### ISSUE TITLE
Contact form response message not showing

### ISSUE THREAD

**Issue by wirtloto** [PopupMaker/Popup-Maker#100]
Hi there,

I'm trying to show the contact form 7 inside the popup. everything works fine a part the message. If you click send doesn't show any message. Any idea why? It's not just invisible but it doesn't print the message for some reason.
![screen shot 2015-06-29 at 2 14 43 pm](https://cloud.githubusercontent.com/assets/11939230/8399818/4d2e4c7e-1e69-11e5-9084-68122f1d81f1.png)

Thanks,
Ale

**Comment by danieliser** [comment]
@wirtloto - Have you tried CF7 support forums? They typically work fine inside popups which leads me to beileive the issue may be with CF7 setup or settings. Does it work if its not in a popup?

**Comment by wirtloto** [comment]
Hi Daniel,

Yes outside the popup works.

Cheers,
Ale
