### ISSUE TITLE
Invite team Crash Reporting Settings Inbound filters Alerting Reports Export Real User Monitoring APM Customers Deployments Application settings Integrations Feature requests What's New 1 Contact Raygun Error: Illegal string offset 'openPopupId' 

### ISSUE THREAD

**Issue by tsviet** [PopupMaker/Popup-Maker#1000]
## Describe the bug

Message: Error: Illegal string offset 'openPopupId'
#0 Raygun4php\RaygunClient::SendError called at [/opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/raygun4wp/main.php:192]
#1 ::error_handler called at [/opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/popup-maker/classes/Admin/BlockEditor.php:121]
#2 PUM_Admin_BlockEditor::add_attributes_to_registered_blocks called at [/opt/bitnami/apps/wordpress/htdocs/wp-includes/class-wp-hook.php:287]
#3 WP_Hook::apply_filters called at [/opt/bitnami/apps/wordpress/htdocs/wp-includes/class-wp-hook.php:311]
#4 WP_Hook::do_action called at [/opt/bitnami/apps/wordpress/htdocs/wp-includes/plugin.php:478]
#5 ::do_action called at [/opt/bitnami/apps/wordpress/htdocs/wp-settings.php:568]
#6 ::require_once called at [/opt/bitnami/apps/wordpress/htdocs/wp-config.php:110]
#7 ::require_once called at [/opt/bitnami/apps/wordpress/htdocs/wp-load.php:37]
#8 ::require_once called at [/opt/bitnami/apps/wordpress/htdocs/wp-blog-header.php:13]
#9 ::require called at [/opt/bitnami/apps/wordpress/htdocs/index.php:17]

## Site information
Popup Maker version: 1.16.7

WordPress version: 5.5.9

PHP version: 7.4.12

## Expected behavior
no error

## Current behavior
Error: Illegal string offset 'openPopupId'

## Steps to reproduce
1. run any page on wp site

## Errors
Error: Illegal string offset 'openPopupId'

**Comment by danieliser** [comment]
I tried duplicating this originally an meant to ask then, but are you still able to reproduce this issue? If not gonna close this.
