### ISSUE TITLE
admin menu doesn't appear when popup-maker is activate

### ISSUE THREAD

**Issue by elocreamars** [PopupMaker/Popup-Maker#1005]
If Popup-Maker is activate on my website, i can't see the wpadminbar on my website.
When i desactivate Popup-Maker plugin, i can see this.

![image](https://user-images.githubusercontent.com/111698451/185800910-7da35abb-510b-4b40-800b-c60a618fc749.png)

Others difficulties, like insert a new image using divi builder occured when Popup-Maker is activated.

## Site information
Popup Maker version: 1.16.7

WordPress version: 6.0.1

Divi Theme version: 4.18.0

PHP version: X.X.X

**Comment by danieliser** [comment]
Can you check your PHP error logs? That indicates there is an error in the PHP rendering the admin bar at a minimum, but not much more.

Also there is an option to disable the admin bar via Popup Maker -> Settings you might try to see if the issue goes away

**Comment by elocreamars** [comment]
Thank you for your answer. 
I don't know why, but without doing any modification of the setting, this trouble disapear.
So, i close this issue.

**Comment by danieliser** [comment]
@elocreamars - Though phantom errors are always of a bit of concern, when they vanish on their own thats a WIN!
