### ISSUE TITLE
Getting review nonce, review uuid, and data-reason code statements in the "100 popup views" notification

### ISSUE THREAD

**Issue by marklchaves** [PopupMaker/Popup-Maker#1018]
## Describe the bug

I'm getting review nonce, review uuid, and data-reason code statements in the "100 popup views" notification. See screen capture.

## Site information
Popup Maker version: 1.17.0

WordPress version: 6.1.1

PHP version: 8.0.12

## Expected behavior

The notification should **NOT** have review nonce, review uuid, and data-reason code statements.

This does not happen in version 1.16.8.

## Current behavior

The notification displays review nonce, review uuid, and data-reason code statements.

## Steps to reproduce
1. Run the SQL statements individually (and as needed) below to reset the 100 views data in the database. Or, use phpMyAdmin.
2. Open a popup at least 2 times on the public-facing side of your site.
3. Go to the Popup Maker admin page (l/wp-admin/edit.php?post_type=popup) to view the message.

```sql
SELECT * FROM `wp_usermeta` WHERE `meta_key` LIKE '%dismissed%'

UPDATE `wp_usermeta` SET `meta_value` = '' WHERE `meta_key` = '_pum_reviews_dismissed_triggers';

SELECT * FROM `wp_options` WHERE `option_name` LIKE '%open_count%' 

UPDATE `wp_options` SET `option_value` = '99' WHERE `option_name` = 'pum_total_open_count';
```

## Additional context

![popup-maker-100-views-review-notification](https://user-images.githubusercontent.com/4658423/204291032-7aa4d37c-5cef-4315-a2ea-3024f38d7a1d.png)

**Comment by marklchaves** [comment]
Speak of the devil ...

https://wordpress.org/support/topic/50-pop-ups-message-error-in-code/

**Comment by danieliser** [comment]
Must be from escaping that output, probably need to explicitly allow script tags or something.

Looking into it.

**Comment by danieliser** [comment]
Resolved in `develop`
