### ISSUE TITLE
1.17.1: PUM admin bar item should display count of popups loaded on current page

### ISSUE THREAD

**Issue by lkraav** [PopupMaker/Popup-Maker#1028]
## Describe the feature request
We're noticing orphan popups getting loaded on landing pages, after people have removed all triggering code, but have forgotten to disable or adjust popup targeting.

Now you might be loading a bunch of extra garbage on every page load that nobody will ever see.

Solution might be simply appending a counter like "Popup Maker (1)" to indicate how many popups are loaded. We might even want to color the number with one of the new `--wp` preset color variables or something to draw attention.

Alternatively, a Query Monitor integration panel would be nice. I'm sure we all can't count how many times QM has saved our behinds by highlighting stray network requests, and other problems.

## Use case
Improve page load speed metrics.

## Example screenshots (if any)
N/A

**Comment by danieliser** [comment]
@lkraav - Good idea.

Query Monitor tools might be useful, but I'm not sure there is something we could add there we don't already show elsewhere (including the console debugger mode).

**Comment by danieliser** [comment]
Opted not to use the normal red, as that indicates "needs attention", but the next release will include a white circle with count of popups loaded on the page.
![image](https://user-images.githubusercontent.com/847818/213364198-d3308a1d-d21b-499b-9559-3a5b6f17b722.png)
