### ISSUE TITLE
Regression: line 125 of classes/AssetCache.php has broken caching in recent versions

### ISSUE THREAD

**Issue by robsheldon** [PopupMaker/Popup-Maker#1039]
Hi,

Commit dda3314 introduced a bug on [line 125 of classes/AssetCache.php](https://github.com/PopupMaker/Popup-Maker/blob/b0067325f6e1d32a3d144f80c1394cc11208cad1/classes/AssetCache.php#L125):

```
if ( true !== get_option( 'pum_files_writeable', true ) ) {
```

If a strict comparison is required here, then the line needs to be changed to:

```
if ( '1' !== get_option( 'pum_files_writeable', true ) ) {
```

See also https://developer.wordpress.org/reference/functions/get_option/, which states that boolean `true` values get stored as a `string(1) "1"` value in `wp_options`, and `"1"` is what `get_option()` returns after that.

I've manually confirmed this behavior.

This bug is causing recent versions of Popup Maker to incorrectly mark its cache as not writeable.

Thanks!

**Comment by robsheldon** [comment]
Looks like line 663 of the same file may have the same bug too: https://github.com/PopupMaker/Popup-Maker/blob/b0067325f6e1d32a3d144f80c1394cc11208cad1/classes/AssetCache.php#L663

```
return true === get_option( 'pum_files_writeable', true ) || true === get_option( '_pum_writeable_notice_dismissed', true );
```

**Comment by danieliser** [comment]
@robsheldon Thanks for the report, marking this one closed as it has already been patched in the `develop` branch.

Your correct, and the final solution was to coerce the get_option into a boolean for the strict comparison.

We are pushing PHPCS cleanup, and this one got by us. We have a review going over all the other changes to strict comparisons looking for anything comparing boolean to possibly non-boolean values, where similar fixes will be employed.
