### ISSUE TITLE
Fix broken EU cookie notices link in the readme.txt file

### ISSUE THREAD

**Issue by marklchaves** [PopupMaker/Popup-Maker#1041]
Change to https://ninjaforms.com/blog/eu-cookie-notices-ninja-forms/

https://github.com/PopupMaker/Popup-Maker/blob/b0067325f6e1d32a3d144f80c1394cc11208cad1/readme.txt#L34

**Comment by marklchaves** [comment]
PR https://github.com/PopupMaker/Popup-Maker/pull/1042

**Comment by danieliser** [comment]
Patched in release changeset.
