### ISSUE TITLE
Error log tool is broken in WordPress VIP Setup

### ISSUE THREAD

**Issue by shreyasikhar** [PopupMaker/Popup-Maker#1043]
## Describe the bug

When the `Popup Maker` plugin is enabled on the [WordPress VIP](https://wpvip.com/) platform, it breaks with a fatal error <img width="609" alt="Screenshot 2023-03-23 at 4 06 40 PM" src="https://user-images.githubusercontent.com/40795917/227177932-6564ae27-7ce4-4e1e-afd6-4f6d32c74b91.png">

The reason for the above error is condition `'direct' === $wp_filesystem->method` on line https://github.com/PopupMaker/Popup-Maker/blob/master/classes/Utils/Logging.php#L119 failing, as with WordPress VIP the value of `'$wp_filesystem->method` is 'vip'.

So, I think we can add extra checks to avoid calling the filesystem methods with a bool.

## Site information
Popup Maker version: 1.18.1

WordPress version: 6.1.1

PHP version: 8.1.9

## Expected behavior

The error log tool should show logs without throwing a fatal error.

## Current behavior

The error log tool is throwing some fatal error due to incompatibility with WordPress VIP platform.

## Steps to reproduce
1. Setup a WordPress VIP instance [(Reference docs)](https://docs.wpvip.com/how-tos/local-development/)
2. Install and Activate the `Popup Maker` plugin
3. Go to `Popup Maker -> Tools -> Error log` from the WP-Admin screen.

**Comment by danieliser** [comment]
Appreciate the report and PR. Can you confirm this change does in fact resolve the error?

**Comment by shreyasikhar** [comment]
Thank you @danieliser 

Yes, it resolves the fatal error attached in the above screenshot and the changes from linked PR won't break other sites as this is just an extra check for the object before calling its methods.

**Comment by ssapire** [comment]
Hi @danieliser 
I am not the technical person on our team, but we enabled the Popup-Maker plugin on our site. I clicked some sort of update or cache link related to your plugin and our website went down. Our developer has indicated that this is the issue related to why that happened and they won't reenable this until the bug is fixed. I am following here to make sure we know when it can be addressed. Thanks!

**Comment by danieliser** [comment]
@ssapire - See my comments above but you have 2 options today:

1. Add the code VIP said to add in their docs: https://docs.wpvip.com/technical-references/vip-go-files-system/media-uploads/#h-wp-filesystem-api
2. Disable asset caching in our plugin entirely via the Popup Maker -> Settings page.

**Comment by dougaxe1** [comment]
Hello, @danieliser. I just tried the second option above and on VIP + Popup Maker 1.18.2, and unfortunately the Popup Maker -> Tools page (/wp-admin/edit.php?post_type=popup&page=pum-tools) still throws the fatal error described in this ticket.

Our client reported to us another functional area broken by this issue in the preview functionality. Attempting to preview a popup throws a full-screen fatal error:
![image](https://github.com/PopupMaker/Popup-Maker/assets/10548206/c336be5b-fabd-4546-aedc-0eb7b6d12d29)

We have even attempted to disable logging functionality with `define( 'PUM_DISABLE_LOGGING', true )`, however this too does not prevent the filesystem check (but it should).

I can test the VIP WP Filesystem code, but with logging disabled, it should short circuit all filesystem checks altogether.

**Comment by danieliser** [comment]
Constant should now be respected, and we check that the method exists before using it in these sections of code.
