### ISSUE TITLE
Error PHP Fatal error: Uncaught TypeError: array_merge(): Argument #1 must be of type array

### ISSUE THREAD

**Issue by marklchaves** [PopupMaker/Popup-Maker#1054]
## Describe the bug

Error PHP Fatal error: Uncaught TypeError: array_merge(): Argument `#1` must be of type array, null given in /wp-content/plugins/popup-maker/classes/Admin/Shortcode/UI.php:173

## Site information
Popup Maker version: 1.18.2

WordPress version: 6.3.2

PHP version: 8.1.9

## Expected behavior

We should probably check that `$plugin_array` is valid before calling `array_merge()`.

https://github.com/PopupMaker/Popup-Maker/blob/3e720bf9021f889ee34384b5d5ea417822926b7f/classes/Admin/Shortcode/UI.php#L171

## Current behavior

Fatal error thrown when using Popup Maker with [WP Frontend Profile plugin](https://wordpress.org/plugins/wp-front-end-profile/).

## Steps to reproduce
From the customer.

1. Fresh WP
2. Gravity Form
3. Popup maker

All works fine

4. Wp Front end profile plugin installed and there the error from PopupMaker appears
5. Error PHP Fatal error: Uncaught TypeError: array_merge(): Argument `#1` must be of type array, null given in /wp-content/plugins/popup-maker/classes/Admin/Shortcode/UI.php:173

## Errors

Error PHP Fatal error: Uncaught TypeError: array_merge(): Argument `#1` must be of type array, null given in /wp-content/plugins/popup-maker/classes/Admin/Shortcode/UI.php:173

**Comment by danieliser** [comment]
Added a check for and cast as array
