### ISSUE TITLE
Network activating causes fatal error

### ISSUE THREAD

**Issue by s-acv2** [PopupMaker/Popup-Maker#1057]
## Describe the bug

A critical error occurs on multi-sites when activating Popup Maker network-wide.

## Site information
Popup Maker version: 1.18.2

WordPress version: 6.4.3

PHP version: 8.1.27

## Expected behavior

After the user clicks on Network Activate, it should activate & display "Network Deactivate".

## Current behavior

Triggers a fatal error.

## Steps to reproduce
1. Go to the Network Dashboard -- > Plugins page of a multisite.
2. Click 'Network Activate'.
3. Triggers Fatal error.

**Comment by danieliser** [comment]
Unable to replicate.
