### ISSUE TITLE
Plugin conflict with Fluent forms affecting speed

### ISSUE THREAD

**Issue by s-acv2** [PopupMaker/Popup-Maker#1059]
## Describe the bug

Plugin conflict with Fluent forms causes slow speed.

## Site information
Popup Maker version: 1.18.2

WordPress version: 6.4.3

PHP version: 8.2.15

## Expected behavior

The site should run at regular speed.

## Current behavior

The site is running slower than expected.

## Steps to reproduce
Unable to reproduce.

**Comment by danieliser** [comment]
Just added Fluent Form support and saw no issues.
