### ISSUE TITLE
Deprecation notice effecting popup behavior.

### ISSUE THREAD

**Issue by s-acv2** [PopupMaker/Popup-Maker#1061]
## Describe the bug

A deprecation notice is affecting popup performance.

## Site information
Popup Maker version: 1.18.2

WordPress version: X.X.X

PHP version: X.X.X

## Errors

[Deprecation] The keyword 'searchfield-cancel-button' specified to an 'appearance' property is not standardized. It will be removed in the future.

**Comment by danieliser** [comment]
Seems unrelated to our plugin and more likely caching issue or similar. There is no reference in our code base to this line, and the screen caps show lots of broken css files not loading which indicates other bigger issues.
