### ISSUE TITLE
Settings not saved error message shows when there are no changes to save

### ISSUE THREAD

**Issue by marklchaves** [PopupMaker/Popup-Maker#1063]
## Describe the bug

Popup Maker plugin settings page (/wp-admin/edit.php?post_type=popup&page=pum-settings) displays an "There must have been an error, settings not saved successfully!" error when you click **Save** without making any setting changes.

Also, the error message has an "x" to close or dismiss it, but it doesn't work.

See the short GIF.

![popup-maker-settings-not-saved-error](https://github.com/PopupMaker/Popup-Maker/assets/4658423/095a98f5-b639-4b6c-8bf3-1aaebc585ad3)

## Site information
Popup Maker version: 1.18.2

WordPress version: 6.4.3

PHP version: 8.1.23

## Expected behavior

You shouldn't get the error when you don't make any changes and hit **Save**.

The error message should disappear when you click the "x".

## Current behavior

See GIF.

## Steps to reproduce

See GIF.

## Errors

No.

**Comment by danieliser** [comment]
Fixed
