### ISSUE TITLE
Allow more than one popup at a time

### ISSUE THREAD

**Issue by danieliser** [PopupMaker/Popup-Maker#12]
Original Issue: https://wordpress.org/support/topic/double-popups-1

**Comment by danieliser** [comment]
This isn't ready, bumping to v1.2.1

**Comment by anneiven** [comment]
Hello danieliser,

I'm using v.1.2.2 of your wonderful plugin, but I'm still havin' this problem (cannot have more than one popup opened at the same time). Can you tell me if this feature has been bumped again or if it's me that I'm doing something wrong?

Thank you

**Comment by danieliser** [comment]
@anneiven - Hmm this is a duplicate issue and it has been added in v1.3. #108.

v1.3 beta should be announced later today or tomorrow.

Closing this issue since its been done.
