### ISSUE TITLE
Close button displaying improperly

### ISSUE THREAD

**Issue by mholen** [PopupMaker/Popup-Maker#122]
This is novadigi from wordpress.org. I just installed 1.3 and can see the close button at the top right isn't displaying properly. I've attached a screenshot.

![2015-07-27 11_58_57-real endeavors _ lease to own owner financed properties](https://cloud.githubusercontent.com/assets/5512576/8910839/05809f22-3457-11e5-8ea0-2fa8daf0a188.jpg)

**Comment by danieliser** [comment]
Set the close height and width to 0 which makes it auto.
