### ISSUE TITLE
Multiple Popups

### ISSUE THREAD

**Issue by mungle** [PopupMaker/Popup-Maker#125]
Unable to see the check button in "Display Setting" tab on beta 1.3

**Comment by danieliser** [comment]
Stackable 	This enables other popups to remain open. 

Its under Position. Just checked and its there in latest version.

**Comment by mungle** [comment]
![Screenshot] (http://i58.tinypic.com/10qx5i1.jpg)

**Comment by danieliser** [comment]
You may need to redownload. Seems like you must have an old copy of the plugin.

https://github.com/PopupMaker/Popup-Maker/blob/v1.3-general/includes/admin/popups/metabox-display-fields.php#L240

Here is the latest zip https://github.com/PopupMaker/Popup-Maker/archive/v1.3-general.zip
