### ISSUE TITLE
Seems to be a conflict with Beaver Builder

### ISSUE THREAD

**Issue by mrjonwilson** [PopupMaker/Popup-Maker#138]
Hey Daniel! I hope you are doing well.

I am using the scroll trigger add-on. There seems to be a conflict with the Beaver Builder plugin. The popup does popup, but does not stick, and the positioning is off. I have it set to 10px from right and bottom.

Demo Site: http://cti.flywheelsites.com/

Check Chrome Developer Tools Console. Any ideas?

**Comment by danieliser** [comment]
Hmm, only the right is coming through and the position isn't set to fixed, so double check the fixed position is still checked.

**Comment by mrjonwilson** [comment]
Hey Daniel,

When I check the checkbox for fixed position, it is removed upon saving.

**Comment by danieliser** [comment]
Hey, it should only force uncheck when you first select a responsive size. It shouldn't uncheck on page load. Are you using v1.3.6?

**Comment by mrjonwilson** [comment]
Yes. I'm on v1.3.6.

This is what I'm seeing:
<iframe class="tscplayer_inline embeddedObject" name="tsc_player" scrolling="no" frameborder="0" type="text/html" style="overflow:hidden;" src="http://www.screencast.com/users/mrjonwilson/folders/Camtasia/media/e2405de9-26d7-4d22-b866-7fd6a92b854a/embed" height="1968" width="3120" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>

**Comment by danieliser** [comment]
Ok gonna have to disable that unchecking functionality and maybe do it a different way. Causing more problems than its worth.

**Comment by mrjonwilson** [comment]
Oh! So that was a feature? ;)

**Comment by danieliser** [comment]
Yea kinda, fixed doesn't work well for mobile screens and responsive sizes. So was trying to be smooth and auto disable fixed when you select a mobile size as that is one of the most asked questions I see.
