### ISSUE TITLE
Build WP API support

### ISSUE THREAD

**Issue by danieliser** [PopupMaker/Popup-Maker#159]
popup endpoint should include settings and data attr.

Will allow for moving of the popup loading to a json request on load rather than preloading the popups.

Potential setup criteria.
- Allow popups to still be hard loaded in the footer, such as age verification where it needs to be available immediate.
- Pass variables from the browser via JS to the JSON call such as browser, device info, screen size, element exists, etc. These can be checked in the WP API request and used to determine if a popup should load.

**Comment by lkraav** [comment]
+1000

**Comment by danieliser** [comment]
Gonna punt this to v1.5 as time is short and this is a major overhaul. We are also making many other major changes so now may not be the best time to do this.

Also currently WP Core only has minimal support for the api and this requires a lot of bridging which won't be necessary in the near future.

**Comment by danieliser** [comment]
Have been testing for this lately, there are a lot of issues when it comes to compatibility. Most form plugins won't support this since the content would be loaded via ajax and never initialized properly.

Scrapping this and planning to add something else in the near future instead.
