### ISSUE TITLE
Gravity Forms datepick not working in popups.

### ISSUE THREAD

**Issue by danieliser** [PopupMaker/Popup-Maker#165]
https://wordpress.org/support/topic/gravity-forms-datepicker-does-not-work-in-popup?replies=6#post-7503172

**Comment by danieliser** [comment]
Solution provided by user @Rick Radko

Hi, I just bumped into this too. The datepicker.min.css being loaded by Gravity forms is only setting a z-index of 9999, but hits it with !important, which trumps the 2000000000 set by popup maker.

body div#ui-datepicker-div[style] {
    z-index: 9999 !important;
}

add_action( 'wp_head', 'gf_datepicker_fix', 1000000 );
function gf_datepicker_fix(){
?><style>
	body div#ui-datepicker-div[style] {
	    z-index: 2000000000 !important;
	}
</style> <?php
}

**Comment by rick** [comment]
![](http://49.media.tumblr.com/tumblr_m4kb52tY6r1qjemo2o1_250.gif)

**Comment by danieliser** [comment]
Merged
