### ISSUE TITLE
Add grunt task to auto grab the latest list of extensions and save it to the extensions.json file

### ISSUE THREAD

**Issue by danieliser** [PopupMaker/Popup-Maker#188]
This can be done as part of a final build process.

Grab a copy of the latest json feed and save it to that file.

**Comment by fpcorso** [comment]
What if we instead just pulled in the feed (http://wppopupmaker.com/extensions/feed/) and used the built in WP feed function and transients to save it? We could update the feed every day or week so newer extensions are shown without having to update the plugin.

**Comment by fpcorso** [comment]
For example, a snippet from QSM to gather the feed:

```
$qmn_feed = fetch_feed('http://quizandsurveymaster.com/feed');
				if (!is_wp_error($qmn_feed)) {
					$qmn_feed_items = $qmn_feed->get_items(0, 5);
					foreach ($qmn_feed_items as $feed_item) {
					    $qmn_rss[] = array(
					        'link' => $feed_item->get_link(),
					        'title' => $feed_item->get_title(),
					        'description' => $feed_item->get_description(),
									'date' => $feed_item->get_date( 'F j Y' ),
									'author' => $feed_item->get_author()->get_name()
					    );
					}
				}
```

Then that is save to a transient. When needed, we just foreach through the $qmn_rss. Same can be done for extensions.

**Comment by danieliser** [comment]
The code is already in the core to do this from a JSON feed on the love site, BUT, since the site is on WPEngine and they bill by #of visitors, and they track visitors as unique visitors per day.

So each server that requests it will be counted as a unique visitor every day that it connects. With so many sites using plugin we would be over max in no time. Will be moving to pagely in the future at which point we will be in commenting out the remote JSON source.

**Comment by fpcorso** [comment]
Ah, that makes sense. I was wondering why you wanted to build it into a JS.

**Comment by danieliser** [comment]
Building it into a build task will just mean that it gets updated every build without having to think about it. Currently there are several new extensions not listed.
