### ISSUE TITLE
Overlay on top

### ISSUE THREAD

**Issue by finchkelsey** [PopupMaker/Popup-Maker#197]
since WP update the pop overlay appears on top of the screen making the op up content inaccessible. Any help would be appreciated!
Thanks

http://canadianbeef.wpengine.com/

Brand Partner -> Trade Resources ->Beef Cut Diagram

**Comment by danieliser** [comment]
Looks like your theme added a unneccesary z-index to the #wrap_all element. Set it to auto.

#wrap_all { z-index: auto!important; }
