### ISSUE TITLE
Top popup link in list of popup links does not execute

### ISSUE THREAD

**Issue by ragordon** [PopupMaker/Popup-Maker#227]
I created a list of popup forms in a sidebar widget (see below code) and all of the pop ups work except the top one on the list. I tested it be changing the top pop up for one that I confirmed worked and same result. What do you think the issue is?
<h4>QUICK LINKS</h4>
<h6><a href="#" class="popmake-114689">HO Registration</a></h6> 
<h6><a href="#" class="popmake-114496">Favorite this HOA</h6>
<h6><a href="#" class="popmake-114950">Suggestion Box</h6>
<h6><a href="#" class="popmake-114839">Board Registration</h6>
<h6><a href="#" class="popmake-114738">Connected Homeowners </h6>
<h6><a href="#" class="popmake-114900">HOA Data Update</h6>
Thanks 
Richard

**Comment by ragordon** [comment]
Update,
Reinstalled the plugin and it seems to work now.
Sorry

**Comment by danieliser** [comment]
@ragordon Glad you got it.

**Comment by ragordon** [comment]
Hi Daniel
Glad to see you have launched the new version. I have updated and completed
all of the admin settings ( I think). I read through your change log and
noticed that you allow for popups to scroll within their over lay. Not
quite sure what that means. First there is no overlay, like before, which
doesn't matter to me, but no matter how I arrange the settings I can not
get a longer form to scroll. It is like it is still in a fixed position so
the bottom of the form can't be viewed.
Is the traditional overlay, no longer?
The fixed position ck box can not be unchecked.
This was a problem we experienced last last year- I must not be setting
things properly
Richard

On Wednesday, January 6, 2016, Daniel Iser <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

> Closed #227 <https://github.com/PopupMaker/Popup-Maker/issues/227>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PopupMaker/Popup-Maker/issues/227#event-507572139>.
>


-- 
Dick Gordon
916-224-2575

**Comment by danieliser** [comment]
@ragordon - Sounds like something is not right on your end for sure. Fixed position can most certainly be unchecked now :), Scrolling is done 2 different ways if fixed is disabled.

If the overlay is not disabled then the scroll bar is added to the overlay and the page behind it stays still. If the overlay is disabled the popup scrolls with the page as it used to.

By default with overlay open if the popup is not longer than the bottom of the screen no scroll bar is shown, if the content is longer it should scroll perfectly. This was one of the biggest changes overall, specifically for that reason.

Do you have a link?

**Comment by ragordon** [comment]
Daniel,
There is clearly some sort of conflict, maybe with another plugin, I just
don't know.
Here is a link to a test page:
http://www.hoahomepage.com/find-hoas-2/abc-timeshare-association/#
On this page on the left there is a photo gallery (popup # 116135), I can't
seem to change the theme for this popup, or uncheck the "disable the
overlay" - this popup is suppose to display two rows of 3 photos, as it did
before- but now it displays in a single column, even if I set the popup
size to something other than auto.
Also on this page (in the middle column) you see registrations, under Quick
Links- clicking on this gives you three options to register (is this a
problem having popups within a popup) clicking on the Homeowner
registration (popup #116301), the form pops up, but you cannot see the
submit button, the popup is fixed. On the settings page, the fixed position
is unchecked, disable display unchecked (but there is no overlay), the
click on overlay to close is checked, but cannot be unchecked. I tried
changing the theme for the popup and it does not change the display.
I set up an admin login for you : email used: support@wppopupmaker.com PW:
popupmaker2016

Would appreciate your help in figuring out what is going on. I did confirm
that the plugin has been updated to 1.4.9
Thanks Richard

On Mon, May 2, 2016 at 10:37 PM, Daniel Iser <notifications@github.com>
wrote:

> @ragordon <https://github.com/ragordon> - Sounds like something is not
> right on your end for sure. Fixed position can most certainly be unchecked
> now :), Scrolling is done 2 different ways if fixed is disabled.
>
> If the overlay is not disabled then the scroll bar is added to the overlay
> and the page behind it stays still. If the overlay is disabled the popup
> scrolls with the page as it used to.
>
> By default with overlay open if the popup is not longer than the bottom of
> the screen no scroll bar is shown, if the content is longer it should
> scroll perfectly. This was one of the biggest changes overall, specifically
> for that reason.
>
> Do you have a link?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/PopupMaker/Popup-Maker/issues/227#issuecomment-216442903>
>



-- 
Dick Gordon
916-224-2575

**Comment by ragordon** [comment]
Daniel,
I just noticed if I want to change the theme, if I preview it first on the
popup edit page, the change will apply on the live page.
Richard

On Tue, May 3, 2016 at 7:45 AM, Richard Gordon <ragordonco@gmail.com> wrote:

> Daniel,
> There is clearly some sort of conflict, maybe with another plugin, I just
> don't know.
> Here is a link to a test page:
> http://www.hoahomepage.com/find-hoas-2/abc-timeshare-association/#
> On this page on the left there is a photo gallery (popup # 116135), I
> can't seem to change the theme for this popup, or uncheck the "disable the
> overlay" - this popup is suppose to display two rows of 3 photos, as it did
> before- but now it displays in a single column, even if I set the popup
> size to something other than auto.
> Also on this page (in the middle column) you see registrations, under
> Quick Links- clicking on this gives you three options to register (is this
> a problem having popups within a popup) clicking on the Homeowner
> registration (popup #116301), the form pops up, but you cannot see the
> submit button, the popup is fixed. On the settings page, the fixed position
> is unchecked, disable display unchecked (but there is no overlay), the
> click on overlay to close is checked, but cannot be unchecked. I tried
> changing the theme for the popup and it does not change the display.
> I set up an admin login for you : email used: support@wppopupmaker.com
> PW: popupmaker2016
>
> Would appreciate your help in figuring out what is going on. I did confirm
> that the plugin has been updated to 1.4.9
> Thanks Richard
>
> On Mon, May 2, 2016 at 10:37 PM, Daniel Iser <notifications@github.com>
> wrote:
>
>> @ragordon <https://github.com/ragordon> - Sounds like something is not
>> right on your end for sure. Fixed position can most certainly be unchecked
>> now :), Scrolling is done 2 different ways if fixed is disabled.
>>
>> If the overlay is not disabled then the scroll bar is added to the
>> overlay and the page behind it stays still. If the overlay is disabled the
>> popup scrolls with the page as it used to.
>>
>> By default with overlay open if the popup is not longer than the bottom
>> of the screen no scroll bar is shown, if the content is longer it should
>> scroll perfectly. This was one of the biggest changes overall, specifically
>> for that reason.
>>
>> Do you have a link?
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/PopupMaker/Popup-Maker/issues/227#issuecomment-216442903>
>>
>
>
>
> --
> Dick Gordon
> 916-224-2575
>
>
>


-- 
Dick Gordon
916-224-2575

**Comment by danieliser** [comment]
@ragordon The previews shouldn't effect anything. They are passive in nature. They take the same code used to generate popups on the front and show a preview, if it works there it should work everywhere.

Can you tell me exactly what I am looking at on that page you linked?

**Comment by ragordon** [comment]
Daniel,
I think I have discovered something that explains what is going on. I am
still testing but, many of my popups are embedded in a CPT template, when I
launch the popup outside of the template, like in a sidebar, the
functionality seems to return. I will keep looking at it and report back,
but for now, no need for you to spend any time on it.
Thanks
Richard

On Tue, May 3, 2016 at 3:25 PM, Richard Gordon <ragordonco@gmail.com> wrote:

> On that page there are a dozen or so popups. I use popups to stay in the
> loop and pass CPT meta data to various forms.
>
> On Tue, May 3, 2016 at 9:50 AM, Daniel Iser <notifications@github.com>
> wrote:
>
>> @ragordon <https://github.com/ragordon> The previews shouldn't effect
>> anything. They are passive in nature. They take the same code used to
>> generate popups on the front and show a preview, if it works there it
>> should work everywhere.
>>
>> Can you tell me exactly what I am looking at on that page you linked?
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/PopupMaker/Popup-Maker/issues/227#issuecomment-216592807>
>>
>
>
>
> --
> Dick Gordon
> 916-224-2575
>
>
>


-- 
Dick Gordon
916-224-2575

**Comment by ragordon** [comment]
Hi Daniel,
I have two popups with forms in them. I have both set to allow other popups
to remain open. The user wants to complete form A, but he first needs to
complete form B, so clicks open form B completes and summits it. However,
on submit, form A disappears. Is it suppose to stay open after form B is
submitted or not?

On Thu, May 5, 2016 at 10:26 AM, Richard Gordon <ragordonco@gmail.com>
wrote:

> Daniel,
> I think I have discovered something that explains what is going on. I am
> still testing but, many of my popups are embedded in a CPT template, when I
> launch the popup outside of the template, like in a sidebar, the
> functionality seems to return. I will keep looking at it and report back,
> but for now, no need for you to spend any time on it.
> Thanks
> Richard
>
> On Tue, May 3, 2016 at 3:25 PM, Richard Gordon <ragordonco@gmail.com>
> wrote:
>
>> On that page there are a dozen or so popups. I use popups to stay in the
>> loop and pass CPT meta data to various forms.
>>
>> On Tue, May 3, 2016 at 9:50 AM, Daniel Iser <notifications@github.com>
>> wrote:
>>
>>> @ragordon <https://github.com/ragordon> The previews shouldn't effect
>>> anything. They are passive in nature. They take the same code used to
>>> generate popups on the front and show a preview, if it works there it
>>> should work everywhere.
>>>
>>> Can you tell me exactly what I am looking at on that page you linked?
>>>
>>> —
>>> You are receiving this because you were mentioned.
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/PopupMaker/Popup-Maker/issues/227#issuecomment-216592807>
>>>
>>
>>
>>
>> --
>> Dick Gordon
>> 916-224-2575
>>
>>
>>
>
>
> --
> Dick Gordon
> 916-224-2575
>
>
>


-- 
Dick Gordon
916-224-2575
