### ISSUE TITLE
Change Modal Text To Popup For Consistency

### ISSUE THREAD

**Issue by fpcorso** [PopupMaker/Popup-Maker#274]
We should change the text that says "modal" to say "popup" wherever found for consistency sake. I will list them here as I find them:

https://github.com/PopupMaker/Popup-Maker/blob/v1.4-general/includes/admin/welcome/about.php#L111

https://github.com/PopupMaker/Popup-Maker/blob/v1.4-general/includes/admin/welcome/getting-started.php#L150

**Comment by danieliser** [comment]
Absolutely. Those entire sections if we keep them need to be rewritten. They have been the same since v1.0 and were written by a partner that isn't involved anymore. Their is a lot of room for improvement there, maybe even a quick video at some point.

**Comment by danieliser** [comment]
Disabled the welcome for now. Will revisit later.
