### ISSUE TITLE
WP_Post to int conversion error in Theme Settings Meta Box

### ISSUE THREAD

**Issue by fpcorso** [PopupMaker/Popup-Maker#275]
When installing 1.3.9, no themes were created while using that version including default or custom. Updated to 1.4 and ran upgrade routine. Went to popup settings and encountered this error inside each of the options in the select box in the Theme Settings meta box:

Notice:  Object of class WP_Post could not be converted to int in C:\xampp\htdocs\wordpress\wp-content\plugins\popup-maker\includes\class-pum-popup.php on line 145

![theme_settings_error](https://cloud.githubusercontent.com/assets/9730040/12738768/b370185a-c931-11e5-98a9-c2a32cb602f2.png)

**Comment by danieliser** [comment]
This one was a pain. Finally tracked it to the last migration routine that checks to be sure every popup has a valid theme assigned. It was saving the entire default theme rather than just the ->ID.
