### ISSUE TITLE
Conditions upgrade routine misses specific posts and pages.

### ISSUE THREAD

**Issue by fpcorso** [PopupMaker/Popup-Maker#276]
I installed 1.3.9. For the conditions, I set the following options:

![example_conditions_error](https://cloud.githubusercontent.com/assets/9730040/12738875/b26e3e72-c932-11e5-8824-5a19dee272ff.png)

However, when upgrading, it converted to this:

![conditions_error](https://cloud.githubusercontent.com/assets/9730040/12738798/ec5b466c-c931-11e5-83f0-9ff210cf1b47.png)

Where the selected posts and pages were not kept.

**Comment by danieliser** [comment]
You didn't add the pages first. Checking them in v1.3.9 != adding them. You have to click the add selected button to add the checked items to a hidden text field. Bad UX to begin with. Try it one more time. You can test by simply editing the wp_options pum_db_ver to 2, adding the pages, then processing updates again.

**Comment by fpcorso** [comment]
Ah, that makes sense. Yeah, that fixes this one @danieliser
