### ISSUE TITLE
Condense down the admin notices upon upgrade

### ISSUE THREAD

**Issue by fpcorso** [PopupMaker/Popup-Maker#277]
Should condense down the 8,000 admin notices that appear when a user upgrades.

![example_export](https://cloud.githubusercontent.com/assets/9730040/12739035/c6034288-c933-11e5-8455-f2f395f53e70.png)

**Comment by danieliser** [comment]
What do you think of this wording.

Popup Maker: Pending database upgrades. Click here to get started.

**Comment by fpcorso** [comment]
@danieliser Can the plugin function if the user does not click on the notice? Should it sound a little more urgent like:

"Popup Maker: Pending database upgrades. You must click here to finish your upgrade."

**Comment by danieliser** [comment]
@fpcorso: good point. Maybe

"Popup Maker: Important database upgrades required. Please click here to complete these changes now."

**Comment by fpcorso** [comment]
Yeah, @danieliser I like that one.

**Comment by danieliser** [comment]
I can even make it red instead of green. or highlight "Important" in red with an exclamation point Icon

**Comment by danieliser** [comment]
Same icon we use for negative conditions.

**Comment by danieliser** [comment]
This is what it looks like now.

![screenshot from 2016-02-02 22 45 08](https://cloud.githubusercontent.com/assets/847818/12772361/a8571400-c9fe-11e5-99d4-f961acb5bfc4.png)
