### ISSUE TITLE
Add Full WPML support

### ISSUE THREAD

**Issue by danieliser** [PopupMaker/Popup-Maker#279]
This needs to be a priority. We need to integrate with as many language plugins as possible.

Here is the core issue as seen many times.

Popup in Lang1 targeting pages in Lang1

User translates Popup into Lang2 but conditions still target Lang1 during clone.

Possible solutions:
- Add WPML Language Selection Conditions. - https://wpml.org/forums/topic/is_pagex-how-to-point-to-a-page-and-its-tranlations/
- Rewrite conditions on the fly based on the language, checking each condition against the new language finding replacements. (Very Performance Degrading)
- Trick WPML into creating a completely new popup in the correct language mapping new pages. < Theoretical (Not sure how this would be done or if this would even work)
- Add a new condition that forces a popup on one language only. (Not 100% sure this would work, but may be the simplest solution.)
  - Can add this condition by default if WPML is enabled, defaulting it to the currently selected language.

**Notify Users:**
- https://wordpress.org/support/topic/multilingual-support-wpml-1?replies=1

**Comment by 972creative** [comment]
What's the status on this feature?

Also, can you identify which custom fields [these two elements](http://prntscr.com/dfj3uj) relate to so we can mark the fields for translation?

Thanks,
Todd

**Comment by danieliser** [comment]
@972creative Are those in relation to the Terms & Conditions extension? if so they are currently stored in a serialized post_meta key, it can be filtered, but the next release moves all of that to the shortcode itself. That will also add the terms_conditions shortcode to the PM Shortcode editor / visual previews.

Then those will be in the content of the post/popup itself.

**Comment by danieliser** [comment]
I just tested with the latest WPML and the only issue I am seeing are:

- [ ] Popups are not enabled for translation by default.
- [ ] Popup post_meta are not copied correctly, resulting in missing triggers, cookies, etc.
- [ ] Popup conditions are not properly translated during post_meta copying in some cases.

All in all very fixable.

**Comment by danieliser** [comment]
The basics are complete. Other than having to enable this for popup post type its ready to go.
