### ISSUE TITLE
Customer field not functioning in woocommerce order page

### ISSUE THREAD

**Issue by web-hosting-uk** [PopupMaker/Popup-Maker#307]
After popup maker updated a few days ago, within admin on woocommerce orders page the customer field no longer works and is blank apart from the placeholder Guest. I think popup maker may be affecting woocommerce class="wc-customer-search" in class-wc-meta-box-order-data.php.

**Comment by danieliser** [comment]
@web-hosting-uk Already patched this for v1.4.8 hopefully going out later today.

**Comment by danieliser** [comment]
See 3b844f5856f7b82d250f7245c7ae4a92a8ef26d0 and 5ca708965c8b8ff60cb137fbb5a4f06926ae8891
