### ISSUE TITLE
1.4.8: select2 wp-admin conflicts with woocommerce-2.5.5

### ISSUE THREAD

**Issue by lkraav** [PopupMaker/Popup-Maker#308]
Dialogs don't load and product admin screen gets broken. It looks like a cross-plugin race condition of some sort, where Popup Maker thinks `select2` is registered, enqueued or loaded and tries to use it too early. WC, Yoast SEO, Popup Maker, and probably host of others are all using it now... I guess misunderstandings are bound to happen.

https://<server>/wp-content/plugins/popup-maker/assets/js/admin.min.js?ver=1.4.8

![screenshot from 2016-04-28 15-30-23](https://cloud.githubusercontent.com/assets/147228/14885793/28c9a112-0d56-11e6-9b5c-0a7833552970.png)

cc @anxalicious

**Comment by danieliser** [comment]
This should have already been resolved in v1.4.8. In fact we entirely sandboxed it under the new name pumselect2().

I tested with all of the offending plugins enabled and found no JS errors. Can you try clearing your browser cache to be sure that your loading the latest admin.js file, v1.4.7's JS would throw that error, but v1.4.8 wouldn't as it doesn't call .select2() anywhere, now calls pumselect2() instead.

We no longer enqueue it the right way as it appears that everyone else is still using an old version (3.5.2) and most have customizations in place that will absolutely break if updating to 4. If it were not for the customization's such as ajax searching in WooCommerce then v4 is backward compatible.

In most cases I would just update our code to work with v3.5 but this will not be one of them. Ultimately Select2 v4 was the culmination of direct help and input from WP Core team and accessibility teams to get it ready for inclusion into the core. So they will have to update theirs in the near future anyways.

Secondly WP has made it a point this last 2 years to make everything Accessible. v3.5.2 could never be included in WP core as it utterly fails accessibility tests. So for me to go backward removes our accessibility.

See
- https://github.com/PopupMaker/Popup-Maker/commit/5ca708965c8b8ff60cb137fbb5a4f06926ae8891#diff-e7704c2df23b9fc3a7715723ec4b0758L186
- https://github.com/PopupMaker/Popup-Maker/blob/master/assets/js/admin.js#L6277-L6291

In v1.4.9 I have made a slight adjustment fixing some occasional 'amd' is undefined errors, but your not getting that so I am thinking likely cached scripts.

**Comment by danieliser** [comment]
@lkraav - Before I move on, can you by chance do it again with SCRIPT_DEBUG set to true and click the black arrow showing the stacktrace? I just looked and may have found where our sandboxed version makes one reference to the global $().select2 rather than pumselect2. That could be it but I need to see what line that error is triggered on.

**Comment by lkraav** [comment]
![screenshot from 2016-04-29 13-05-03](https://cloud.githubusercontent.com/assets/147228/14913344/0b65fb9c-0e0b-11e6-9a0d-5bd13bbb629e.png)

@danieliser done, see if this screenshot helps.

**Comment by danieliser** [comment]
This was resolved in v1.4.9. Currently we namespace select2 until more plugins move to the latest version.
