### ISSUE TITLE
Add AMP support

### ISSUE THREAD

**Issue by danieliser** [PopupMaker/Popup-Maker#349]
The AMP plugins some users reported using are:
- http://www.markryancreative.com/wp-amplifier/

**Comment by danieliser** [comment]
Not sure how viable this is. AMP currently doesn't support popups or overlays, so this is an issue we can't solve until Google allows it.

**Comment by s-acv2** [comment]
After internal discussion, closing because it was determined this is no longer viable.

**Comment by s-acv2** [comment]
After internal discussion, closing because it was determined this is no longer viable.
