### ISSUE TITLE
When creating a new popup the numeric values can be set to anything.

### ISSUE THREAD

**Issue by Dzuum** [PopupMaker/Popup-Maker#351]
Concerns both "Animation Speed", "Top" (position) and "Close Button Delay". See attached picture. If in the field something is manually typed, the popup can be saved as is.

![popup](https://cloud.githubusercontent.com/assets/9950729/19395584/00bb2846-9247-11e6-955f-5daefeb08b14.png)

**Comment by danieliser** [comment]
@dzuum - is it sanitizing the value at least? I.e. Are you able to insert some JavaScript or does that get stripped?

I can add a validation check to this fields on the front end by making them number fields. That should solve it.

**Comment by Dzuum** [comment]
I tried inserting something, but it saved as is. Not sure if the script gets run, though. The validation check sounds good. It does do some kind of validation, when pressing the +/- buttons. If I type letters and press the button, it reverts to NaN, although it lets me save the value as "NaN", too.

**Comment by danieliser** [comment]
@Dzuum Thanks for the report. Its patched in the linked commit.
