### ISSUE TITLE
Fix divi theme issues with popup data attributes.

### ISSUE THREAD

**Issue by danieliser** [PopupMaker/Popup-Maker#365]
Currently the popup data attribute displays some error messaging from the divi & elegant themes collection. Doesn't cause errors but its ugly and an annoyance for support & users.

**Comment by danieliser** [comment]
Need more info to duplicate this. Fresh install of the theme didn't cause it. Even tried bogus update credentials.

**Comment by danieliser** [comment]
Here is what I have found so far:

This is the data attribute whos data is being corrupted:

```
{
	"id": 4363,
	"slug": "andy",
	"theme_id": 2817,
	"cookies": [],
	"triggers": [
		{
			"type": "click_open",
			"settings": {
				"extra_selectors": ".andy",
				"do_default": null,
				"cookie": {
					"name": null
				}
			}
		}
	],
	"mobile_disabled": null,
	"meta": {
		"display": {
			"size": "medium",
			"responsive_min_width": "",
			"responsive_max_width": "",
			"custom_width": "640",
			"custom_height": "380",
			"animation_type": "fade",
			"animation_speed": "350",
			"animation_origin": "center top",
			"position_bottom": "<em>Before you can receive product updates, you must first authenticate your Elegant Themes subscription. To do this, you need to enter both your Elegant Themes Username and your Elegant Themes API Key into the Updates Tab in your theme and plugin settings. To locate your API Key, <a href=\"https://www.elegantthemes.com/members-area/api-key.php\" target=\"_blank\">log in</a> to your Elegant Themes account and navigate to the <strong>Account > API Key</strong> page. <a href=\"http://www.elegantthemes.com/gallery/divi/documentation/update/\" target=\"_blank\">Learn more here</a></em>. If you still get this message, please make sure that your Username and API Key have been entered correctly",
			"location": "center top",
			"position_right": "<em>Before you can receive product updates, you must first authenticate your Elegant Themes subscription. To do this, you need to enter both your Elegant Themes Username and your Elegant Themes API Key into the Updates Tab in your theme and plugin settings. To locate your API Key, <a href=\"https://www.elegantthemes.com/members-area/api-key.php\" target=\"_blank\">log in</a> to your Elegant Themes account and navigate to the <strong>Account > API Key</strong> page. <a href=\"http://www.elegantthemes.com/gallery/divi/documentation/update/\" target=\"_blank\">Learn more here</a></em>. If you still get this message, please make sure that your Username and API Key have been entered correctly",
			"position_top": "100",
			"position_left": "<em>Before you can receive product updates, you must first authenticate your Elegant Themes subscription. To do this, you need to enter both your Elegant Themes Username and your Elegant Themes API Key into the Updates Tab in your theme and plugin settings. To locate your API Key, <a href=\"https://www.elegantthemes.com/members-area/api-key.php\" target=\"_blank\">log in</a> to your Elegant Themes account and navigate to the <strong>Account > API Key</strong> page. <a href=\"http://www.elegantthemes.com/gallery/divi/documentation/update/\" target=\"_blank\">Learn more here</a></em>. If you still get this message, please make sure that your Username and API Key have been entered correctly",
			"overlay_zindex": "1999999998",
			"zindex": "1999999999",
			"responsive_min_width_unit": "px",
			"responsive_max_width_unit": "px",
			"custom_width_unit": "px",
			"custom_height_unit": "px"
		},
		"close": {
			"text": "",
			"button_delay": "0"
		},
		"click_open": {
			"extra_selectors": ""
		}
	}
}
```

The only place this string is located in the Divi theme is

`<em>Before you can receive product updates, you must first authenticate your Elegant Themes subscription. To do this, you need to enter both your Elegant Themes Username and your Elegant Themes API Key into the Updates Tab in your theme and plugin settings. To locate your API Key, <a href=\"https://www.elegantthemes.com/members-area/api-key.php\" target=\"_blank\">log in</a> to your Elegant Themes account and navigate to the <strong>Account > API Key</strong> page. <a href=\"http://www.elegantthemes.com/gallery/divi/documentation/update/\" target=\"_blank\">Learn more here</a></em>. If you still get this message, please make sure that your Username and API Key have been entered correctly`

Is only located in the `themes /core/admin/includes/class-updates.php:415`.

It is only called when there is an update but either no key is entered or the key is not valid.

Based on that I am not sure what to think. We have a new version going into testing shortly. I would like to see if it happens with new popups created after that version is released.

**Comment by danieliser** [comment]
To clarify the above data attribute was taken from a user with the issue, I still was not able to duplicate.

**Comment by Supaiku** [comment]
I have this issue.

Unclear what causes the corruption, but it's happened a few times now.

**Comment by Supaiku** [comment]
Weirdly this works:
data-popmake="{"id":5028,"slug":"sprung-floor-and-more-indiegogo-campaign-4","theme_id":2717,"cookies":[{"event":"on_popup_close","settings":{"name":"pum-5028","key":"","time":"1 month","path":1}}],"triggers":[{"type":"auto_open","settings":{"delay":"500","cookie":{"name":["pum-5028"]}}},{"type":"click_open","settings":{"extra_selectors":"","cookie":{"name":null}}}],"mobile_disabled":null,"tablet_disabled":null,"meta":{"display":{"size":"medium","responsive_min_width":"","responsive_max_width":"","custom_width":"640","custom_height":"380","animation_type":"fade","animation_speed":"350","animation_origin":"center top","location":"center top","position_bottom":"<em>Before you can receive product updates, you must first authenticate your Elegant Themes subscription. To do this, you need to enter both your Elegant Themes Username and your Elegant Themes API Key into the Updates Tab in your theme and plugin settings. To locate your API Key, <a href=\"https:\/\/www.elegantthemes.com\/members-area\/api-key.php\" target=\"_blank\">log in<\/a> to your Elegant Themes account and navigate to the <strong>Account > API Key<\/strong> page. <a href=\"http:\/\/www.elegantthemes.com\/gallery\/divi\/documentation\/update\/\" target=\"_blank\">Learn more here<\/a><\/em>. If you still get this message, please make sure that your Username and API Key have been entered correctly","position_top":"100","position_left":"<em>Before you can receive product updates, you must first authenticate your Elegant Themes subscription. To do this, you need to enter both your Elegant Themes Username and your Elegant Themes API Key into the Updates Tab in your theme and plugin settings. To locate your API Key, <a href=\"https:\/\/www.elegantthemes.com\/members-area\/api-key.php\" target=\"_blank\">log in<\/a> to your Elegant Themes account and navigate to the <strong>Account > API Key<\/strong> page. <a href=\"http:\/\/www.elegantthemes.com\/gallery\/divi\/documentation\/update\/\" target=\"_blank\">Learn more here<\/a><\/em>. If you still get this message, please make sure that your Username and API Key have been entered correctly","position_right":"<em>Before you can receive product updates, you must first authenticate your Elegant Themes subscription. To do this, you need to enter both your Elegant Themes Username and your Elegant Themes API Key into the Updates Tab in your theme and plugin settings. To locate your API Key, <a href=\"https:\/\/www.elegantthemes.com\/members-area\/api-key.php\" target=\"_blank\">log in<\/a> to your Elegant Themes account and navigate to the <strong>Account > API Key<\/strong> page. <a href=\"http:\/\/www.elegantthemes.com\/gallery\/divi\/documentation\/update\/\" target=\"_blank\">Learn more here<\/a><\/em>. If you still get this message, please make sure that your Username and API Key have been entered correctly","overlay_zindex":"1999999998","zindex":"1999999999","responsive_min_width_unit":"px","responsive_max_width_unit":"px","custom_width_unit":"px","custom_height_unit":"px"},"close":{"text":"","button_delay":"0"},"click_open":{"extra_selectors":""}}}"


But this is broken:
https://wordpress.org/support/topic/popup-maker-conflict-with-divi-theme-2/

as is this:
<div id="pum-5023" class="pum pum-overlay pum-theme-2717 popmake-overlay auto_open click_open" data-popmake="{"id":5023,"slug":"sprung-floor-and-more-indiegogo-campaign-3","theme_id":2717,"cookies":[{"event":"on_popup_close","settings":{"name":"pum-5023","key":"15d027848ea","time":"3 days","path":1}}],"triggers":[{"type":"auto_open","settings":{"delay":"500","cookie":{"name":["pum-5023"]}}},{"type":"click_open","settings":{"extra_selectors":"","cookie":{"name":null}}}],"mobile_disabled":null,"tablet_disabled":null,"meta":{"display":{"size":"medium","responsive_min_width":"","responsive_max_width":"","custom_width":"640","custom_height":"380","animation_type":"fade","animation_speed":"350","animation_origin":"center top","location":"center top","position_bottom":"100","position_top":"100","position_left":"100","position_right":"100","overlay_zindex":"1999999998","zindex":"1999999999","responsive_min_width_unit":"px","responsive_max_width_unit":"px","custom_width_unit":"px","custom_height_unit":"px"},"close":{"text":"Already got it covered!","button_delay":"6000","esc_press":"true","f4_press":"true"},"click_open":{"extra_selectors":""}}}" role="dialog" aria-hidden="true" aria-labelledby="pum_popup_title_5023">

**Comment by danieliser** [comment]
v1.7 Deprecates the data attribute usage in favor of global JS var. Once we remove it in v1.9 this issue shouldn't be a problem any longer.
