### ISSUE TITLE
Conflict with MailChimp Subscriber Popup embed.

### ISSUE THREAD

**Issue by mrjonwilson** [PopupMaker/Popup-Maker#37]
When using a MailChimp Subsciber Popup and a Popup Maker popup on the same page, the MailChimp Popup displays, but the Popup Maker popup does not. I tested this with the following embed code:

`<script type="text/javascript" src="//s3.amazonaws.com/downloads.mailchimp.com/js/signup-forms/popup/embed.js" data-dojo-config="usePlainJson: true, isDebug: false"></script><script type="text/javascript">require(["mojo/signup-forms/Loader"], function(L) { L.start({"baseUrl":"mc.us9.list-manage.com","uuid":"22a2745ac8439d70fec507b89","lid":"2f8d4a458a"}) })</script>`

I also put a Popup Maker button in the Primary widget area. Here is a screenshot: http://www.screencast.com/t/oTE7Ivdlj

**Comment by danieliser** [comment]
Moving the script from mailchimp to the footer before the closing body tag, but after all js has been loaded resolves the issue. Not a conflict with Popup Maker as the issue exists even when Popup Maker is disabled.

**Comment by rlam3** [comment]
@mrjonwilson i'm having a similar problem but with vue.js was wondering if you found a workaround for this. thanks!

**Comment by mrjonwilson** [comment]
@rlam3 I'm sorry, but I do not remember. I can hardly remember much from last month. :)
I no longer use Popup Maker. It is a great plugin, but I do not need it anymore.
