### ISSUE TITLE
Debugger

### ISSUE THREAD

**Issue by waltermesser** [PopupMaker/Popup-Maker#383]
If there are no popups loaded then the Popups menu on the admin bar goes away - i would like to see it stay, but in the drop down it says "No popups loaded" - then when they go to docs - i'll have a doc named "No popups loaded" cause thats what theyll search for

**Comment by danieliser** [comment]
How bout we just link straight to that doc with a ? link.

**Comment by waltermesser** [comment]
Yea that's even better

**Comment by waltermesser** [comment]
Put a link to this doc as it will have the relevant info [http://docs.wppopupmaker.com/article/265-my-popup-wont-work-how-can-i-fix-it](http://docs.wppopupmaker.com/article/265-my-popup-wont-work-how-can-i-fix-it)
