### ISSUE TITLE
Add "Presets" ability to Theme Builder Color Picker

### ISSUE THREAD

**Issue by waltermesser** [PopupMaker/Popup-Maker#384]

**Comment by danieliser** [comment]
Pretty sure this already exists in Advanced Theme Builder.

**Comment by danieliser** [comment]
Yep, just checked. Settings -> Extensions there is a section for Advanced Theme Builder to add custom preset color pallete. Probably needs to be documented.

**Comment by waltermesser** [comment]
Yeah didnt know that thanks
