### ISSUE TITLE
Update Support Pane

### ISSUE THREAD

**Issue by waltermesser** [PopupMaker/Popup-Maker#385]
- replace with better icons (provided)
- remove priority support
- see zip for mockup/icons
- [Support Pane.zip](https://github.com/PopupMaker/Popup-Maker/files/802137/Support.Pane.zip)

**Comment by danieliser** [comment]
Will get icons added, but the priority-support link is already gone. Likely your still using the version I manually uploaded. The official Beta1 should have had that change in already. My fault, shouldn't call the test version we use beta1, it should be alpha1 for being pre beta.

**Comment by waltermesser** [comment]
10 4
