### ISSUE TITLE
Is it possible to have the Theme Preview Pane in the Theme Editor be on the bottom by default so it will sticky and follow by default without having to move it first?

### ISSUE THREAD

**Issue by waltermesser** [PopupMaker/Popup-Maker#386]

**Comment by danieliser** [comment]
Not sure, will have to look into it.

**Comment by danieliser** [comment]
There isn't a reliable way to do this currently. All ways currenlty involve constantly overwriting the users preferences which is not a good idea as if they decide they want something different it won't let them.

**Comment by danieliser** [comment]
Set priority to low in v1.7. Also added a set of random tips including one that says move it to the bottom.
