### ISSUE TITLE
Further Accessibility Improvements

### ISSUE THREAD

**Issue by danieliser** [PopupMaker/Popup-Maker#391]
Our friends at 10 up have a few additional improvments on the modals for accessibility - https://10up.github.io/wp-component-library/component/modal/index.html

**Comment by fpcorso** [comment]
@danieliser The page you link to is about implementing the A11y Dialog library. Were you looking to replace the base of our popups with that library?

The only thing on the page itself that isn't part of the library is the `aria-label` on the close button.

**Comment by danieliser** [comment]
@fpcorso Guess we can ignore this one. There was more too it before, but the note about the <dialog> element etc wasn't there so it has changed.
