### ISSUE TITLE
Allow use of Font Awesome inside Close Button Text Field

### ISSUE THREAD

**Issue by waltermesser** [PopupMaker/Popup-Maker#394]
Potential Effectors:

- https://github.com/PopupMaker/Popup-Maker/blob/master/includes/functions/popups/template.php#L89
- https://github.com/PopupMaker/Popup-Maker/blob/master/classes/Model/Popup.php#L626-L635

**Comment by somethumb** [comment]
Any news on this? It would be helpful to have Font Awesome in that Close button

**Comment by fpcorso** [comment]
Possible fix: Detect font awesome shorthand (e.g. 'fast-forward') or font awesome class (e.g. 'fa-fast-forward') and have it automatically create/show the font awesome icon.

**Comment by danieliser** [comment]
@fpcorso my only concern with this one currently is what happens if their site isn't already loading font-awesome, or has a different version that doesn't contain the version they need?

**Comment by fpcorso** [comment]
I used a bit of regex to ensure the admins can use any style of Font Awesome, in case they were using something beyond just the free plan.

E.g. They can put the default `fas fa-camera` or the light `fal fa-camera`. If detected, will use a `<i>` element. If not detected, will use the regular esc_html code.

Example with using camera icon:
![image](https://user-images.githubusercontent.com/9730040/74552047-63cbbb80-4f22-11ea-8f28-01feb41e833b.png)

**Comment by fpcorso** [comment]
Ah @danieliser We must have been typing at the same time. We could not include it at all and recommend installing the Font Awesome plugin if it doesn't work. I wouldn't want to purposely include font-awesome in case there is a different version or something different already loaded on their site.

Not sure the right approach there.

**Comment by danieliser** [comment]
Agree on number 3

**Comment by fpcorso** [comment]
Created documentation in HelpScout which will be published upon 1.10 release. Merged pull request into develop. Closing issue.
