### ISSUE TITLE
1.5.8 not working at all

### ISSUE THREAD

**Issue by cometfish** [PopupMaker/Popup-Maker#402]
Hi, just upgraded to 1.5.8 via the wordpress auto-updater, which broke the whole site.

PHP log says "PHP Fatal error:  Class 'PUM_Extension_License' not found in {filepath}\wp-content\plugins\popup-maker\includes\license-handler.php on line 22

Reverted to 1.5.7 manually, error disappeared. Any thoughts?
(Running wordpress on IIS if that makes a difference.)

**Comment by danieliser** [comment]
@cometfish - There were no differences in those files between the versions, only in JS files which are client site, not server side. Sounds like it failed to fully install / unzip the newest version for some reason. I would try installing it using the upload method after first removing the current version.

**Comment by cometfish** [comment]
@danieliser Thanks for the quick response. Yes, it worked when I tried again.
I don't think I was on 1.5.7 in the first place (haven't updated in a while), so you're probably right that something messed up with the unzip.
All good now :)
