### ISSUE TITLE
Javascript conflict with Stylemix Motors Theme

### ISSUE THREAD

**Issue by jmac-digital** [PopupMaker/Popup-Maker#405]
In the WordPress dashboard for the Motors theme a javascript conflict occurs which prevents the theme from displaying custom fields for listing details. This is an integral part of the theme. The developers of the theme identified the conflict being this plugin.

Error log is included below, the issue is a conflict with one of the files loading through the WP core script loader.

This is a paid theme, so cannot supply a copy. Link to example theme: http://motors.stylemixthemes.com/

[domain.com-1495609234774.txt](https://github.com/PopupMaker/Popup-Maker/files/1024658/domain.com-1495609234774.txt)

**Comment by danieliser** [comment]
Took a look at the logs and nothing there indicates an issue with PM or that should be affected by PM. I only see errors with google maps api. In fact there are no JS fatal errors in that log that I can see.

Not sure how it was related to our plugin, maybe their devs could shed some light?

Till them closing this.
