### ISSUE TITLE
2 WP Menu Trigger issues

### ISSUE THREAD

**Issue by huntersbest** [PopupMaker/Popup-Maker#407]
In every menu I have multiple Dropdowns to Trigger Popups.
a) even non publicized Popups are in the dropdown(s)
b) only the last menu item has only one dropdown - the first item has as many dropdowns as menu items are available in this menu (see screenshots)

Problem is theme independent, disabling other plugins did not help

![menus-dopdown-popup-trigger-1-1](https://user-images.githubusercontent.com/25035806/26885552-393a375a-4ba3-11e7-967c-6f136979cb3b.jpg)
![menus-dopdown-popup-trigger-1](https://user-images.githubusercontent.com/25035806/26885551-39345bdc-4ba3-11e7-830c-53b7d8b71af3.jpg)

**Comment by danieliser** [comment]
This hasn't been duplicated in testing which most likely indicates a theme issue.
