### ISSUE TITLE
Error with WPML

### ISSUE THREAD

**Issue by fabienlege** [PopupMaker/Popup-Maker#409]
I've this error when I try to load the "Add popup" page on my wordpress : 

```mod_fcgid: stderr: PHP Fatal error:  Call to undefined method SitePress::get_new_post_source_id() in /var/www/vhosts/*********.com/httpdocs/mip/wp-content/plugins/popup-maker/includes/integrations/class-pum-wpml.php on line 52, referer: https://**********.com/wp-admin/plugins.php```

- Wordpress 4.8
- Popup maker V1.6.3
- WPML v3.1.5
- WPML CMS Nav v1.4.3
- WPML String Translation v2.0.5
- WPML Translation Management v1.9.4

All my plugins are up-to-date

**Comment by fabienlege** [comment]
UP !
Someone with same issue or with a solution ?

**Comment by danieliser** [comment]
@fabienlege - Have not had any other reports of this but haven't tested in a while. That said they haven't changed this particular code in a long time and I have a hard time thinking they did all of a sudden which means that for some reason WPML is not available in the admin on your site.

Will have to try to duplicate it.

**Comment by danieliser** [comment]
This should have been addressed in v1.6.5
