### ISSUE TITLE
Add a custom class for themes, using ids prevents reusing css for others themes

### ISSUE THREAD

**Issue by bluantinoo** [PopupMaker/Popup-Maker#413]
would be nice to have a field to give a custom name to theme class.
OR class could be the theme title.

Right now the class name is made with theme ID, but this prevent using the same css for other themes or other websites, forcing to restyle each time from the beginning.

thanks.

**Comment by adrianogiannacco** [comment]
+1

**Comment by danieliser** [comment]
@bluantinoo Great idea, if you want it sooner feel free to submit a pull request: https://github.com/PopupMaker/Popup-Maker/blob/master/includes/class-pum-popup.php#L169

**Comment by bluantinoo** [comment]
@danieliser here it is a pull request for you https://github.com/PopupMaker/Popup-Maker/pull/414 :)

**Comment by danieliser** [comment]
@bluantinoo Awesome, will get that pulled in for the next release. Much appreciated.
