### ISSUE TITLE
Fix iOS scrolling issues

### ISSUE THREAD

**Issue by danieliser** [PopupMaker/Popup-Maker#428]
The fix outlined in [here](https://wordpress.org/support/topic/problem-with-pop-up-on-iphone-6/) seems to have resolved it for several users.

    html.pum-open.pum-open-overlay, html.pum-open.pum-open-overlay.pum-open-fixed .pum-overlay {
        overflow: hidden;
        position: fixed;
        width: 100%;
    }
    html.pum-open.pum-open-overlay.pum-open-scrollable .pum-overlay.pum-active {
        overflow-y: scroll;
        -webkit-overflow-scrolling: touch;
    }

**Comment by ayophanz** [comment]
@danieliser, at first doesn't work, but when I removed the **position: fixed** works very well
Big thanks to someone who solve

**Comment by nicolaosmoubayed** [comment]
Still can't get it to work !!!!
The solution above is causing my page to scroll to the TOP, and applying the black overlay over the screen without showing the actually popup. Im assuming the actually popup is somewhere down on the page but i cant scroll there to see it.

Any other suggestions please ?

**Comment by nicolaosmoubayed** [comment]
Any recommendation please ? Thanks
