### ISSUE TITLE
Popups don't work at localhost

### ISSUE THREAD

**Issue by parfilov** [PopupMaker/Popup-Maker#436]
Hello! I've tested the plugin on my local server and at the hosting. The first is not working, the second is ok.
What I need to send to you to solve this problem?

Thanks!

**Comment by danieliser** [comment]
@parfilov Sounds like an issue on your localhost, possibly PHP or JS errors. The plugin has no functionality that would be limited by being offline or on a local install. In fact 100% of development on the plugin is done on local machines.
