### ISSUE TITLE
Sitewide cookie option will not stay unchecked.

### ISSUE THREAD

**Issue by danieliser** [PopupMaker/Popup-Maker#44]
https://wordpress.org/support/topic/sitewide-cookie-option-wont-stay-unchecked?replies=1#post-6721545

**Comment by rstalfoort** [comment]
does this also involve a link to a privacy page? The link is automatically created, but not wanted

**Comment by danieliser** [comment]
@rstalfoort - Not sure I understand what you mean. We don't add any links or privacy pages. This simply refers to an admin setting that when unchecked and saved comes back checked again.

**Comment by rstalfoort** [comment]
can you tell me when this will be solved?

**Comment by danieliser** [comment]
@rstalfoort - I am reworking several extensions at the moment, but we will be working on v1.3 beginning next week. This will likely be included in that unless a smaller point fix goes out before then. Once the issue is solved you can see and manually update the needed files from the commit log attached to this issue. Since you are subscribed you will be notified immediately when that happens.

**Comment by rstalfoort** [comment]
Hi Daniel, another question. The plugin automaticly creates a link to my privacy page. But i'm not able to change this, please advice.

**Comment by danieliser** [comment]
@rstalfoort - I'm not sure. This plugin has nothing to do with links to pages or privacy pages etc. It's definately not coming from PM. You can search the code yourself. Sounds more like your using a shortcode or something that is rendering that link.

**Comment by rstalfoort** [comment]
Even the title links to the privacy page. I've tried chrome and firefox en did some tests, but still links to the privacy page. Any idea?

**Comment by danieliser** [comment]
Can you upload screenshots? This is definately not from our plugin. Sounds like something is filtering the titles. I've never seen that. Do you have a link I can look at?

**Comment by rstalfoort** [comment]
the plugin links to the copyright link in the footer. How can i prevent the text in the popup from linking to this page?

**Comment by danieliser** [comment]
Fixed in v1.3-general
