### ISSUE TITLE
Moving when pop up is triggered

### ISSUE THREAD

**Issue by rajanam** [PopupMaker/Popup-Maker#446]
Any other css hacks to fix the "jumping" when pop up is active? 
been following the documentation ``http://docs.wppopupmaker.com/article/314-why-does-my-site-shift-jump-or-skip-when-a-popup-is-triggered`` but still no luck

**Comment by danieliser** [comment]
@rajanam Can you please move support requests to a valid support forum? If you were providing solutions or helping work through the issue then this would be the appropriate place.

In any case its generally fixed position elements that have issues. You can add CSS to set their padding-right: 0!important; and that should do it.
