### ISSUE TITLE
Popups can only be previewed on front end when 'status' == 'published'

### ISSUE THREAD

**Issue by rgadon107** [PopupMaker/Popup-Maker#453]
In version PUM v1.6.6, the popup permalink does not return a front-end preview. The workaround is to visit the front-end and use the PUM Toolbar (embedded in the WP Admin Toolbar). For example, 'Popup Maker' >> 'Popups' >> '{name-of-popup} >> 'Open Popup' only works when a popup is published. It will returns 'No Popups Loaded? if all popups are set to 'status: pending review' or 'status: draft'. 

At present, one workaround is to set a Click Open trigger on a popup with status == 'draft' or 'pending review'. Then the popup can be inspected on the front end using the PUM Toolbar. However, plugin users should not be expected to know that in advance, nor set up the plugin in that way just to inspect their popups on the front end. 

Plugin users need to be able to inspect their popups on the front end when popup status is set to either 'draft' or 'pending review'.

**Comment by danieliser** [comment]
v1.7 has better front end previews. Test them and let me know.
