### ISSUE TITLE
If no popups are published, the Popmake site-wide styles and theme styles are still enqueued on all pages.

### ISSUE THREAD

**Issue by benlk** [PopupMaker/Popup-Maker#464]

**Comment by danieliser** [comment]
This shouldn't happen in the newest version going into beta soon. That said there are still curcumstances when assets should be loaded even if popups are not such as using the [popup] shortcodes in your pages.

**Comment by benlk** [comment]
Wanting to keep the assets around for shortcodes makes sense. Does the beta version only enqueue popup assets if a popup is registered a page or if a listener on the shortcode handler notes that a shortcode is on the page?

**Comment by danieliser** [comment]
Correct. We run has_shortcode on the main content currently but calling it from inside the shortcode isn’t bad idea either.

**Comment by jonathanstegall** [comment]
Is this issue still pending? I've noticed that the style and script files load on all pages for me as well, running version 1.7.24.

**Comment by danieliser** [comment]
@jonathanstegall - Definitely resolved. If your still seeing issues you either have an older extensions that hasn't been updated to work with v1.7 yet, or some script that has our assets marked as a dependency.

**Comment by jonathanstegall** [comment]
@danieliser thanks. I think I did figure out my issues.
