### ISSUE TITLE
Popup preview in version 1.7 beta generates PHP warning 

### ISSUE THREAD

**Issue by rgadon107** [PopupMaker/Popup-Maker#466]
Popup preview button in Popup Admin works. However, on the front end, Xdebug program throws the following warning message and displays the entire PHP call stack in the overlay layer behind the popup container: 

Warning: Cannot assign an empty string to a string offset in: 

/app/public/wp-content/plugins/Popup-Maker-release-1.7/classes/Model/Popup.php on line 276.

**Comment by danieliser** [comment]
Think I got this nailed down. Can you retest in just a bit after I push a bunch of commits?
