### ISSUE TITLE
[PUM v1.7 beta] Ninja Form Success cookie option does not display when NF activated

### ISSUE THREAD

**Issue by rgadon107** [PopupMaker/Popup-Maker#468]
@danieliser In PUM v1.6.6, when the Ninja Forms plugin is activated, PUM provides a 'Ninja Forms Success' cookie option. In PUM v1.7 beta, that menu option _does not appear_ when NF is activated. In v1.7, cookie menu options include: 

On Popup Open
On Popup Close
Subscription Form: Successful
Subscription Form: Already Subscribed
Manual JavaScript

As integration with Contact Form 7 was maintained in v1.7 beta, I am going to assume _that integration with NF has yet to be completed_. I don't have a license for GravityForms, so I was unable to test the integration with that plugin on my test site.

**Comment by danieliser** [comment]
Just tested this now and the cookie is in the list for me. I haven't modified anything withing that lately.

**Comment by rgadon107** [comment]
I'll go back into my 1.7 test site and check again. Seems strange that it didn't turn up for me when I was running PUM & NF.

**Comment by danieliser** [comment]
@rgadon107 Can you retest? Still unable to duplicate. Closing for now.
