### ISSUE TITLE
Color picker conflicting with Wordpress's Core JS (Iris)

### ISSUE THREAD

**Issue by feverdog** [PopupMaker/Popup-Maker#471]
PopupMaker customized color picker is conflicting with Wordpress's Core javascript called "_Iris_" and breaking my page editor.

Console Output:
```
TypeError: (new Color(...)).setHSpace is not a function
iris.min.js:4:7897 
```

The problem is occurring in both production and development environments. I have disabled the plugin to confirm the issue.

Iris is a wordpress core javascript that is used to pick colors, it can be found in:

> "wp-admin/iris.min.js"

It seems that PopupMaker included color picker used in the theme editor is conflicting with it.
Iris Github: https://github.com/Automattic/Iris

![bug-modal](https://user-images.githubusercontent.com/5825385/35122135-e7a974f8-fc84-11e7-8bc5-7dfd7a58e14a.png)

**Wordpress versions tested**: 4.9.0, 4.9.1, 4.9.2

**Comment by danieliser** [comment]
Hmm, We don't include any libs and use the built in iris color picker ourselves in a completely  normal fashion: https://github.com/PopupMaker/Popup-Maker/blob/master/assets/js/src/admin/plugins/colorpickers.js#L8.

Furthermore we are using it correctly based on core guidelines: https://make.wordpress.org/core/2012/11/30/new-color-picker-in-wp-3-5/

The error & trace in your image also don't point anything towards PMs JS, but rather only your theme.

The only possibility is that they are using the same classes we are for designating their color fields. That said the errors don't indicate that is the issue at all. Instead it appears that they are not finding a function they are looking for. Could be any number of causes for that including that we requested that the wp color picker js (iris) is loaded before they register their extra code to render with it or something along those lines.

Happy to help debug further and add in some class changes to prevent namespacing issues in the future. But doesn't appear its directly related to PM, but rather PM being active simply triggers errors in your own theme that need to be investigated as well.

**Comment by feverdog** [comment]
Greetings Daniel, thank you the fast reply!

I'll look further for the issue, but what really got me is that disabling PM makes everything work just fine.. but what you've pointed makes perfect sense.

**Comment by danieliser** [comment]
Yea I completely understand why it appears that way. But it definitely happens where a small change in ordering of things breaks ones functionality.
