### ISSUE TITLE
Change Wording in 'Click Trigger' Dialogue Box on Class Names

### ISSUE THREAD

**Issue by rgadon107** [PopupMaker/Popup-Maker#475]
@danieliser Request originates from (Ticket #7151, 01/29/2018). When adding a new click open trigger, the plugin user observes the following in the 'Click Trigger Settings' dialogue box about CSS classes: 

"3) Language. This will be made more clear to you in the attached screenshot. Essentially when it comes to CSS, it is honestly confusing. Currently the wording found inside "Add New Trigger" popup window needs tweaking. Currently the wordsmith used is applying single and multiple class treatments in ONE description. It would be great if single class and multiple class treatment be parsed out and displayed independently which would offer the greatest amount of clarity.

Feedback: _Rewrite class examples, particularly inside the field location for only ONE class treatment only (see screenshot)_. This approach will greatly reduce any miscommunications. Then for multiple class treatments, offer a second example. Again, it is all explained in the screen shot." 

Note: I'll contact the plugin user to request that they resend us their comments, which are currently embedded in a screenshot. Then resubmit those comments as an addendum to this post. 

------------------------------------------------------------------------------------------

Notes: 

File: ‘/Popup-Maker-release-1.7/classes/Triggers.php’

Function ‘register_triggers’

Target: $triggers[‘click_open’][‘fields’][‘general’][‘extra_selectors’][‘desc’]

**Comment by danieliser** [comment]
@rgadon107 Want to do a PR for this one?

**Comment by danieliser** [comment]
@rgadon107 Got this one I think. Try out the nightly and see what you think.

**Comment by rgadon107** [comment]
@danieliser I think the changes you made are good; clarifying the description for the 'Extra CSS Selectors' custom field, and moving the 'prevent default functionality' to an 'Advanced' tab. 

I still think that plugin users needs better contextual information on the 'why'. _Why_ is the 'Extra CSS Selectors' custom field here in the first place, and when should it be applied? Pointing them to the 'doclink' on the article 'Getting CSS Selectors' is okay. But that article doesn't explain the 'why' and the 'what'. It focuses on the 'how'. 

If users haven't gone to the documentation yet (or avoid it altogether), they're going learn 'how' to use our the plugin Find CSS Selectors tool, without thinking through 'why' they might choose to do this in the first place. 

I don't think the 'Click Trigger' Settings' box (as it's currently setup) does an adequate job of putting the 'Extra CSS Selectors' custom field in context for our users.
