### ISSUE TITLE
Change Wording in the 'Click Trigger Settings' Box on the Default Click Functionality

### ISSUE THREAD

**Issue by rgadon107** [PopupMaker/Popup-Maker#476]
@danieliser This issue addresses the checkbox labeled 'Do not prevent the default click functionality'. It pertains to an input with name="trigger_settings[do_default]".  I find both the purpose and the label attached to the setting confusing. 

1) The statement 'Do not prevent the default click functionality' is a double negative. Another way of saying the same thing is '_Allow_ the default click functionality'. By default (unchecked), it implies that the plugin _prevents_ the 'default click functionality' (whatever that is). 

2) Why should users care about this? Why do we provide them the option to override the default (allow or prevent)? How many plugin users are affected by the absence or presence of this option setting?

3) If this setting is a lower priority than the linking of a 'Cookie Name' to a trigger, then relocate the setting _below_ the 'Cookie Name' input field. Give the setting less visual importance compared to the addition of a 'Cookie Name' linked to the trigger.

**Comment by rgadon107** [comment]
The plugin user recommends the following changes to the wording in the 'Click Trigger Settings -- General' option settings box: 

1) For placeholder text in the custom field labeled 'Extra CSS Selectors' replace '.my-class, #button2' with : '.class-here' (a single class). 

2) Outside the 'Extra CSS Selectors' custom field (and still inside the  'Click Trigger Settings -- General' option settings box), replace: 
'This allows custom css classes, ids or selector strings to trigger the popup when clicked. Separate multiple selectors using commas.' 

with 

'For more than one class, separate by comma (,). For example: .class-here, .class-here-2, #button_id

**Comment by rgadon107** [comment]
@danieliser See the following Gist for my recommended changes to ‘/Popup-Maker-release-1.7/classes/Triggers.php’, line 145. 

https://gist.github.com/rgadon107/c355ece17abdd01650d4346e5b5ce63d

**Comment by rgadon107** [comment]
@danieliser I need your help in properly formatting the URL for the 'Related article' link in the above Gist. The link is http://docs.wppopupmaker.com/article/144-trigger-click-open. When I test the link in my dev site, it redirects to a internal page not found on the dev site: 

http://pum17test.local/wp-admin/"http:/docs.wppopupmaker.com/article/144-trigger-click-open. 

The link needs to point to the external URL.

**Comment by rgadon107** [comment]
@danieliser I think a simpler solution to the 'Related article' link is to simply add a 'doclink' after the contextual description. The link should point to http://docs.wppopupmaker.com/article/144-trigger-click-open.

**Comment by danieliser** [comment]
That means that your adding the url after a / somehow.

That said I decided to go with a simpler click trigger extra selector description. Please move the longer one in your gist to the docs and insert a <a id="extra-selectors"></a> tag in that doc at the location of that info and the rest about that field. Then we can use #extra-selectors in the doclink url and take them straight to it.

**Comment by danieliser** [comment]
@rgadon107 See ^^
