### ISSUE TITLE
[version 1.7] Activation of PUM and MC Integration extension throws fatal error

### ISSUE THREAD

**Issue by rgadon107** [PopupMaker/Popup-Maker#477]
@danieliser When the following two plugins are activated on a test site: 

- Popup Maker (version 1.7), and 
- Popup Maker, MailChimp Integration (version 1.2.4)

and I select 'Popup Maker' >> 'All Popups' from within the Admin, the following error message is displayed: 

Fatal error: Uncaught Error: 

Call to undefined function pum_get_newsletter_admin_localized_vars() in 

/app/public/wp-content/plugins/pum-mailchimp-integration/classes/Admin.php on line 25

**Comment by danieliser** [comment]
Ok I need to work those out so they don't throw fatal errors, but the MC extension has an update that goes with this new version. I will send it to you tomorrow on slack. Its raw at the moment but adds full merge field support & ability to trigger custom automations in MC as well.

**Comment by danieliser** [comment]
Should be fixed with latest nightly.
