### ISSUE TITLE
[version 1.7] PUM & PUM--ATC extension throw fatal error on 'Active Plugins' Admin

### ISSUE THREAD

**Issue by rgadon107** [PopupMaker/Popup-Maker#478]
@danieliser I activated P UM v1.7 & Popup Analytics extension (v1.1.7), then deactivated Analytics. I then activated: 

- Popup Maker, version 1.7, and 
- Popup Maker--Advanced Targeting Conditions, version 1.3.0

When the link labeled 'Active' (http://pum17test.local/wp-admin/plugins.php?plugin_status=active) was selected, the following fatal error was rendered in the browser: 

Fatal error: Uncaught Error:

Call to undefined function popmake_get_label_singular() in 

/app/public/wp-content/plugins/popup-maker-popup-analytics/includes/class-legacy.php on line 46

Any attempt to either deactivate the ATC extension, or open the Admin links to 'Plugins' >> 'Installed Plugin'; 'Plugins' >> 'Add New'; or 'Plugins' >> 'Editor' returns the same error as above. 

The existing popup on the site cannot be edited. It throws the same error above.

**Comment by danieliser** [comment]
Added backward compatible functions and mared them deprecated in the latest nightly.
