### ISSUE TITLE
[version 1.7] Addition of new PUM trigger generates 'add_new' cookie

### ISSUE THREAD

**Issue by rgadon107** [PopupMaker/Popup-Maker#479]
Editing an existing trigger to set and link a cookie links the new trigger to a cookie with ID 'add_new'. The existing trigger is not updated. 

1) Create and save a new trigger without setting a cookie (e.g. Click Open trigger). 
2) Select the ‘edit’ trigger option. 
3) Open ‘Click Trigger Settings  — General’ option settings popup. 
4) In ‘Cookie Name’ custom field, select ‘Add New Cookie’. Select ‘Update’. 
5) ‘When should cookie be set?’ option settings box opens . Select menu option (e.g. On Popup Close). Select ‘Add’. 
6) Cookie Settings option settings box appears with cookie ID assigned in ‘Cookie Name’ custom field. Select ‘Add’. 
7) New cookie ‘On Popup Close’ is set with ID ‘pum-19’. Second ‘Click Open’ trigger is set linked to cookie with ID ‘add_new’. First ‘Click Open’ trigger is shown with no cookie set. 

Plugins activated: Popup Maker, v1.7
Theme activated: Twenty Sixteen

**Comment by rgadon107** [comment]
![add_new_cookie](https://user-images.githubusercontent.com/3718603/35599128-d8591b36-05ec-11e8-99c3-b0a3a3ea8d4e.png)

**Comment by danieliser** [comment]
Fixed in patch just now.
