### ISSUE TITLE
Missing Admin Toolbar On Some Sites

### ISSUE THREAD

**Issue by ruess** [PopupMaker/Popup-Maker#481]
Hey there,

I've posted this issue on the WordPress forum for the previous version (1.6.6 and lower) and was able to resolve it by changing the priority level of the following action hook from 1 to 3000
`add_action( 'wp_footer', 'popmake_render_popups', 1 );` 
(line 104 of load-popups.php in that version).

My only guess was that something was overriding this directive at a priority of 2999 because no priority under this worked to re-display the toolbar.

I've just migrated over to the new 1.7 beta and the code change mentioned above no longer works. Probably because the function 'popmake_render_popups' seems to have been removed by this version. Has this function just been renamed or is there a new way of going about this?

To me the core of the issue that's causing this has something to do with this plugin somehow overriding and maybe disabling the theme's inclusion of "wp_footer();" and subsequently only re-injecting this when a popup is displayed. I say this because whenever a popup is actually being displayed, the admin bar magically appears again!

Hope to get to the bottom of this, as it is affecting more than just me - it's a certain number of us who seem to be affected.

Thanks!

kevin

**Comment by danieliser** [comment]
@ruess - I think your missing something. If the admin bar isn't showing up its not neccessarily our plugin doing something. Could be any php error that occurs after the visual footer renders and before the admin bar is rendered. IE if your popups content contains something that triggers a PHP error the admin bar wouldn't load, but other popups might.

We do nothing with wp_footer other than render html, no buffering of the output etc. Other than a PHP error causing the admin bars html to never get rendered I am not seeing how this is related to Popup Maker other than moving our hook later fixes it. If that is in fact the case it definitely points to a PHP error either directly in PM (doubtful as I haven't seen any reports and we haven't updated anything recently to have broken it) or more likely a conflict with another plugin or your theme only when popups are active which to me suggests its in your popups content. Try deleting all of your popups and see if the issue remains, then untrash them one by one to see if it breaks again.

Like I said nothing in the core plugin would cause that directly, has to be something interfering which again is 99% of the time in the content of your popups, not the popups themselves.

PS moving that filter to 3000 will break a lot of underlying functionality including the admin bar tools, extension JS rendering and a few other things that are hooked in well before that, so its not an ideal fix. Best bet to track down the errors in your logs.

**Comment by ruess** [comment]
Thanks for the insight/feedback @danieliser  - I'll keep looking and report back.

**Comment by ruess** [comment]
Yup - you were right on track, it was the content of one of my popups that was causing it. Specifically the shortcode from a Gravity Forms form I was trying to embed. Thank you very much - this has truly mystified me and I wasn't getting anywhere on the WP forum.
