### ISSUE TITLE
[version 1.7]Rename Display -- General option setting to Display -- Style

### ISSUE THREAD

**Issue by rgadon107** [PopupMaker/Popup-Maker#486]
In the Popup Editor >> 'Popup Settings' >> 'Display' option tab, I recommend that the option setting of ‘General’ be changed to ‘Style’. The name of the option setting should convey more information about the _intent_ of that option. ‘Style’ is a term that conveys greater intent than 'General'. 
The word ‘Style’ is also understood in a broader sense of the field of web design and development (e.g. ’cascading style sheets’, ’stylesheet’). 

Also in the same option setting box (Popup Settings -- Display -- Style), I recommend changing the 'Theme' label to 'Popup Theme' to make the reference more specific in the user's mind. It also reinforces the 'Popup Themes' Admin submenu which will be visible to the plugin user at the same time.

**Comment by danieliser** [comment]
Done
