### ISSUE TITLE
[version 1.7]Reorder editor Popup Settings option tabs

### ISSUE THREAD

**Issue by rgadon107** [PopupMaker/Popup-Maker#487]
@danieliser As I'm not currently listed as a contributor to this repository, I'm going to have to post an 'issue' with my PR code provided as a GH Gist. 

I recommend reordering the 'Popup Settings' option tabs and renaming some of the section labels to improve user experience in setting up a popup. I was able to accomplish in my sandbox what I'm proposing here by reorganizing some code blocks around in my v1.7 plugin. 

[Link to Gist with recommended changes to code targeting:
'/Popup-Maker-release-1.7/classes/Admin/Popups.php'. ]
(url: https://gist.github.com/rgadon107/183c1b190684a42b264d599a94aa7aeb)

My file modifications reorder the 'Popup Settings' option tabs from: 

1) Display
2) Close
3) Triggers
4) Targeting 

TO: 

1) Targeting // Set 'Standard' or 'Advanced Targeting' Conditions
2) Triggers // Set trigger(s) and cookie(s)
3) Display // Style the popup
4) Close // Customize the popup close settings

Screenshots of reorganized UI added below.

**Comment by rgadon107** [comment]
![popup_settings_targeting_tab](https://user-images.githubusercontent.com/3718603/35907045-5ba6632a-0bb2-11e8-9345-575309907e15.png)
![popup_settings_triggers_tab](https://user-images.githubusercontent.com/3718603/35907044-5b83b924-0bb2-11e8-9cf6-4d3f8bed71da.png)
![popup_settings_display_tab_and_settings](https://user-images.githubusercontent.com/3718603/35907043-5b707db4-0bb2-11e8-94df-475f0bf29aca.png)
![popup_settings_close_tab_and settings](https://user-images.githubusercontent.com/3718603/35907041-5b538006-0bb2-11e8-8a7c-dd18eea3b799.png)

**Comment by danieliser** [comment]
I'm not sure putting targeting first is best idea. To be clear one of the big support issues used to be that people set up conditions incorrectly right away when they really wanted a popup on all pages (no conditions). So I'm feeling like we may be pushing them back that direction toward adding conditions as a step 1 everytime when they may not want them.
