### ISSUE TITLE
Missing WooCommerce conditions in Popup Settings/Targeting option settings tab

### ISSUE THREAD

**Issue by rgadon107** [PopupMaker/Popup-Maker#488]
@danieliser When WooCommerce (version 3.3.1) and Popup Maker (version 1.6.7/ branch: origin/release/1.7) are activated together, the WooCommerce conditions are missing in 'Popup Settings' >> 'Targeting' option settings box. 

See screenshot: 

![woocommerce_conditions_missing](https://user-images.githubusercontent.com/3718603/36064815-973dee84-0e56-11e8-9038-2337de5ddc3e.png)

**Comment by danieliser** [comment]
Resolved in nightly.

**Comment by rgadon107** [comment]
@danieliser Just reviewed nightly release in test site. WooCommerce conditions appear in targeting conditions. WooCommerce Conditions documentation article updated (http://docs.wppopupmaker.com/article/236-woocommerce-conditions).
