### ISSUE TITLE
Change $url on Popup Settings -- Targeting options tab

### ISSUE THREAD

**Issue by rgadon107** [PopupMaker/Popup-Maker#489]
Now that the 'Triggers' option settings documentation is published, I would like to change the 'doclink' reference, and the contextual description in the option settings box. I will submit these suggested changes as a PR, referencing this issue number.

**Comment by danieliser** [comment]
@rgadon107 - Go ahead and get a new branch up for this to submit a PR.

**Comment by rgadon107** [comment]
@danieliser Cllosing this issue out, as it's addressed in a PR on issue/499.
