### ISSUE TITLE
Possible to add 2 cookies with same ID to popup trigger

### ISSUE THREAD

**Issue by rgadon107** [PopupMaker/Popup-Maker#492]
@danieliser I'm working locally on the 'origin/release/1.7' branch of 'Popup-Maker'. 

When creating a new trigger (either 'Click Open' or 'Auto Open') and adding a cookie during trigger creation, it's possible to add a cookie twice to the same trigger.  Here are the steps I followed to generate this result. In this example, I create a new 'Auto Open' trigger. Result will be the same if creating a new 'Click Open' trigger. 

1) In Popup Settings, select 'Add New Trigger'. 
2) Select checkbox labeled 'Would you like to set up a cookie as well?'. 
3) On 'Time Delay Setting -- General' option settings tab, custom field labeled 'Cookie Name' automatically includes a cookie ID (e.g. 'pum-{integer}').  When the cursor is clicked inside the 'Custom Name' custom field, a second option appears; 'Add New Cookie'. Select the 'Add New Cookie' option, which adds that selection to the custom field. Select 'Add'. 
4) Plugin prompts 'When should your cookie be created?". Select cookie option default ('On Popup Close'), and select 'Add'.  Note: behind the overlay, in the Trigger option setting, 'Cookie' column, a second cookie named 'add_new' is added to the existing cookie 'pum-{integer}'. 
5) On the 'Cookie Settings --General' option settings tab, select 'Add'. 
6) Two cookies with the exact same ID (e.g. 'pum-{integer}) appear in the 'Trigger' option settings tab, 'Cookies' column. 

![add_new_cookie_option_during _trigger_creation_1](https://user-images.githubusercontent.com/3718603/36184975-7cf4506a-10fc-11e8-81e6-ef729398f844.png)
![add_new_cookie_option_during _trigger_creation_2](https://user-images.githubusercontent.com/3718603/36184980-81588964-10fc-11e8-8f25-739b0547dc1c.png)

**Comment by danieliser** [comment]
@rgadon107 Caught this one earlier before I read this ticket. It was patched along with the other cookie/trigger issue.

Test the nightly to confirm.
