### ISSUE TITLE
When adding a cookie to an existing trigger, selected cookie option gives different results

### ISSUE THREAD

**Issue by rgadon107** [PopupMaker/Popup-Maker#493]
@danieliser Working locally on branch 'origin/release/1.7'. 

While reviewing the behavior of the plugin in my test site in preparation for writing documentation, I observed that an existing trigger _with no linked cookie_ will add a cookie differently depending on whether one chooses the 'pum-{integer}' or 'Add New Cookie' option in the 'Cookie Name' custom field of either the 'Click Open Settings -- General'  or 'Time Delay Settings -- General' option settings. 

1) Select the 'pencil' icon to edit an existing trigger (no cookie exists in popup). 
2) In either 'Click Open Settings -- General'  or 'Time Delay Settings -- General' option settings, >> 'Cookie Name' custom field, click the cursor on the custom field. Two options appear: 'Add New Cookie' or 'pum-{integer}'. 
3) Select the 'Add New Cookie' option, then select 'Update'. 
4) Cookie creation popup appears that prompts: 'When should your cookie be created?' Default option is: "On Popup Close". Select 'Add'. 
5) 'Cookie Settings' -- General options settings tab appears. 'Cookie Name' custom field contains the cookie ID 'pum-{integer}'. Select 'Add'. 
6) New cookie with Event: 'On Popup Close', is added to popup. Cookie is linked by ID to trigger. 

Now, delete the cookie, and edit the trigger to remove cookie. Go through the trigger editing process again. At step 3 above, the cookie setting process turns out differently if one selects a cookie with 'Cookie Name' 'pum-{integer}' instead. 

3) In the 'Cookie Name' custom field, select 'pum-{integer}', then select 'Update'. 
4) A cookie with ID 'pum-{integer}' is added to the trigger. _No cookie creation popup appears before the cookie is added to the trigger._ Instead, a cookie ID is assigned and linked to the trigger. _But no cookie is set in the 'Cookie' option settings box_. 

Possible consequences for the plugin user: 
1) They may think that they set a cookie and linked it to their trigger, when in fact they have not. Then they're puzzled why the cookie (which they thought they set) is not controlling repeated display of the popup. 
2)  The plugin user (if they're paying attention) has to add a new cookie on the 'Trigger' option settings tab. 

My question to you: is this plugin behavior what you _intended_ and _expected_?

**Comment by danieliser** [comment]
@rgadon107 Not sure what your seeing. When I add a new popup with no cookies and click to add a new trigger only the "Add New" cookie option. The only time you would see pum-{ID} is if that cookie already existed in the list. The dropdown is updated to include all existing cookies + "add new" every time the form is shown, so it should always show only what is listed.

**Comment by danieliser** [comment]
@rgadon107 That said while trying to duplicate I did find that the "Add new" option in the cookie editor replaces the first cookie in the list below every time which is not correct, fixing that now.

**Comment by danieliser** [comment]
Retest the nightly and close this if you can't duplicate. Otherwise I will reread and try again.

**Comment by rgadon107** [comment]
@danieliser The problem is now resolved as of 02/14/18.
