### ISSUE TITLE
Popup Trigger Shortcode does not work properly when setting up in a post

### ISSUE THREAD

**Issue by rgadon107** [PopupMaker/Popup-Maker#503]
![1-select popup trigger sc option in post](https://user-images.githubusercontent.com/3718603/36503808-03604b96-1714-11e8-92ed-d5c293de09dd.png)
![2-popup trigger -- general option settings](https://user-images.githubusercontent.com/3718603/36503807-034cca44-1714-11e8-9734-4f0d98e056fe.png)
![3-popup trigger -- options option settings](https://user-images.githubusercontent.com/3718603/36503806-03373396-1714-11e8-8ef7-cc79ab50a46a.png)
![4-popup trigger shortcode atts on editor text tab](https://user-images.githubusercontent.com/3718603/36503804-031251ca-1714-11e8-9c77-102d2084f17e.png)
![5-popup trigger markup on editor visual tab](https://user-images.githubusercontent.com/3718603/36503805-0326c4d4-1714-11e8-9e6e-ee01c4e99bfb.png)
![6-raw html rendered in post on front end](https://user-images.githubusercontent.com/3718603/36503803-02ff5340-1714-11e8-8322-4dc34e97fa43.png)

**Comment by rgadon107** [comment]
Plugins and themes active on site: 

PI: Popup-Maker v1.7rc.1 (branch 'release/1.7', nightly build released 02-21-18)
Theme: TwentySixteen

**Comment by danieliser** [comment]
Try the latest nightly again.
