### ISSUE TITLE
Duplicate Option Settings on Popup Trigger and Popup Close Button shortcodes 

### ISSUE THREAD

**Issue by rgadon107** [PopupMaker/Popup-Maker#504]
When selecting either the 'Popup Trigger' or 'Popup Close Button' shortcode options from the editor menu, the 'options' tab setting displays a duplicate option setting. See checkbox below. 

![popup_close_shortcode_options_settings_tab](https://user-images.githubusercontent.com/3718603/36505559-846caa72-1719-11e8-9ab6-70ea70df6a27.png)
![popup_trigger_shortcode_options_settings_tab](https://user-images.githubusercontent.com/3718603/36505560-847e26e4-1719-11e8-8bba-5c39daacbe52.png)

**Comment by danieliser** [comment]
Fixed in the nightly.
