### ISSUE TITLE
PUM 'Subscription Form' SC form returns 'already subscribed' when adding first DB record

### ISSUE THREAD

**Issue by rgadon107** [PopupMaker/Popup-Maker#505]
When the 'wp_pum_subscribers' DB table has no records, the addition of the first DB record on form submit returns a message 'You are already a subscriber' in the popup container. This message should not render when the DB table contains no records. 

Test site settings:
===========================================================
Plugins active: Popup Maker v1.7rc.1 ('release/1.7' branch, nightly release 02-21-18)
Theme: TwentySixteen
Targeting: Condition: 'All Posts'
Popup ID: popmake-80 (slug: form-test-popup)
Trigger: Click Open
Cookies (2): 
- Subscription Form: Successful; 
- Subscription Form: Already Subscribed

![1-wp_pum_subscriber_db_table_empty](https://user-images.githubusercontent.com/3718603/36507717-3a0c3518-1720-11e8-9d9f-de631c9d71b5.png)
![2-completed subscription form in popup on front end](https://user-images.githubusercontent.com/3718603/36507716-39f7a36e-1720-11e8-98c4-8225243ec4c0.png)
![3-subscription form confirmation message](https://user-images.githubusercontent.com/3718603/36507715-39e35dfa-1720-11e8-8b5b-8b46ce616661.png)
![4-subsciption form db record](https://user-images.githubusercontent.com/3718603/36507714-39d15aec-1720-11e8-92e0-9f190b1aae9f.png)

**Comment by danieliser** [comment]
Try it now.
