### ISSUE TITLE
'Ninja Forms Success Cookie' option does not display

### ISSUE THREAD

**Issue by rgadon107** [PopupMaker/Popup-Maker#506]
When the Ninja Forms plugin is active with PUM (v1.7rc.1, branch 'release/1.7', build 02-21-2018 nightly), the 'Ninja Forms Success Cookie' option does not appear when attempting to set a cookie. 

![1-plugins settings admin](https://user-images.githubusercontent.com/3718603/36561231-bfc6afcc-17d8-11e8-9223-4e685a111c1c.png)
![2-cookie option settings](https://user-images.githubusercontent.com/3718603/36561230-bfb3eb6c-17d8-11e8-9de7-442ec4db2451.png)

**Comment by danieliser** [comment]
Your gonna need to debug a lot further and possibly xdebug to step through the NF integration file and see what isn't returning true. That is the only thing that could prevent it from adding that option.

One of these two specifically is the only possible cause: https://github.com/PopupMaker/Popup-Maker/blob/release/1.7/includes/integrations/class-pum-ninja-forms.php#L7-L11

That said it uses deprecated filters to add them, though they still work for me I will get those updated shortly as well. See if you can test that section of code though by whatever means you have.

**Comment by rgadon107** [comment]
@danieliser The debugging tool that I use is Kint (https://github.com/kint-php/kint). I'm not currently skilled at using Xdebug in PHPStorm. When I go to https://github.com/PopupMaker/Popup-Maker/blob/release/1.7/includes/integrations/class-pum-ninja-forms.php#L7-L11 and inspect the condition `( ! class_exists( 'Ninja_Forms' ) )`, it returns TRUE and the conditional returns early (thus bailing out of the rest of the file). I'm not sure why the conditional is returning TRUE. That's the most information I can provide at this point. Am running the 'release/1.7' branch on the 2-21-18 nightly.

**Comment by rgadon107** [comment]
@danieliser FWIW -- CF7 and GF 'submit success' are both showing up as cookie options when those PIs are active on my test site. NF is not.

**Comment by danieliser** [comment]
Either that code is running before plugins_loaded, or the Ninja_Forms class is not available for whatever reason. Will see what I can come up with.

**Comment by danieliser** [comment]
Took a look at NFs init:

`if( get_option( 'ninja_forms_load_deprecated', FALSE ) && ! ( isset( $_POST[ 'nf2to3' ] ) && ( defined( 'DOING_AJAX' ) && DOING_AJAX ) ) ){

    include 'deprecated/ninja-forms.php';

    register_activation_hook( __FILE__, 'ninja_forms_activation_deprecated' );

    function ninja_forms_activation_deprecated( $network_wide ){
        include_once 'deprecated/includes/activation.php';

        ninja_forms_activation( $network_wide );
    }

} else {

    include_once 'lib/NF_Upgrade.php';
    include_once 'lib/NF_AddonChecker.php';

    include_once plugin_dir_path( __FILE__ ) . 'includes/deprecated.php';

    /**
     * Class Ninja_Forms
     */
    final class Ninja_Forms
`

Only thing that makes since is if that wp_option key exists in your db and is set to 1 or true.

Try running delete_option( 'ninja_forms_load_deprecated' ); and see if that clears it up.

**Comment by danieliser** [comment]
If that is the case we need to get look at NF docs and write up a doc of our own telling them why its not appearing, pointing to NF docs on whether they can proceed to update or not and then offering the  delete_option solution.

Reasons they couldn't update is if they are using non v3 compatible NF addons.

**Comment by rgadon107** [comment]
@danieliser I deleted my version of the NF plugin, and installed and activated the latest version, 3.2.15. I dropped all the DB tables associated with my former version of NF. Then did a fresh install of NF on my PUM v1.7 test site. 

I inspected line 28  of the NF plugin '/ninja-forms/ninja-forms.php' using Kint. See results below: 

![inspecting ninja-forms_php plugin file line 28](https://user-images.githubusercontent.com/3718603/36703316-b5fe9e78-1b20-11e8-9f35-b76ff4639243.png)

That means that the 'else' code block should run, which launches the Ninja Forms class on line 50. 

When I run the 'release/1.7' branch and reinspect '/Popup-Maker/includes/integrations/class-pum-ninja-forms.php'L#7 - 9, the conditional returns TRUE. The Ninja Forms class DOES NOT exist, and I presume the rest of the code in that file does not run. 

When I comment out L#7-9 of the file referenced above, the NF cookie option appears in the POPUPM Cookie drop-down menu. 

IMO, the issue is in our plugin, not in NF.

**Comment by danieliser** [comment]
Test latest. I initialized NF integrations late to compensate for this issue.

**Comment by rgadon107** [comment]
@danieliser Just inspected on test site. We're good on my end.

**Comment by danieliser** [comment]
Perfect, working through all the issues on v1.7 now. Some getting punted to 1.7.1, others getting done really quick then pushing it out.

Will start pushing out the updates for extensions shortly after that.
