### ISSUE TITLE
Selected post or page won't save on 'Popup Settings -- Targeting' option settings tab

### ISSUE THREAD

**Issue by rgadon107** [PopupMaker/Popup-Maker#507]
@danieliser Unable to save selected post or page to database on popup 'Targeting' option settings tab. 

Active popup: PUM v1.7rc.1 [running branch 'remote/origin/release/1.7', updated to 2-27-18 nightly.]
Theme: TwentySixteen. 

Sending you a separate (brief; 17 sec) .mp4 file via Slack demonstrating what's happening on my site. 

Within the 'Posts' option menu  on the 'Targeting' tab, the only option _that does not save_ to the DB is 'Posts: Selected'. All other options are saved.

**Comment by danieliser** [comment]
Should be fixed now.

**Comment by rgadon107** [comment]
@danieliser Confirmed that issue is fixed on local test site.
