### ISSUE TITLE
Fix license nag issues in network sites.

### ISSUE THREAD

**Issue by danieliser** [PopupMaker/Popup-Maker#510]
Ensure only site owners are seeing messages. 
Make them dismissable at least for 30-60 days at a time.
Remove notices from sites on network installs. Only render the notice on sites with an activated license key.

**Comment by danieliser** [comment]
Seems fine as is at this point. Removing milestone until more info is uncovered.

**Comment by fpcorso** [comment]
@danieliser Can this issue be closed? You commented 2 years ago about it appearing fine. Have you had any other mentions about this issue from users?

**Comment by danieliser** [comment]
@fpcorso Not that I'm aware of. Closing it now.
