### ISSUE TITLE
Popup Shortcode Theme option settings show number rather than popup theme name

### ISSUE THREAD

**Issue by rgadon107** [PopupMaker/Popup-Maker#513]
In the [popup] shortcode option settings box -> 'Popup  -- Display' tab -> 'Popup Theme' option setting, the popup theme options display as numbers. The 'title' attribute in the `span` element wrapping the option setting is assigned and renders an integer value, rather than being assigned a string and rendering as the human-readable name of the popup theme. The images below show the Popup Theme option settings in PUM version 1.6.6 compared to version 1.7rc.1. 

![popup shortcode -- display popup theme options v1_6_6](https://user-images.githubusercontent.com/3718603/36865259-9efc8952-1d54-11e8-8e53-f099e9d90d26.png)
![popup shortcode -- display popup theme options v1_7rc1](https://user-images.githubusercontent.com/3718603/36865266-a350bad2-1d54-11e8-9ee2-1762dce53d7e.png)

**Comment by rgadon107** [comment]
@danieliser If the [popup] shortcode is going to be removed from the Shortcode Button on the 'posts' and 'pages' editor in version 1.7, then this issue can closed. There's no need to address.

**Comment by danieliser** [comment]
Fixed these and removed the shortcode from the buidlder as well just in case.
