### ISSUE TITLE
Popup Shortcode 'Size' option settings show name only; no size values in percent

### ISSUE THREAD

**Issue by rgadon107** [PopupMaker/Popup-Maker#514]
In version PUM version 1.6.6, the 'Size' option setting in the 'Popup -- Display' tab of the 'Popup' shortcode box shows both the name and percentage size of the popup. In PUM version 1.7rc.1, the percent size and name passed as option setting values. But the percent amount is left off the option setting shown to the plugin user. Do you want to revert to the display format used in version 1.6.6 for the 'Size' option setting? 

![popup shortcode -- display size options v1_6_6](https://user-images.githubusercontent.com/3718603/36865472-40b5aee0-1d55-11e8-8773-d6984dd76306.png)
![popup shortcode -- display size options v1_7rc1](https://user-images.githubusercontent.com/3718603/36865473-40cb027c-1d55-11e8-9553-242a335b67ab.png)

**Comment by rgadon107** [comment]
@danieliser If the [popup] shortcode is going to be removed from the Shortcode Button on the 'posts' and 'pages' editor, then this issue can closed. There's no need to address.

**Comment by danieliser** [comment]
All of these resolved.
