### ISSUE TITLE
Popup Shortcode 'Content' custom field will not accept or update inputs

### ISSUE THREAD

**Issue by rgadon107** [PopupMaker/Popup-Maker#516]
When creating or editing a [popup] shortcode in a post or page editor, the 'Popup -- General' -> 'Content' custom field does not save additions or edits to that field. The 'post_content' for that post/page ID does not update in the database. 

Activated plugins: PUM v1.7rc.1
Theme: TwentySixteen

![popup shortcode -- visual tab in post editor](https://user-images.githubusercontent.com/3718603/36868231-5d044414-1d5d-11e8-83a2-621096136ae8.png)

**Comment by rgadon107** [comment]
@danieliser I have a dummy post on my test site (ID=1; post_title="Hello Cheeseburger!'). I'm setting a [popup] shortcode in the content editor. I just want to see what attributes it returns and how the shortcode behaves. I'm doing this as I prepare to edit the `Shortcode: [popup]` documentation article. 

I'm also running a must-use plugin that loads a Composer package called 'Whoops!'. It has a pretty page handler for displaying call stacks in error messages. 

When I attempt to view my dummy post, Whoops! returns an error. On line 20 of 'Popup-Maker/includes/pum-template-functions.php', the function 'pum_popup_classes' returns an error as it refers to another function 'pum_popup', which was deprecated in PUM version 1.7.  The error message sent by Whoops! is "Call to a member function get_classes() on boolean'.

**Comment by danieliser** [comment]
This is likely resolved as well.
