### ISSUE TITLE
Remove the [popup] shortcode option from Shortcode Button on 'posts' and 'pages'

### ISSUE THREAD

**Issue by rgadon107** [PopupMaker/Popup-Maker#518]
This is a just a reminder and a followup from our Slack DM on 03-01-2018 as you complete your checklist to launch  PUM v1.7. You wrote: 

>No need, honestly delete or archive the [popup] doc. I will also hide it from the shortcode editor in >v1.7. [As of PUM version 2.0, the [popup] ]doesn't exist anymore. If they had it already set up 
>( [popup] shortcode ), it will still work. But no mention going forward getting new users using it.

I'm going to temporarily set the article 'Shortcode: [popup]' to 'unpublished' and remove references to [popup] in the 'Shortcode Button' article. If anyone needs to view the 'Shortcode: [popup]' button article after the 1.7 release, I can republish the article if necessary.

**Comment by danieliser** [comment]
Done.
