### ISSUE TITLE
Issues with UI in 'Subscription Form' Shortcode box -> 'Action' option tab 

### ISSUE THREAD

**Issue by rgadon107** [PopupMaker/Popup-Maker#519]
1) Does the ‘Delay' time slider refer to only the ‘Close’ Popup’ checkbox above, or does it effect the ‘Open Popup’ checkbox below? This is unclear because there's no contextual information provided to the user.  

2) The ‘Popup ID’ option can accept the same popup as the one in which the form originates. Per the design of the plugin, this will not work. Popups that reference back to themselves flash open and then close. The 'Popup ID' option setting should be changed to remove the same popup as a possible selection for users.

**Comment by danieliser** [comment]
1. Delay timer is for close only and does have context. Ie it only appears if you check the Close Popup box. 

That said if you check both, the open Popup command is not triggered until the current Popup is closed after the delay.

2. Will look into it.

**Comment by danieliser** [comment]
@rgadon107 #2 is resolved.
