### ISSUE TITLE
wrong input type under Click-Open Settings meta box

### ISSUE THREAD

**Issue by jrevillini** [PopupMaker/Popup-Maker#52]
In the meta box for Click-Open Settings when editing a popup, the code for the text input is 

    <input type="input" placeholder=".my-class, #button2" name="popup_click_open_extra_selectors" id="popup_click_open_extra_selectors" value="">

It should be

    <input type="text" placeholder=".my-class, #button2" name="popup_click_open_extra_selectors" id="popup_click_open_extra_selectors" value="">

**Comment by danieliser** [comment]
Did i not add this issue when you mentioned it before? You wanna submit a pull request for it?

**Comment by jrevillini** [comment]
I looked but didn't see it. I'll have to look up the pull request thing - some kind of way to pull a file and submit a fix I would guess? I've worked with git locally to familiarize myself when it came out. I've never collaborated with it.

**Comment by danieliser** [comment]
Ok quick outline of how you should do it then.

1. Fork the repo so you have your own copy.
2. Create a new branch with name issue/52
3. When committing add #52 to your commit message each time so the notes come here automatically.
3. Make your changes and push them to your fork.
4. Come to Github and create a pull request.
5. For the PR options choose your fork/branch and PopupMaker/master as the target.
6. Add a note for the PR with #52 so it will auto link here as well and then submit it.

Git takes some getting used to but pretty easy. Couple notes, for each issue you work on, always create a new branch from the master. For instance if you finish this issue then create a new branch issue/40 from this one, that branch when PR will also submit your other unrelated changes as well. So always switch to master and do a fetch, then create new branch for the next issue.

**Comment by danieliser** [comment]
Fixed in v1.3-general
