### ISSUE TITLE
Admin Page 'Pum-Tools' is currently blank

### ISSUE THREAD

**Issue by rgadon107** [PopupMaker/Popup-Maker#521]
From the Admin UI, the 'Tools' submenu (page="pum-tools") is currently blank.

**Comment by danieliser** [comment]
Not seeing this, can you check error logs and see if there is an error for you causing it to be empty?

**Comment by danieliser** [comment]
Debug best you can, if you don't find it by Monday punting this to 1.7.1.

**Comment by rgadon107** [comment]
@danieliser Running branch 'release/1.7' nightlies updated to 03-11-18 04:29 AM. The 'Tools' Admin page is now displaying. However, there is an error on line 283 of '/Popup-Maker/classes/Admin/Tools.php. First screenshot shows the call stack from the Xdebug; second shows the end of the call stack using Whoops! I run 'Whoops!' as a 'mu-plugin' on my site. Even when Whoops! is turned off, the Xdebug call stack displayed on Popup Maker -> Tools -> SysInfo (tab) (figure 1) still appears.

![pum tools admin sysinfo tab](https://user-images.githubusercontent.com/3718603/37259582-14d97780-2556-11e8-8b4b-70aedf3109a3.png)
![pum tools admin sysinfo tab --whoops](https://user-images.githubusercontent.com/3718603/37259583-14e9abc8-2556-11e8-935f-74d9542cbfb1.png)

**Comment by danieliser** [comment]
@rgadon107 Got that one patched just now, good catch.
