### ISSUE TITLE
'Subscription Form' SC does not open selected popup with 'Open Popup' cb checked

### ISSUE THREAD

**Issue by rgadon107** [PopupMaker/Popup-Maker#522]
In the 'Subscription Form' shortcode option settings box, 'Actions' -> 'Popup'  submenu, the 'Open Popup' checkbox does not return the selected popup. For example, the subscription form is built into popup with ID-80. The target popup to open on form submit is popup 'ID-40'. On form submit, the existing popup (ID-80) displays a form submit success message. But the form fields clear, and the second popup does not appear.

**Comment by rgadon107** [comment]
A related issue in the 'Popup' submenu box is that when either checkbox='checked' for 'Close Popup' or 'Open Popup', their checked state does not persist in the option settings box upon 'Save' and popup 'Update'.  The checkbox selection is visible as a SC attribute on the editor 'Text' tab, but does not persist in the Subscription Form option settings UI.

**Comment by danieliser** [comment]
Just worked this one out. Now should work correctly on both accounts. I believe the first issue you reported was actually due  to the second issue of it not saving/rendering checkboxes properly.
