### ISSUE TITLE
DIVI conflit with Version 1.7.5 and 1.7.6

### ISSUE THREAD

**Issue by sebWP** [PopupMaker/Popup-Maker#525]
Hi, 
First of all, thank you for your work.

I updated popup maker (version 1.7.5 and 1.7.6). I have DIVI theme on my Wordpress site and these latest versions generates a conflict with DIVI. 

Here is the message that appears when loading pages and posts:
Oops, it looks like the Divi Builder failed to load. Performing the following actions may help solve the problem.
1. You are using third party plugins. Try disabling each plugin to see if one is causing a conflict.

By disabling popup maker the worry disappears...
Any ideas to solve this problem?

Thanks

**Comment by sebWP** [comment]
Hi, 

I discovered that the latest versions of popup marker can work with DIVI! The problem of loading the DIVI builder happens when TinyMCE Advanced plugin is also enabled on the site. If I disable one of the two then everything works fine. If both plugins are enabled, it is impossible to load the DIVI builder in the back office.

**Comment by danieliser** [comment]
This should be fixed in v1.7.9, and if your server has caching issues then 1.7.12 will fix that.
