### ISSUE TITLE
Remove 'openpopup' and 'openpopup_id' SC attributes if 'openpopup_id'="0"

### ISSUE THREAD

**Issue by rgadon107** [PopupMaker/Popup-Maker#528]
In the 'Subscription Form' shortcode box, 'Actions' option tab, 'Popup ID' option setting, if a user accidentally selects and saves the option 'Select a Popup', the attributes 'openpopup' and 'openpopup_id'="0" are saved in the editor (Text tab).

I don't know if the plugin processes 'openpopup_id'="0" as a NULL value and simply ignores it. If it does, then I suppose the attributes 'openpopup' and 'openpopup_id' can continue to display in the editor. 

However, if you don't want the attribute value of 'openpopup_id'="0" to display, then both 'openpopup' and 'openpopup_id'="0" should not display in the editor if 'Select a Popup' is the selected and saved option setting. 

![sub_form_shortcode_actions_option_tab_popup_id](https://user-images.githubusercontent.com/3718603/37427722-3a83223a-2798-11e8-828b-db0d298b7dbc.png)
![sub form in content editor -- text tab](https://user-images.githubusercontent.com/3718603/37427721-3a6eea18-2798-11e8-8d15-cc17e09f336d.png)

**Comment by danieliser** [comment]
Its fine, it ignores it.
