### ISSUE TITLE
How can I remove wpautop filter?

### ISSUE THREAD

**Issue by elisa-studioand** [PopupMaker/Popup-Maker#53]
Hi, I'd need to remove this filter (```popup-functions.php```, line 203)
```php
add_filter( 'the_popup_content', 'wpautop', 10 );
```
from certain popups.

I tried with this plugin https://wordpress.org/plugins/toggle-wpautop/ with no success.

So i tried to remove it in my ```functions.php``` file with
```php
remove_filter( 'the_popup_content', 'wpautop', 100 );
```
but neither this is working...

The only thing working is this
```php
remove_all_filters( 'the_popup_content', 100 );
```
but it removes all the other filters I guess.

How can I remove it without modifying the plugin files?

**Comment by danieliser** [comment]
Hey Elisa,

When using remove_filter it must match exactly the add_filter. So change 100 to 10.


remove_filter( 'the_popup_content', 'wpautop', 10 );Also if you want to do it only for certain ones that can also be done via a custom function that will A) detect the correct popup &amp; B) call remove filter if it is correct.Thanks,Daniel Iser---- On Fri, 03 Apr 2015 12:16:30 -0400 elisa-studioand&lt;notifications@github.com&gt; wrote ---- 

Hi, I'd need to remove this filter (popup-functions.php, line 203)
 add_filter( 'the_popup_content', 'wpautop', 10 );
 from certain popups.
 I tried with this plugin https://wordpress.org/plugins/toggle-wpautop/ with no success.
 So i tried to remove it in my functions.php file with
 remove_filter( 'the_popup_content', 'wpautop', 100 );
 but neither this is working...
 The only thing working is this
 remove_all_filters( 'the_popup_content', 100 );
 but it removes all the other filters I guess.
 How can I remove it without modifying the plugin files?

**Comment by elisa-studioand** [comment]
It works, thank you!
I think I should learn more about worpress priority... ;-)
