### ISSUE TITLE
Add dropdown in All Popups table to generate various types of click triggers for each popup.

### ISSUE THREAD

**Issue by danieliser** [PopupMaker/Popup-Maker#536]
- [ ] Shortcode trigger output
- [ ] Manual JS
- [ ] onclick=""
- [ ] class

**Comment by fpcorso** [comment]
@danieliser Can you elaborate a little more on this? Were you wanting to add a mechanism to create new triggers from the All Popups page for each popup?

**Comment by danieliser** [comment]
@fpcorso Pretty much, similar to how when you add a manual cookie it now shows the shortcode you can use to set it, but on the all popups screen you could do something like:

- Copy CSS Class `popmake-123`
- Copy Popup Trigger Shortcode `[popup_trigger id="123"]Open Popup 123[/popup_trigger]`
- Copy Popup ID `123`
- Copy JS Code `PUM.open(123);`

Those are the main ones, but there are others that could be done like Manual JS using jQuery.popmake etc.

**Comment by fpcorso** [comment]
@danieliser I'm not sure if we need that. The All Popups page can be a bit cluttered, especially after one adds in Popup Analytics. Additionally, the main times that people are adding triggers/retrieving the shortcode is when they are editing the popup. 

I don't know if adding this would be beneficial to the overall user experience.

**Comment by danieliser** [comment]
That is why I hired you 😜. If you don't see it, it may not be super useful. It is not related to any user request either, just an idea that floated by so I jotted it down.
