### ISSUE TITLE
Position > Fixed Position checkbox has no effect on popup position

### ISSUE THREAD

**Issue by jrevillini** [PopupMaker/Popup-Maker#54]
SUMMARY
The "Fixed Postioning" checkboc seems to have no effect on the position of the popup.

CLIENT
Browser: Chrome v 41.0.2272.104 (64-bit)
Platform: OSX Mavericks

REPRODUCE:
1. Edit a popup.
2. Under the Position meta box, select TOP RIGHT, then check the Fixed Position check box and set the TOP input to 100px and the RIGHT input to 400px. Set the Targeting Options to Entire Site for simplicity in testing.
3. Save the popup
4. Open the website. Note position of popup.
5. Edit same popup. Uncheck the FIXED POSITION checkbox.
6. Save the popup.
7. Open the website. Note that fixed position of popup is still considered.

EXPECTATION
Having the Fixed Position checkbox unchecked would do something different e.g. be relative based on a percentage or simply anchor to top:0, right:0.

**Comment by danieliser** [comment]
Fixed position means when you scroll the site the popup stays fixed to 100px top 400px right from the edge of the screen.

Non fixed will scroll off screen when you scroll down. This is simple CSS Fixed positioning option. The initial position is determined based on current screen position so it may appear in the same place but the scroll action is what that setting is for.
