### ISSUE TITLE
Add option to disable or adjust the padding-right added to body

### ISSUE THREAD

**Issue by danieliser** [PopupMaker/Popup-Maker#541]
This will make it easier for users to adjust those settings to match their theme.

**Comment by danieliser** [comment]
@fpcorso Any thoughts? It is related to this issue here: https://docs.wppopupmaker.com/article/314-why-does-my-site-shift-jump-or-skip-when-a-popup-is-triggered

We can easily work it into v1.9, but its low volume and could be punted as an easy issue to fill in another release.

Your call.

**Comment by fpcorso** [comment]
Not sure I quite understand what this issue will do. Is it only a checkbox to add the `padding-right: inherit;` or 0 from one of the solutions that you linked to? Is this issue only to help resolve that particular "shift" issue or is there a wider scope for this?

Would this implement a new setting then or is this an additional field in each theme?

**Comment by danieliser** [comment]
@fpcorso This would be an option to disable that padding entirely, or to set a custom value. It allows users to correct that long standing bug on a per site basis without us having to write them custom CSS.

**Comment by fpcorso** [comment]
@danieliser So, would this be per theme, per popup, or in the general PM settings?

**Comment by danieliser** [comment]
@fpcorso This would be in general PM settings per site (per theme). Allows compensation for the current theme only, switch themes and they may need to adjust again. But they will know when they view popups it needs adjusting if its wonky.

**Comment by fpcorso** [comment]
@danieliser We should probably punt this one to 1.10 to give us time to map it out and test it since we want to get the beta for 1.9 ready.
