### ISSUE TITLE
Restrict 'tag' attribute for 'popup_close' shortcode to valid HTML values

### ISSUE THREAD

**Issue by rgadon107** [PopupMaker/Popup-Maker#551]
@danieliser While updating the documentation for 'Shortcode: Popup Close' (https://docs.wppopupmaker.com/article/159-shortcode-popup-close), I deliberately added an erroneous value to the 'HTML Tag' custom field (see 'Popup Close Button' box -> 'General' tab -> 'HTML Tag' input ) in my test site. I wanted to see whether the custom field would accept a value that I knew to be deliberately wrong. **It did.** 

While not necessary to change, I'm going to recommend that you prevent users from adding an invalid value. I haven't dug into this issue enough to know whether there's a WP API function that could be run  to screen the input. But at the very least, run a check on the custom field input for accepted values. If none of those values are added, then bail out and do not allow the user to either save or update the inptut value(s). 

Accepted values should include: 'a', 'button', 'div', 'img', 'li', 'p', and 'span'.

**Comment by fpcorso** [comment]
@danieliser What are your current thoughts on this one? It would be tough to anticipate all the elements that someone might use this on.

Also, with [Web Components](https://www.webcomponents.org/introduction) now being supported in most browsers, many people are now utilizing [custom elements](https://html.spec.whatwg.org/multipage/custom-elements.html) which might be an issue if we limit this field down.

**Comment by danieliser** [comment]
@fpcorso - I'm of the impression none of our users are using any of those in this context. If they are going that far they can easily just do it manually with a `class=""`.

So maybe just the basics of span, button, div, p, a. If an anchor tag we could look at adding an href option so they can set a valid link as well.

**Comment by fpcorso** [comment]
@danieliser Would it be sufficient to just have a small check when something is entered into the "Popup Close Button" modal and showing an error message below the "HTML Tag" field if it isn't one of our allowed values?

Or, should this be something bigger that checks all the shortcodes, even ones manually entered, and have ways to alert of the issue?

**Comment by danieliser** [comment]
I wonder if just changing the field type to select and putting valid options in would do the trick. As long as they had a valid element we already supported it would just work.

**Comment by fpcorso** [comment]
@danieliser I like the idea of switching to a select there. I'll test that out tomorrow.

**Comment by fpcorso** [comment]
Oh @danieliser, since 1.11 is also fixing the bug from #593 which prevented the tag setting from working anyways which is two years old, changing this probably won't affect anyone. 

If no one could use that field for two years, it's even less likely someone used one of the other elements anyways.

**Comment by fpcorso** [comment]
@danieliser Switched to `select` element. Much better experience too. 

![example-popup-close-tag](https://user-images.githubusercontent.com/9730040/83895581-e4583700-a720-11ea-8327-2702a483d929.png)

**Comment by danieliser** [comment]
Did you also add an href field when they select `a`? That would be a huge upgrade as well.

**Comment by fpcorso** [comment]
@danieliser No, I hadn't. I had replaced the text field with the select field to ensure only valid tags were entered. Do you want me to go ahead and add a new href field, add that to the shortcode atts, and add that value to the final output?

**Comment by danieliser** [comment]
@fpcorso I kinda think it makes since. Consider if you set it as an <a> tag, but because its a shortcode with finite parameters, none of which currently include href, you have no way to actually make it a valid link.

The use case here is those with remote content popups, or links that open in a new tab and popup that opens on current. Then again to do that we would also need a `target` option for `_blank` and `self` field when they choose a `a`.

**Comment by danieliser** [comment]
@fpcorso If you think it makes since. Heck if the changeset is simple enough, I'd do the same for the normal popup trigger since it has the same "tag" option, at least I think it does, but we can create a new issue for that and punt it as an easy copy paste win for the next version too.

**Comment by danieliser** [comment]
Ahh, yea, I've had the reverse, people who set up the do default action, but then use the [popup_close] trigger and set the tag to 'a'. When they did that, the link didn't do anything.

This is more apparent on the [popup_trigger] shortcode where they might want to prevent access to a link until they complete an action via the Click Blocking trigger.

On the [popup_close] shortcode your 100% correct, it would never do anything without both, so I can see the confusion. On the [popup_trigger] shortcode though it makes way more since I guess.
