### ISSUE TITLE
The 'Beta Versions' options tab refers to checkboxes when there are none.

### ISSUE THREAD

**Issue by rgadon107** [PopupMaker/Popup-Maker#567]
From the WP admin, 'Tools' -> 'Beta Versions (tab)', there is a reference to 'Checking any of the below checkboxes'. However, there are no checkboxes shown. Is there something missing from this page? Or should the statement be changed to eliminate reference to checkboxes? 

Does the reference to 'pre-release update notification' refer only to Popup Maker, or to all PUM extensions too? 

![popup_maker_tools_beta_versions_tab](https://user-images.githubusercontent.com/3718603/40862958-cf3e29ac-65b3-11e8-838d-bd28612dec6d.png)

**Comment by danieliser** [comment]
Only when an extension is enabled.

**Comment by rgadon107** [comment]
@danieliser I activated Advanced Targeting Conditions just to see what would happen on the 'Beta Versions' tab and ATC appeared with a checkbox. Does this tab only apply then to pre-release notices of updates to PM extensions?

**Comment by danieliser** [comment]
No it just opts you to see notifications for betas is available. Rather than updating to the current it updates to a beta we can release from our site.only for extensions though.
