### ISSUE TITLE
Blinking Overlay

### ISSUE THREAD

**Issue by carlosnpz** [PopupMaker/Popup-Maker#574]
Hey guys!
I use Popup Maker and it's a great plugin, but when I open a popup on my site (Enterprise Blue theme), overlay blinks twice before opening box.

Any help?

**Comment by rgadon107** [comment]
@carlosnpz Hi Carlos, It would be best for you to submit a support request to https://wppopupmaker.com/support/. Scroll down and select the button labeled 'Support Request'. The forum is answered by the plugin developer. Please be sure to include: 

- the URL of the site on which the issue occurs;
- then name (and if possible, the ID) of the popup that is generating the problem. 

That will allow us to inspect your site, and check the popup settings. 

This issue tracker is really intended for itemizing issues that have occurred across a range of sites that developer needs to address, or posting new features that the developer plans to build.
