### ISSUE TITLE
Allow viewing PUM_Logging log file contents via Popup Maker -> Tools

### ISSUE THREAD

**Issue by danieliser** [PopupMaker/Popup-Maker#575]
We quietly added PUM_Logging for errors and warnings to v1.7. Now we need to add a way to view those logs.

**Comment by fpcorso** [comment]
@danieliser What are your thoughts on this? Adding this would make it easier to ask for them in support as opposed to asking them to go to /wp-content/xxxx.log

**Comment by danieliser** [comment]
@fpcorso 

1. Probably a downloadable similar to the system info txt file.

2. If we are showing it in the admin directly then yea, we could only load a finite amount of data and possibly even deduplicate those messages to only show unique issues.

**Comment by danieliser** [comment]
That said I wonder if we could start leveraging the API server and making it so they can do something like this:

1. Click a button such as "Get Help & Support"
2. This loads a form that they fill out like normal.
3. Request permission to submit system info & logs for support needs.
4. If allowed send the logs & system info to the API server along with an identifier.
5. Pass the identifier to Help Scout custom widget to view those logs in popup windows.

**Comment by fpcorso** [comment]
@danieliser To keep this issue clear, let's discuss your second comment in a different thread/issue. But, yes, I think there is something to having a support request from within the plugin.

For this issue, I think making it an option as a downloadable file is a good idea. Where should this go? Can we add a new "Error Log" tab to the "Tools" page? So it would be "Beta Versions" "System Info" "Error Log" and "Import / Export" as tabs on that page?

Then, on that tab, maybe we show the X recent (de-duplicated, if possible) with a download error log button underneath, similar to the "System Info" page:
![image](https://user-images.githubusercontent.com/9730040/87697175-c50cea80-c75f-11ea-82b4-15823db1b29a.png)

**Comment by danieliser** [comment]
@fpcorso sounds good

**Comment by fpcorso** [comment]
@danieliser This is where I am currently at. Since this is currently the only place within the admin to control the log, should we also have a button to empty the log?

![image](https://user-images.githubusercontent.com/9730040/88948605-22289600-d260-11ea-8336-a77b6af765d5.png)

**Comment by danieliser** [comment]
@fpcorso Button to empty it would be simple enough and a good addition.

Looks good.
