### ISSUE TITLE
PUM_Logging should keep eye on filesize and auto clean.

### ISSUE THREAD

**Issue by danieliser** [PopupMaker/Popup-Maker#577]
Appears it can cause slow downs to site when logging file gets large.

**Comment by fpcorso** [comment]
@danieliser Have you noticed a breakpoint where the file becomes too large that it affects speed? Is there any size you noticed that we should have as the maximum?

**Comment by danieliser** [comment]
@fpcorso We can close this, it already auto crops to 1M max.  https://github.com/PopupMaker/Popup-Maker/blob/master/classes/Utils/Logging.php#L69
