### ISSUE TITLE
PHP Warning:  ssh2_sftp_mkdir() expects parameter 1 to be resource, null given

### ISSUE THREAD

**Issue by ahmed-sigmalux** [PopupMaker/Popup-Maker#580]
I'm seeing the following warning after installing PopupMaker:

`PHP Warning:  ssh2_sftp_mkdir() expects parameter 1 to be resource, null given in /var/www/mysite/wordpress/wp-admin/includes/class-wp-filesystem-ssh2.php on line 519
`

According to Query Monitor, the caller is:

```
get_header() resources/themes/storefront/template-homepage.php:15
locate_template() wp-includes/general-template.php:41
load_template('resources/themes/mytheme/header.php') wp-includes/template.php:647
wp_head() resources/themes/mytheme/header.php:18
do_action('wp_head') wp-includes/general-template.php:2614
wp_enqueue_scripts() wp-includes/class-wp-hook.php:286
do_action('wp_enqueue_scripts') wp-includes/script-loader.php:1447
PUM_Site_Assets::register_styles() wp-includes/class-wp-hook.php:286
PUM_AssetCache::enabled() extensions/popup-maker/classes/Site/Assets.php:317
PUM_AssetCache::writeable() extensions/popup-maker/classes/AssetCache.php:80
WP_Filesystem_SSH2->mkdir() extensions/popup-maker/classes/AssetCache.php:106
ssh2_sftp_mkdir() wp-admin/includes/class-wp-filesystem-ssh2.php:519
```

**Comment by danieliser** [comment]
@ahmed-sigmalux You are likely gonna find this is related to hosting or security. We se WP_Filesystem to write files to the server and it appears that WP_Filesystem is what is throwing an error.

Will keep an eye on it but we are passing the correct parameters there, not sure what we can do differently in our code currently.

You can disable asset caching via PM settings, which may prevent that code from running.

**Comment by fpcorso** [comment]
This issue will be resolved once we implement changes for accounting for errors from the filesystem in #730. Closing this one.
