### ISSUE TITLE
Show Popup ID on the editor page in bold near the top.

### ISSUE THREAD

**Issue by danieliser** [PopupMaker/Popup-Maker#583]

**Comment by fpcorso** [comment]
@danieliser Looking for the right place to add this. Originally, I was thinking we could add a slightly gray `- #XXXX` next to the heading. Such as `Edit Popup - #1111`.
![image](https://user-images.githubusercontent.com/9730040/87699886-89741f80-c763-11ea-91f1-e3d5409f65f2.png)

But, that title is apparently brought directly from the CPT's `edit-item` key without any filters so it isn't easy to add something there that dynamically changes:

`$title = $post_type_object->labels->edit_item;`
to
```
<h1 class="wp-heading-inline">
<?php
echo esc_html( $title );
?>
</h1>
```

However, there is an `edit_form_top` hook right after the heading which can be added to like this:
![image](https://user-images.githubusercontent.com/9730040/87700346-30f15200-c764-11ea-93f6-700c553c1852.png)

Thoughts on location? Also, we just need to output the ID, right? Or, should we add additional explanation text?

**Comment by danieliser** [comment]
I like the latter one, is there one above the Edit Popup title, and if so does break the floats of the buttons?

**Comment by fpcorso** [comment]
@danieliser There isn't a good action for above the heading. That said, I think it is more consistent with how core outputs attributes by being underneath.

I went ahead and added it underneath and decreased the font size a little so it isn't quite as big as the main heading.
