### ISSUE TITLE
Show default click trigger classes in the popup editor or click trigger.

### ISSUE THREAD

**Issue by danieliser** [PopupMaker/Popup-Maker#584]

**Comment by fpcorso** [comment]
@danieliser We added this explainer in 1.11 to the click trigger settings:
![image](https://user-images.githubusercontent.com/9730040/87184220-98ffee00-c2b5-11ea-9fcb-627e33652a0e.png)

Is that what this issue is referring to or was there something more you wanted to do here?

**Comment by danieliser** [comment]
@fpcorso - Yea that should suffice.

That said now that I've reread that description, I wonder why you chose name over ID. Name's change over time breaking the link.

**Comment by fpcorso** [comment]
@danieliser Yeah, I had copied in the text that was originally near the name field which appears to not have had the ID class with it. Definitely makes sense to use that here. We'll try to switch that out in the next update before closing this then.

**Comment by fpcorso** [comment]
@danieliser That section is added in Triggers.php where I can't easily retrieve the ID for the current popup being edited. I temporarily switched to `popmake-{popup-ID}` but it would be better to show the actual ID there.
https://github.com/PopupMaker/Popup-Maker/blob/develop/classes/Triggers.php#L157

We could add an empty HTML element there, such as `popmake-<span id="click-trigger-id">{popup-ID}</span>`. Then, add some JS to our editor JS to replace that with the popup ID. 

Can you think of a more efficient way to do it?

**Comment by danieliser** [comment]
Yea I would use a placeholder and JS to swap it based on the post_ID field value.

**Comment by fpcorso** [comment]
@danieliser Set the field to have a span placeholder and have some JS to swap it. However, the click settings template for the field gets regenerated every time you add a trigger. So, when you click the add trigger button, it regenerates the template, thus showing the placeholder instead of the new value I swapped it with.

Any thoughts on why you have the template being regenerated? Would it break anything if I changed it?

Alternatively, I could swap out the placeholder when the click trigger settings open instead.

**Comment by danieliser** [comment]
@fpcorso Try pumInit JS event.

I would do it like this for now.

    <span class="pum-default-click-trigger-classes"></span>

And inside the above JS event something like this.
```
jQuery('.pum-default-click-trigger-classes:not(.initialized)').each(function () {
    var $this = jQuery(this);
    $this.addClass('initialized');
    $this.text('set it to whatever here');
});
```
Will fire off every time a form is re-rendered.

**Comment by fpcorso** [comment]
@danieliser That code doesn't work. The issue wasn't finding or changing the text. It's that the plugin completely recreates the template when the trigger is being added.

Running that code above changes the span text correctly during pageload or puminit. But, as soon as the trigger button is clicked, the template is overwritten to use the default empty span again.

**Comment by danieliser** [comment]
@fpcorso Sorry your right, I was mistaken, it seem the proper event name is pum_init for some reason: https://github.com/PopupMaker/Popup-Maker/blob/master/assets/js/src/admin/popup-editor/plugins/triggers.js#L304

That event is triggered on every redraw of a form intentionally. Because of that you must "initialize" elements in a detectable way. That is why it uses `:not(.initialized)` in the selector and `$this.addClass('initialized');` in the handler because it will run regularly and we don't want to keep reiniting things that didn't get redrawn.

**Comment by fpcorso** [comment]
@danieliser Ah, I thought the pum_init type events only fire when all of PM is initialized. I didn't realize we also have one firing each time after the form modal is recreated. I'll need to play with that to see if I can find it and work with that.

Where is that called? I didn't see it in the modal or template JS files which are the only thing called during that form method?

**Comment by danieliser** [comment]
@fpcorso Check the render method for forms: https://github.com/PopupMaker/Popup-Maker/blob/master/assets/js/src/admin/general/plugins/forms.js#L484

It triggers on the form itself, but like I mentioned in my PR review today, events bubble up to document, so we catch it there.

**Comment by fpcorso** [comment]
@danieliser I don't think we ever call any methods from forms.js here. The method I linked to (`triggers.form`) only calls modals.reload and templates.modal. Neither of which calls any methods from forms.js.

Here is where the modal gets created in triggers.js:
https://github.com/PopupMaker/Popup-Maker/blob/master/assets/js/src/admin/popup-editor/plugins/triggers.js#L134

Which calls templates.modal which is just a quick wrapper for templates.render which only calls `wp.template` and does some preparations before returning it: https://github.com/PopupMaker/Popup-Maker/blob/master/assets/js/src/admin/general/plugins/templates.js#L8

All that the modals.reload method does is remove the old HTML and appends the new HTML: https://github.com/PopupMaker/Popup-Maker/blob/master/assets/js/src/admin/general/plugins/modals.js#L140

That said, at the very end of that method, it triggers a `pum_init` event so the idea should still work.

Unfortunately, I can't get it to work for some reason. `pum_init` event is not firing when opening and going through the modals. I tried using a similar version to the code above but it didn't successfully change the span. I tried attaching a simple `console.log('Yes');` to `pum_init` and it only fired when I called it manually and did not fire when adding or editing triggers for some reason. Still looking through it.

**Comment by fpcorso** [comment]
@danieliser Nevermind that last paragraph. I had a type in my code 🤦‍♂️

**Comment by fpcorso** [comment]
@danieliser So, it does work, but `pum_init` fires many times throughout the course of creating a popup. My code ran a couple of dozen times by the time I finished testing creating a popup. Is that sufficient or should we go back to the original place I suggested of right after the trigger settings modal gets created?

**Comment by danieliser** [comment]
@fpcorso Its effecient as long as your code properly bails early. That is what the `:not(.initialized)` & `.addClass('initialized')` handle.

Again make a new -initialized class for this.

**Comment by fpcorso** [comment]
@danieliser Got this working correctly now:
![image](https://user-images.githubusercontent.com/9730040/91883350-4bb75180-ec52-11ea-96c5-2e038b880a1e.png)
