### ISSUE TITLE
popup_close shortcode tag element not working.

### ISSUE THREAD

**Issue by adibpg** [PopupMaker/Popup-Maker#593]
WordPress version: 4.9.8
Plugin version: Version 1.7.30

Expected behavior:
using the shortcode [popup_close tag="button" classes="extra-button-class"]Content[/popup_close]
should create an element < button class="pum-close popmake-close extra-button-class" >Content< /button >

Actual behavior: 
using the shortcode [popup_close tag="button" classes="extra-button-class"]Content[/popup_close]
creates element < span class="pum-close popmake-close extra-button-class" >Content< /span >

Longer explanation:
It seems that whatever I put in the shortcode's tag the button comes out as a span.

**Comment by danieliser** [comment]
Based on the code used to render that shortcode I’m not sure how that would be possible

https://github.com/PopupMaker/Popup-Maker/blob/master/classes/Shortcode/PopupClose.php#L115

**Comment by danieliser** [comment]
Ugh I see it. A few lines above it says if ( empty $attrs[‘’] ) ) { $atts[‘tag’] = ‘span’; }

It should be checking if the tag is empty. Will get a patch out for it.

**Comment by fpcorso** [comment]
Fixed in a recent commit on `develop`. Will be fixed in 1.11!
