### ISSUE TITLE
New shortcode to set cookies.

### ISSUE THREAD

**Issue by danieliser** [PopupMaker/Popup-Maker#597]
Allows users to set a cookie, disabling a popup, simply by inserting a shortcode on the page or tagging an html element with some extra parameters.

- [x] Should not trigger until visible.
- [x] Manual cookies should show this shortcode with atts prefilled for easy copy/paste.

**Comment by danieliser** [comment]
@fpcorso Any thoughts on the name of this shortcode?

- `set_cookie`
- `popup_conversion`
- `popup_action` - Kinda like this one if we considered adding other functionality into these.
- `popup_cookie`
- `pum_cookie` - Namespaced might be good idea, though doubt popup_cookie is used either, and we have set precedent with `popup_trigger` & `popup_close` already.
- `pum_action`

I kinda like `popup_action`. We could then make aliases for it that handle different things in shorter fashion.

Such as this shorthand to set a cookie 
`[popup_cookie name="pum-123" expires="1 week"]` 
which aliases to 
`[popup_action set_cookie="true" cookie_name="pum-123" cookie_expires="1 week" cookie_path="/"]`

I am thinking this way makes since as we expand on what you can do with an action (see action system).

So it will also immediately support

`[popup_conversion popup_id="123" type="form" form="my embed/custom form"]` 

This would mainly be used for people with Popup Analytics, but has other uses too if we track conversions in the free version (which we probably should do minimally like we do for opens as just a count).

But it would map to

`[popup_action conversion="true" popup_id="123" conversion_type="form" form="my embed/custom form"]`

That might be something we expand on later though.

In this case I'm defaulting to `popup_cookie` for now, can relabel it with more feedback in another commit before we merge.

**Comment by fpcorso** [comment]
@danieliser , I only vaguely remember our conversation on this specific shortcode from months ago and what use-cases it unlocks so I am not entirely sure which shortcode name is the best. However, based on my limited recollection of the conversation and your points in your previous comment, I would agree that `popup_pixel` with aliases would be appropriate.

**Comment by danieliser** [comment]
@fpcorso This is used for things like embed forms that redirect to a thank you page. We can't detect the submission directly to set a cookie or track conversions, but they can set this pixel on the thank you page and it will fill that gap without having to also load the popup on that page.

Test it out, it works now.

**Comment by danieliser** [comment]
![image](https://user-images.githubusercontent.com/847818/77811831-8994c600-7073-11ea-9977-cbb0bd0120c5.png)

When you make a manual cookie now it shows the shortcode with those settings set already for each copy/paste.

That said the shortcode & manual trigger are not related, so you can also just write the shortcode from scratch and not add a manual cookie to the popup. Still works.

Just put that there for easy intuitiveness for the user to some degree.
