### ISSUE TITLE
Full Support for Gutenberg

### ISSUE THREAD

**Issue by danieliser** [PopupMaker/Popup-Maker#608]
- [x] Editor works for popups

## Resources
- https://github.com/ahmadawais/create-guten-block
- https://javascriptforwp.com/how-to-build-a-gutenberg-block-with-registerblocktype-and-no-webpack-es6-jsx-or-babel/
- https://javascriptforwp.com/wordpress-plugin-sidebar-api-tutorial/
- https://richardtape.com/2018/10/05/add-a-custom-sidebar-panel-to-gutenberg/

Migrated dependent issues from ZenHub:

- [ ] Issue #650 
- [ ] Issue #652 
- [ ] Issue #653 
- [ ] Issue #654 
- [ ] Issue #655

**Comment by fpcorso** [comment]
Since we are now using GitHub projects to track these, I am going to close this one.
