### ISSUE TITLE
Popups shouldn't have rewrite

### ISSUE THREAD

**Issue by sybrew** [PopupMaker/Popup-Maker#611]
The `popup` custom post type is registered with both the `public` and `rewrite` parameters.

I don't think either should be enabled, with `rewrite` especially so.
Visitors can access popups easily via `?p={popupid}`, and I don't think they're meant to be used this way.

**Comment by danieliser** [comment]
It is public but rewrite shouldn’t be enabled as we have publicly queryable and query bar set to false.

Public is required to handle quite a few things but namely page builder and Gutenberg support.

So I can add rewrite fake but your out of luck on us changing public any time soon.

**Comment by danieliser** [comment]
Further ?popup=1 ultimately should do something, open Popup 1 on the page already being viewed.

**Comment by danieliser** [comment]
Feel free to use the filter for those rags though to tweak it for your needs in the mean time.

**Comment by sybrew** [comment]
The main issue with this was already found earlier by you or your colleagues, as seen in these lines:
https://github.com/PopupMaker/Popup-Maker/blob/c1f5c2e43f8f80989e4cab29f375adbd1d914a61/classes/Types.php#L43-L46

Plugins expect they can work with the front-end of things of these post types, and automatically embed them in their systems.

I overstated my claim on the `public` part, but I do think `rewrite` can use some tweaking. 
However, if this would cause issues further down the line or break current implementations, then I don't recommend enforcing this rule. Luckily, there are many ways around it 🙂
