### ISSUE TITLE
Active license keys show invalid license admin notice.

### ISSUE THREAD

**Issue by danieliser** [PopupMaker/Popup-Maker#612]
You have invalid or expired license keys for Popup Maker. Please go to the Licenses page to correct this issue.

**Comment by danieliser** [comment]
Notify user: https://secure.helpscout.net/conversation/709347059/10458?folderId=557106

**Comment by danieliser** [comment]
Notify user: https://secure.helpscout.net/conversation/707409503/10436/

**Comment by lkraav** [comment]
Yep, I noticed the same.

**Comment by danieliser** [comment]
@ikraav - Trying to wrap this one up for v1.8. Do you have a site where its currently occurring? If so can you check the DB and see what the actual status of your license is there?

The only thing that makes since is that the status is coming back as something that is not "valid" but means its working fine with some limitation.

Knowing what it is means I can check for that and not show a message based on that.

**Comment by danieliser** [comment]
This appears it could be licensing server side as one user sent in his saved license status object from wp_options, its stored as invalid which is the direct response from the server, punting this as it doesn't appear to be fixable in the core plugin at this time and needs to be addressed on our servers.

That said notices of this nature will now be dismissable for 30+ days anyways.

**Comment by fpcorso** [comment]
@danieliser Do you know if this is still occurring or have had any other new details concerning the server side of the issue?

**Comment by danieliser** [comment]
@fpcorso I have no recent reports, so I'm guessing patched in later versions of EDD SL + SL Updater class.

That said wouldn't hurt to double check our EDD_SL_Updater class extension is up to date with their example.
