### ISSUE TITLE
Admin Bar not showing on frontend when plugin active

### ISSUE THREAD

**Issue by Stryder777** [PopupMaker/Popup-Maker#614]
Whenever popupmaker is active, it removes the wpadmin bar from pages. Is there a way to resolve this by changing a plugin action in my functions.php file?

Please advise

**Comment by lkraav** [comment]
It probably means a crash. Investigate server logs first.

**Comment by Stryder777** [comment]
> It probably means a crash. Investigate server logs first.

Its not a crash as everything is running 100%. When active the plugin simply hides the WordPress Admin Bar that should be showing on the frontend of the website.

Only when the popup is activated does the admin bar return.

**Comment by rgadon107** [comment]
@Stryder777 Please see the following documentation article: https://docs.wppopupmaker.com/article/265-my-popup-wont-work-how-can-i-fix-it

Refer to Item #3.  Use inspection tools to assess whether the `wp_footer()` action is present and loading scripts. If the WP Admin toolbar is missing, the Popup Admin Toolbar will be missing too. Likely your theme template is not loading.

**Comment by danieliser** [comment]
@stryder777 - @ikraav nailed it. Need logs. There is no other explanation unfortunately.

To be clear we aren’t unhooking it. It means a fatal php error occurred after your themes visual footer was rendered but before the admin bar was rendered.

If it goes away when you disable popup maker, the error is coming from whatever content you have inserted into your popups, likely not the popups or Popup Maker itself.

This has been the case every single time this gets reported.

Try marking all popups draft. Then retest. Re publish one at a time to figure out which it is. 


Hope that helps.
