### ISSUE TITLE
PUM v1.8.0 -- Popup Theme Menu Options in Popup Settings Box Are Blank

### ISSUE THREAD

**Issue by rgadon107** [PopupMaker/Popup-Maker#619]
@danieliser I updated the 'release/1.80' branch of my local PUM install. The Popup Theme menu options in the Popup Settings box are blank. See attached screenshot (includes display of markup). When I click on the menu box, no options appear in the menu drop-down. 

From the WP Admin, 'Popup Maker' >> 'Settings' >> 'General', the default theme set for my PI install is 'Default Theme'. 

![pum_popup_settings_theme_selector](https://user-images.githubusercontent.com/3718603/50707584-e64b3180-1026-11e9-9d70-c00a15fa7bca.png)

**Comment by danieliser** [comment]
Already saw and patched this one, should be fixed in latest.
