### ISSUE TITLE
PUM 1.8.0 -- Popup Theme Settings box is Missing Upsell Notice & Link to ATB Plugin

### ISSUE THREAD

**Issue by rgadon107** [PopupMaker/Popup-Maker#620]
For PUM v1.8.0, in the Popup Theme Settings box , the Overlay and Container >> Background options are missing the notice and link to the Advanced Theme Builder plugin extension. Oversight or intentional? If the former, add back in. If the latter, then close out this issue. 

Also noticed that the descriptions underneath the color and opacity settings for both Color and Opacity on the Overlay tab are removed. Again, oversight or intentional?

![pum_theme_settings_overlay--missing-atb-upsell](https://user-images.githubusercontent.com/3718603/50708619-97070000-102a-11e9-8ff6-615b379d1fca.png)

**Comment by danieliser** [comment]
@rgadon107 Good catch.
