### ISSUE TITLE
Release/1.8.0 branch -- 'Cutting Edge' Theme Title & Content color properties changed

### ISSUE THREAD

**Issue by rgadon107** [PopupMaker/Popup-Maker#626]
@danieliser Screenshots of the Cutting Edge popup theme for PUM version 1.7.30 compared to the release/1.8.0 branch. Check the default color settings for the Title >> Font and Content options on the release/1.8.0 branch. The title and content on the theme preview is bleached out. 

**Cutting Edge Theme preview -- PUM v1.7.30**
![cutting_edge_theme_preview_version_1_7_30](https://user-images.githubusercontent.com/3718603/51136552-60876d00-1802-11e9-9a00-1171439923f9.png)

**Cutting Edge Theme preview -- release/1.8.0 branch**
![cutting_edge_theme_preview_version_release_1_8_0_branch](https://user-images.githubusercontent.com/3718603/51136578-76952d80-1802-11e9-93fb-50cd449d07e3.png)

Theme settings are installed `/Popup-Maker/includes/pum-install-functions.php` on L#50.

**Comment by danieliser** [comment]
Hmm this isn't the cutting edge theme at all, should look like these: https://themes.wppopupmaker.com/

**Comment by rgadon107** [comment]
Fixed since 01/14/2019. Close issue.
