### ISSUE TITLE
Release/1.8.0-beta.1: Disable BG Color property on Theme Overlay when BG Image Active

### ISSUE THREAD

**Issue by rgadon107** [PopupMaker/Popup-Maker#630]
@danieliser The following issue applies to a use case where a user of the Advanced Theme Builder PI extension customizes a popup theme by selecting 'Background' >> Type = 'Image' on the Popup Themes 'Overlay' option tab. 

Set a condition to remove the 'Background Color' property from view. It continues to appear after 'Image' is selected for Background > Type. However, changing the value of the BG Color property has no effect in the theme preview customizer, nor on the front end. It's presence in the Admin UI when 'Image' is selected will confuse users.

**Comment by danieliser** [comment]
Now repeat those same steps with a png that has transparency in it ;).

**Comment by danieliser** [comment]
@rgadon107 Closing this one if you have no other objection, in any case it belongs in the extensions issues, not core.

If you didn't get the meaning of the last comment, I was trying to point out you can put color behind a transparent image using that background color, then also layer on an overlay color as well for 3 layered effects.
