### ISSUE TITLE
Release/1.8.0.beta.1 -- Popup must be updated to render updated Popup Theme postmeta

### ISSUE THREAD

**Issue by rgadon107** [PopupMaker/Popup-Maker#631]
@danieliser This is a subtle issue that I stumbled upon in testing the beta. Here's the setup: 

- PUM **Default Theme** assigned to a test popup (post_id: 19) in **Popup Settings box > Display option**. 
- Default Theme assigned post_id: 4. 
- In the 'popup_settings' for the Default Theme (meta_key: 220 on my test site), the 'close_text' property is set to value of 'DO SOMETHING'.  The string 'DO SOMETHING' overwrites the previous value of 'X''. 
- Update the popup theme (post_id: 4). The popup (post_id: 19) is not updated with the new value for the 'close_text'. 

On front end, popup auto opens with close text of 'X'. Changes to the Default Theme close_text property do not render. 

Open the Popup Editor and select 'update' on the popup (post_id: 19). Visit FE and popup now displays the updated close_text for the Default Theme 'DO SOMETHING'. 

I'm not sure if you intended users to go through that process or not. It's a subtle design in the plugin that might cause users to freak out and submit a support request. If you can set all popups that use a specific theme to update their settings when the popup theme updates, that could save you having to respond to a ticket.

**Comment by danieliser** [comment]
So to boil that down, if you assign the theme then update the theme text, it doesn’t show up, but if you update the Popup afterwards the new default text shows up properly?

Simple enough. This issue likely cropped up due to my efforts to reduce queries. I did so in this case by presaving the theme close text in Popup data so as to not have to query Popup theme meta.

**Comment by rgadon107** [comment]
@danieliser Yup. That's pretty much it. 

Just to clarify:  if you assign the theme [in the Popup Editor] then update the theme text [in the Popup Theme Editor, the change to the 'close_text' field'] doesn’t show up [on the front end], but if you update the Popup afterwards the new default text [add from the Popup Theme Editor] shows up properly? [Just want to make sure there's no confusion here.]

Simple enough. This issue likely cropped up due to my efforts to reduce queries. I did so in this case by presaving the theme close text in Popup data so as to not have to query Popup theme meta.

If you can change the query to update the post data when the popup_theme postmeta updates, that will likely fix the problem.

**Comment by danieliser** [comment]
Fixed.
