### ISSUE TITLE
Release_1.8.0_beta.1 -- Close Button Positioning Offset from Popup Container Mid-R & Mid-L

### ISSUE THREAD

**Issue by rgadon107** [PopupMaker/Popup-Maker#634]
@danieliser Testing out the positioning of the close button around the popup container for the newly available anchor positions. On the corners (top right, top left, bottom left, bottom right) and top and bottom margins, the close button positions fine in both theme preview and on the front-end. 

In the Theme Settings preview box, the middle-left and middle-right positions for the close button appear where they're expected. On the front-end, the buttons are offset from the border of the popup container. I just want you to be aware of this. Are you able to duplicate this on your own test site? You might receive some comments about this from users.  

Issue occurs whether GB support is enabled or not. 

![popup_maker_popup_theme_editor_preview_close_button_middle_left](https://user-images.githubusercontent.com/3718603/51573127-a7faa280-1e6d-11e9-9714-fb33d07c191c.png)
![popup_maker_popup_theme_close_button_middle_left_offset](https://user-images.githubusercontent.com/3718603/51573137-ae891a00-1e6d-11e9-8458-36335c64f282.png)
![popup_maker_popup_theme_editor_preview_close_button_middle_right](https://user-images.githubusercontent.com/3718603/51573145-b47efb00-1e6d-11e9-9a88-e892dd585a19.png)
![popup_maker_popup_theme_close_button_middle_right_offset](https://user-images.githubusercontent.com/3718603/51573166-c2348080-1e6d-11e9-88e1-6bbd6432ff74.png)

**Comment by danieliser** [comment]
Was able to duplicate this, see if the patch above fixed it for you, just pull the latest release/1.8 branch.
