### ISSUE TITLE
How to remove Google Import font 

### ISSUE THREAD

**Issue by cinghaman** [PopupMaker/Popup-Maker#636]
How to remove popupmaker for adding 
/* Popup Google Fonts */
@import url('//fonts.googleapis.com/css?family=Acme|Montserrat');

to the Stylesheet, I don't want the google fonts to load, I am loading them directly in theme.
Any action/hook?

Thanks

**Comment by rgadon107** [comment]
@cinghaman Please see our documentation: https://docs.wppopupmaker.com/article/363-popup-maker-admin-introduction#misc. Specifically refer to Section 6.C.ii; Assets' option category (3 option settings & 1 button). Do a command-F in your browser and search on 'Assets' option category. It will take you right to the section. You need to disable a setting for loading Google Fonts in the Popup Maker Admin. The doc explains everything you need to do.

**Comment by cinghaman** [comment]
Perfect Thanks
