### ISSUE TITLE
Set up automated testing

### ISSUE THREAD

**Issue by danieliser** [PopupMaker/Popup-Maker#640]
Now that we have PHPUnit set up and some integration tests created, we need these to be automatically run during pull requests, commits, merges, etc...

Merge these into something usable.
- [ ] https://deliciousbrains.com/deploying-wordpress-plugins-travis/
- [ ] https://github.com/deliciousbrains/wp-plugin-build
- [ ] https://github.com/kevindees/travis-ci-wordpress/
- [ ] https://medium.com/@nihon_rafy/how-to-mock-static-methods-for-unit-tests-in-php-18b2a11458d0
- [ ] https://carlalexander.ca/continuous-integration-wordpress/

**Comment by fpcorso** [comment]
@danieliser I did some research on this and we can definitely utilize GitHub Actions for this since our tests are rather straightforward. The question is: When should we run the tests? Just pushes on `master` and on PR's to `master`? Or, should we do PR's to `develop` too? Should we run the tests for each push to `develop` too?

**Comment by danieliser** [comment]
@fpcorso I think this ideally should occur when a PR is submitted against `develop`, it prevents us from having to patch things in `master`. This way all new code must pass before merging.

Probably same for linting and other checks as well.

**Comment by fpcorso** [comment]
@danieliser I see two problems doing it only for PR's for `develop`:

1. There are several smaller items that we commit directly to `develop`. Then, we branch off the `release/x` branch where we also commit to. So, when that goes to get merged into `master` it can contain quite a bit of code that wasn't in PR's for `develop`.
2. What about `hotfix/x` branches? We branch those off of `master` and then merge back into `master` so those wouldn't get tested.

This is why I was thinking we should also do PR's to `master` as well.

**Comment by danieliser** [comment]
@fpcorso My only concern with doing it off `master` might have been misplaced. For some reason I was thinking that would also pick up all the old code that is already malformatted, but it is probably only scanning the lines committed in the merge, otherwise thinking it through the branches merged into `develop` would also have that old/dirty code.

So I guess all merges into `master` & `develop` ?
