### ISSUE TITLE
Can't save cookie site wide checkbox unchecked.

### ISSUE THREAD

**Issue by danieliser** [PopupMaker/Popup-Maker#642]
User says he can't save cookies with site wide cookies disabled.

https://secure.helpscout.net/conversation/703282259/10383/

**Comment by fpcorso** [comment]
@danieliser This sitewide checkbox has been broken for over two years now so we know no one is using it. And yet, we have only received a couple of tickets about it all year.

Should we just remove the feature since it is apparently something no one will miss or should we go ahead and fix it?

**Comment by danieliser** [comment]
@fpcorso that could be an option honestly.

**Comment by fpcorso** [comment]
@danieliser What was the original use-case for this feature? Why would someone want a cookie that is not site-wide?

**Comment by danieliser** [comment]
@fpcorso - Essentially having a single popup across multiple pages, but making users convert on each of them separately. That may just be viewing the popup on every page.

Its been used, but rarely.

**Comment by fpcorso** [comment]
@danieliser We do know no one has used it in the last two years since it's been broken for that long. That use case does sound interesting but, based on searches in HelpScout, it doesn't look like that many people have asked for it.

So, should we remove it or fix it?

**Comment by danieliser** [comment]
@fpcorso Fixing it is obviously the simpler route all things considered. If we opt to remove it we now have to update docs, likely put an explanation of its removal, respond to tickets for users who suddenly find the option missing (even if they weren't using it 🤦‍♂️) etc.

But I do like the prospect of starting to remove the unneccessary fluff. I loved that about Ahoy.

So if we can't find any evidence its in use, maybe hide it as an option and add some way to filter it back on at first. If we go 3-4 months without any support requests, then we can officially remove it.
