### ISSUE TITLE
contact form dropdown not working in popup

### ISSUE THREAD

**Issue by iamjmbkm** [PopupMaker/Popup-Maker#649]
Hello,

I added a dropdown in my contact form but the dropdown is not working in the popup

**Comment by rgadon107** [comment]
@jbakoume I'm not working plugin support today. However, I want to refer you to our plugin documentation for assistance. In particular, please follow the checklist in this doc. Narrow down or eliminate the possibilities that might be contributing to the problem. If unable to solve, please login to your site Admin, go to 'Popup Maker' >> 'Help & Support', and select the button 'Submit Support Request'. 

https://docs.wppopupmaker.com/article/265-my-popup-wont-work-how-can-i-fix-it

https://docs.wppopupmaker.com/article/373-checking-javascript-errors

**Comment by jbakoume** [comment]
tha

> @jbakoume I'm not working plugin support today. However, I want to refer you to our plugin documentation for assistance. In particular, please follow the checklist in these 2 docs. Narrow down or eliminate the possibilities that might be contributing to the problem. If unable to solve, please login to your site Admin, go to 'Popup Maker' >> 'Help & Support', and select the button 'Submit Support Request'.
> 
> https://docs.wppopupmaker.com/article/265-my-popup-wont-work-how-can-i-fix-it
> 
> https://docs.wppopupmaker.com/article/373-checking-javascript-errors

thanks checking that

**Comment by danieliser** [comment]
@jbakoume - it’s likely a z-index layering issue. Ie your dropdown is appearing behind the Popup. Either change your popups z-index to something much Lowe via display settings or make your dropdown use a higher z-index.

**Comment by jbakoume** [comment]
@danieliser thanks for your recomendations, do you know how i can do that. I just checked and effectively when triggered, the dropdown appears behind the popup.

**Comment by danieliser** [comment]
Popup Settings > Display Tab > Advanced > Z Index setting.---- On Thu, 14 Mar 2019 15:55:50 -0400  jbakoume<notifications@github.com> wrote ----@danieliser thanks for your recomendations, do you know how i can do that. I just checked and effectively when triggered, the dropdown appears behind the popup.

**Comment by jbakoume** [comment]
@danieliser  I dont have that option as you can see.
<img width="1280" alt="Screen Shot 2019-03-14 at 21 03 07" src="https://user-images.githubusercontent.com/25420310/54387905-d2622280-469c-11e9-8d78-d5a1ae7bd388.png">

**Comment by rgadon107** [comment]
@jbakoume See: https://docs.wppopupmaker.com/article/454-popup-settings-box-display-option-settings. View 'Popup Z-Index'.

**Comment by jbakoume** [comment]
@rgadon107 @danieliser I have reduce the popup z index but it doesnt work. i increasing the dropdown  z index will work.

**Comment by iamvasee** [comment]
I just got the same issue. Has anybody figured out a way to fix this?

**Comment by danieliser** [comment]
@iamjmbkm, @iamvasee - You likely just need to lower the z-index further. Very likely you set it to 1000+ still and your form is showing at <999. Try 99 or even 10 just to make sure.

**Comment by danieliser** [comment]
Otherwise there is little we can do if their forms aren't rendering properly when the popup is basically at page level. They would likely need to dig into it from their end (the form plugin) and provide some insights

**Comment by ErnestPH** [comment]
Just confirming that reducing z-index to 1000 actually works... This is now ok.
