### ISSUE TITLE
Convert shortcodes to Gutenberg blocks

### ISSUE THREAD

**Issue by danieliser** [PopupMaker/Popup-Maker#653]

**Comment by fpcorso** [comment]
Copied from Slack:

> If we could make the normal PM toolbar button work everywhere in Gutenberg that would be a solid middle step, but even that could be a ton of work. Not sure what the most effective path forward is:
> 1. Make current implementation of PM button compatible with more blocks in Gutenberg, specifically the Shortcode block and HTML/paragraph blocks
> 2. Make a compatibility layer that converts our PUM_Shortcode objects into gutenberg blocks with proper form components. We have a layer like this now that converts from PHP objects into JS form rendering, duplicating that essentially).
> 3. Rewrite them to actually be blocks. Each would be redone separately and likely either pass options through do_shortcode or similar.

**Comment by fpcorso** [comment]
Breaking these up into individual issues for better scoped projects
