### ISSUE TITLE
Fix artificial limitation of 10 selections for Page Selected conditions.

### ISSUE THREAD

**Issue by danieliser** [PopupMaker/Popup-Maker#656]
It will let you add 20, but after saving only 10 show up.

My thinking is its in our query that populates it initially.

**Comment by fpcorso** [comment]
@danieliser Has this been fixed or have you had any recent reports of this?

I created 20 pages and added them all to a "Page Selected" condition:
![image](https://user-images.githubusercontent.com/9730040/83660391-c8bf2600-a592-11ea-895c-ac5852e61f68.png)

Clicked "Update" and then came back to the popup editor and still see all 20 pages in the condition.

**Comment by danieliser** [comment]
Yea I believe I actually patched it in Ahoy, then this fix and a few others got back ported to PM shortly after. It should be resolved.
