### ISSUE TITLE
How to reset the form when popup closed and open it fresh again ?

### ISSUE THREAD

**Issue by Shailesh1709** [PopupMaker/Popup-Maker#657]
I have used contact form 7 on popup whenever I am clicking on submit form button the form gets submitted and it shows a success message. so I closed the popup again whenever I open the popup I am able to see the same success message. I want whenever I close the popup a fresh contact form should open. Can you please help me to do that!

**Comment by danieliser** [comment]
@shailesh1709 - that would be a question for the form plugin support. That has nothing to do with our plugin. The solution would be the same whether the form was in the Popup or on the page.

You seem to also be assuming that the popups content is loaded when the trigger is clicked. The popups content is rendered when the page loads as part of the page hidden in the footer.

Hope that helps.
