### ISSUE TITLE
Old popmake_get_popup method gone

### ISSUE THREAD

**Issue by CheezeCoder** [PopupMaker/Popup-Maker#663]
I haven't touched a theme I created several years ago that used popup maker.  In my functions.php I had a method to get a pop up id and looked like so this:

```php
  $modPopUpId  = popmake_get_popup(popmake_get_the_popup_ID());
  include(get_module_part('popup'));
```

The method appears to have disappeared from the popup maker code base and is as such disabling all popups on our site.  Is there a modern equivalent to this old api?

I couldn't seem to find anything in the documentation that wasn't short codes which I am not using.

**Comment by danieliser** [comment]
What is that code supposed to do exactly? It shouldn’t be disabling your popups if your using our existing functionality as they are rendered by our own hooked functions in the footer.

`pum_get_popup` Is the equivalent.

**Comment by CheezeCoder** [comment]
This code base is a bit old so its not my finest work but essentially I am appending all the popups to the page by hooking into 'pum_popup_after_content'  here's the  whole function:

```php
function add_popup_acf_fields()
{
  $fields   = include __DIR__ . '/utils/acf-field-names.php';
  $modPopUpId  = popmake_get_popup(popmake_get_the_popup_ID());;
  include(get_module_part('popup'));
}

add_action('pum_popup_after_content', 'add_popup_acf_fields', 10, 1);
```

should have included it before sorry.  

The result of `popmake_get_popup(popmake_get_the_popup_ID());` is passed along to my popup template which I include with the final method of that function.   This allows me to access a bunch of ACFs i have on the popups.  

Yep its not the greatest solution ever but its a mess to rewrite right now and I just needed to patch it up. `pum_get_popup` solves the issue for me cheers.
