### ISSUE TITLE
Popup not working on Safari

### ISSUE THREAD

**Issue by horaceleung** [PopupMaker/Popup-Maker#665]
On the website below, when I open the popup by clicking the play button next to "Chest Size"
, the video does not play in Safari (But it works on Chrome).

https://suitablepro.com/product/shirt-multi-color-ii/#page-top

<img width="1365" alt="Screenshot 2019-05-07 at 7 05 56 PM" src="https://user-images.githubusercontent.com/16663831/57294762-3f24f680-70fb-11e9-8f45-f103177e98f8.png">

**Comment by danieliser** [comment]
@horaceleung - Closing this as it's a support issue, not an actual issue with the plugin that can be fixed with patches, so it doesnt belong here on our issue tracker.
