### ISSUE TITLE
Popup HTML inserted in every page

### ISSUE THREAD

**Issue by midzer** [PopupMaker/Popup-Maker#668]
Hi,

I'm working on https://www.feuerwehr-ub.de/ right now which uses PopupMaker.

How come PopupMaker inserts HTML code on startpage (and other pages) where there have been no popups created with Popupmaker at all?

Thanks for your feedback in advance and have a nice day
midzer

**Comment by danieliser** [comment]
@midzer - As we have many available channels for support questions this is not the appropriate place to ask questions. Only to report actual issues/bugs in the plugin itself.

The answer is simple though. That’s how you set them up. If you didn’t apply any targeting conditions to each Popup to limit where it loads then its on every page by default. All explained in the targeting tab and in our docs.

Hope that helps
