### ISSUE TITLE
Let users know about our youtube channel

### ISSUE THREAD

**Issue by danieliser** [PopupMaker/Popup-Maker#672]
Can either add a new notice (ehh) or put a button in the tabs bar with Apps & Integrations

**Comment by fpcorso** [comment]
@danieliser For this issue, what if we just added a "Watch tutorials on our YouTube" type text in the iframe for Help & Support like we do with the FB group: 
![image](https://user-images.githubusercontent.com/9730040/73376644-c585f780-428b-11ea-8762-9d25fb7507fb.png)

**Comment by danieliser** [comment]
Sounds good, you can do that via the API server.

**Comment by fpcorso** [comment]
Added to the help and support page.
