### ISSUE TITLE
Interference with Ninja Form Radio

### ISSUE THREAD

**Issue by thekuom** [PopupMaker/Popup-Maker#673]
I have some custom JS on my website that listens to the ninja forms radio:
```
jQuery(document).ready(function($) {
  var myController = Marionette.Object.extend({

    initialize: function() {
      this.listenTo(Backbone.Radio.channel('forms'), 'submit:response', function () {
        console.log('hello world!');
      });
    }
  });

  new myController();
});
```
As expected, when I submit my form, "hello world!" is printed to the console. When I activate Popup Maker and I submit the form, nothing is printed to the console

**Comment by danieliser** [comment]
@thekuom - You will likely need to consult with NF devs on that one. The code we have is similar: https://github.com/PopupMaker/Popup-Maker/blob/master/assets/js/src/site/plugins/pum-integrations.js#L10-L39

But they wrote the initial part for me and I filled in the blanks ;), so if its not compatible I wouldn't know why that would be.

**Comment by kjohnson** [comment]
@thekuom is this still an issue?

I'm not able to replicate as of PUM v1.8.11 / NF v3.4.20 using https://gist.github.com/kjohnson/79dfd4f28b4c0a1754631052cd47d386
