### ISSUE TITLE
Update WooCommerce endpoint options

### ISSUE THREAD

**Issue by danieliser** [PopupMaker/Popup-Maker#674]
`orders` appears to be a new addition to the WC endpoint list.

https://docs.woocommerce.com/document/woocommerce-endpoints-2-1/

**Comment by fpcorso** [comment]
@danieliser Is this already completed? I see `orders` in our code: https://github.com/PopupMaker/Popup-Maker/blob/master/includes/integrations/class-pum-woocommerce-integration.php#L68

**Comment by danieliser** [comment]
Hmm, seems to have been updated shortly before this was made, wonder if I meant to close this when it was released.
