### ISSUE TITLE
Fix Dead in-Article Links in PUM Documentation

### ISSUE THREAD

**Issue by rgadon107** [PopupMaker/Popup-Maker#682]
@danieliser Hello Daniel, I’ve been reviewing the PUM docs in preparation for a job application I’m preparing. In the course of my review, I came across a couple of dead links. Thought you might want to know about them in case you want to fix them.

======================================================

Collection: How To
Category: Apply Popup Maker

Article: Display Multiple Popups at the Same Time

Section: 1) Create Two Popups and Set to 'Status: Published'

Related Article: Popup Maker Admin Introduction
Change the link name to: All Popups submenu
Change the link URL to: https://docs.wppopupmaker.com/article/489-popup-maker-admin-all-popups-submenu

Section: 2) Change the Default Popup Size of the Stackable Popups

Related article: 'Display - Size' option settings
Change the link name to: ‘Display’ option settings // Size setting
Change the link URL to: https://docs.wppopupmaker.com/article/454-popup-settings-box-display-option-settings

Section: 3) Set the 'Fixed Positioning' Option

Related article:  Related article:  'Display - Position' option settings
Change the link name to: ‘Display’ option settings // Position setting
Change the link URL to: https://docs.wppopupmaker.com/article/454-popup-settings-box-display-option-settings

Section 4) Anchor the Popup Position by 'Location'

Related article: 'Display - Position' option settings
Change the link name to: ‘Display’ option settings // Position setting
Change the link URL to: https://docs.wppopupmaker.com/article/454-popup-settings-box-display-option-settings

Section 5) Set the 'Stackable' Option 

Related article: 'Display - Advanced’ option settings
Change the link name to: ‘Display’ option settings // Advanced setting
Change the link URL to: https://docs.wppopupmaker.com/article/454-popup-settings-box-display-option-settings

======================================================

Collection: Advanced
Category: Creating Cookies

Article (1): Set a Different Cookie Time on Form Submission
URL: https://docs.wppopupmaker.com/article/83-set-a-different-cookie-time-on-form-submission

Article (2): Create Cookie On the Click of an Element Within Your Popup
URL: https://docs.wppopupmaker.com/article/230-create-cookie-on-the-click-of-an-element-within-your-popup

Link: Within the section ‘Setup Your Cookie’ of both articles, the link to the Popup Editor points to a dead URL. The correct URL should be:

>https://docs.wppopupmaker.com/article/485-the-popup-editor-introduction

======================================================

Collection: Product FAQs
Category: Compatibility

Article: Are Popups Responsive
URL: https://docs.wppopupmaker.com/article/188-are-popups-responsive

Link: In the section ‘Non-Responsive Popups’, see ‘Related Article: ’Display — Size’ option settings. 

Change the Link name to: ‘Display’ option settings // Size setting
Change the link URL to: https://docs.wppopupmaker.com/article/454-popup-settings-box-display-option-settings

======================================================

Collection: Extensions
Category: Remote Content

Article: Remote Content -- Set Up A Remote Content Popup
URL: https://docs.wppopupmaker.com/article/284-remote-content-set-up-a-rc-popup

Link: (1) First paragraph, link text is 'Click Trigger'; (2) Section 'Using Load from an iFrame', item (2), link text is 'set up a Click Trigger'. 

Change the link URL for both links to: https://docs.wppopupmaker.com/article/395-trigger-click-open-overview-methods

Collection: Extensions
Category: Remote Content

Article: Remote Content -- AJAX Type Introduction
URL: https://docs.wppopupmaker.com/article/33-remote-content-ajax-type-introduction

Link: Section 'Target Your Front End Element(s)'. The link text is 'Click Trigger' 

Change the link url to:  https://docs.wppopupmaker.com/article/395-trigger-click-open-overview-methods

**Comment by fpcorso** [comment]
Moving this to our documentation project in Asana
