### ISSUE TITLE
Simplify Onboarding/Creating Popups For New Users

### ISSUE THREAD

**Issue by fpcorso** [PopupMaker/Popup-Maker#693]
We have a lot of great features and advanced settings throughout the plugin. But, they can feel overwhelming and confusing to people who just installed PM for the first time. We are looking to explore ways to simplify this process. This issue will serve as organizing these thoughts together.

The focus here is to get first-time users to have a completed first popup as quickly as possible and as easily as possible.

Includes:
- [x] #728
- [x] #801 
- [x] #710  
- [ ] #449 
- [ ] #686 
- [x] #743 
- [ ]  #810

**Comment by danieliser** [comment]
@fpcorso I'm trying to find the name of the library that WP core includes, but we should also add the guided tour functionality. There is a lib in core that lets you add a multi step popover that points to elements on the page and overlays the rest to make a focus on that highlighted element with a popover that has next/prev buttons.

A guided tour using that or another 3rd party library would probably solve a lot of support issues by pointing them at the targeting options, creating triggers & cookies etc.

**Comment by danieliser** [comment]
Ahh here it is: https://code.tutsplus.com/articles/integrating-with-wordpress-ui-admin-pointers--wp-26853

The Admin `wp-pointer` library, not a lot of docs out there on this one but it does exist :)

**Comment by fpcorso** [comment]
I am going to convert this to a GitHub project now that we are using those more.
