### ISSUE TITLE
Put the jquery for the admin bar tools into a file enqueued

### ISSUE THREAD

**Issue by viscosho** [PopupMaker/Popup-Maker#695]
Hi!

I have a request/suggestion: Could you put the jquery for the admin bar tools into a file enqueued, this should be useful for deferring.

Thanks

**Comment by danieliser** [comment]
@viscosho - Clarifying, are you asking to move them into an actual external file rather than inline? I think that's feasible and probably best.

**Comment by viscosho** [comment]
@danieliser yes that is correct,  move them into an external file, and not be inline.
Thanks for quickly responding. If this is something that you consider to implement relatively soon I'll be happy to hear about it.

**Comment by danieliser** [comment]
@viscosho - It's definitely doable. I can't say when it will get done exactly though, our next release has a ton of planned changes already. Will have to see.

**Comment by viscosho** [comment]
Hi, is there any change for this to happen on the next release? Or this is still not in the next plans?
Thank you

**Comment by fpcorso** [comment]
@viscosho We are just starting to scope out priorities for the next minor version (1.11.0). I have temporarily added this issue to that milestone so we can include it when we are reviewing. Can't say for certain yet if it will make it in until we finish scoping out the release.

**Comment by fpcorso** [comment]
The CSS and JS has been moved to external files in a recent commit in `develop`. This will be included in our 1.11.0 release!
