### ISSUE TITLE
Opening Popup Sound

### ISSUE THREAD

**Issue by fpcorso** [PopupMaker/Popup-Maker#701]
I think adding an option to play a sound when the popup opens would help pull site visitor's attention to the popup.

I think it should come with a default sound and then also have the option for the site admin to upload their own sound.

How this is currently set up in Ahoy:
Admin: https://github.com/JunglePlugins/Ahoy/blob/f23d3492c3e8a26ab36777febf56c510fd2a84da/classes/Admin/Messages.php#L222
Frontend loading:
https://github.com/JunglePlugins/Ahoy/blob/b893a240537c2aac8bda7be3a109301284fb96b7/assets/js/ahoy-site.js#L754
Frontend playing:
https://github.com/JunglePlugins/Ahoy/blob/b893a240537c2aac8bda7be3a109301284fb96b7/assets/js/ahoy-site.js#L844

**Comment by fpcorso** [comment]
@danieliser A couple questions/thoughts as I start to map this one out.

Where in the popup editor does an open sound option make sense? Definitely not triggers, conditions, or close. I wouldn't consider the sound feature as advanced. So, maybe in the "display" tab?

Also, do we want to have just the URL box with a single default sound or should we have a dropdown with multiple options including an option for "custom" which would open the URL box for the admin to add their own sound too?

Should we also add an option to turn on or off the sound being played then since they may have a sound in the URL but want to turn it off/on?

Over in Ahoy, we were thinking of defaulting the sound to on but I am not sure how that works with PM. Maybe, default it to off here? But, if it is in "display", it could be part of the presets so we could have the sound default to on for slide-in but off for main popups.

**Comment by danieliser** [comment]
@fpcorso - It could be generally time to look at reorganizing in general. Its pretty easy these days, just move some array keys around.

That said, i'd say it would either fit best currently under the first tabs advanced section or a new tab under display for "Sounds" or put it under the Animation section as the sound could percievably be tied to animation duration.

#### Interface
I agree, do a select box with presets, and the final option would be `Custom`, then have a text field that accepts a url that shows up when they choose custom.

#### No option to disable
No need to add an option to turn it on/off. Make the first option in the select box "None / Choose One" so that setting it to off is as simple as changing it to None.

Since field dependencies only show/hide fields, the custom url would still persist on saving, but would be hidden.

#### Default to off
From there we can add it set to on in our new presets based on the use case.

**Comment by fpcorso** [comment]
@danieliser The "None" option in the drop-down makes sense.

Should we have a custom option to start with? At least with our included ones, we can test and make sure the format/encoding works across browsers. If the admin can add their own, it may lead to support tickets when they aren't using a good format or encoding.

I don't see having a whole "Sounds" tab with only one option on it but I don't think it would be too discoverable under "Animation". I wonder if, when we add the closing animation options #393, if we would add those to the current animation or if we would end up with a group of settings for when a popup opens and a group of settings for when the popup closes. Maybe the group of settings for when the popup opens would include open animations and sounds.

**Comment by fpcorso** [comment]
Also, for popups set to auto-open and may open before the site visitor interacts with the site, the sound may not play due to autoplay restrictions in browsers. Right now, I have that logged to the console when that happens so people debugging would see it. Should we also have some info on the autoplaying restriction somewhere near the option or in the docs?

**Comment by danieliser** [comment]
@fpcorso - See the docs for Ahoy: https://docs.useahoy.com/article/500-message-settings-sounds

Already accounted for there.

**Comment by fpcorso** [comment]
@danieliser ??? I have read those docs and re-opened them now. I don't see how that link addresses either of my previous questions.

**Comment by danieliser** [comment]
Should we have custom to start with, probably yes as its simple as adding an extra field really. Up to them to make sure they get the right sound. We can point them to free resources though like we already do in Ahoy.

The only other question I see references should we have notice about autoplay policy, in which case that doc does mention it.

The sound should be a progressive enhancement, it should never cause the trigger to delay etc. If the sound isn't ready then we simply skip it. Better to show it on time than to delay for a sound.

**Comment by fpcorso** [comment]
@danieliser Did you give any thoughts to my question above about where the sound setting should go? I have a paragraph in a previous comment about some thoughts on it but I need to know where to put it before I can move forward with this one.

**Comment by danieliser** [comment]
@fpcorso See my first response:

> i'd say it would either fit best currently under the first tabs advanced section or a new tab under display for "Sounds" or put it under the Animation section as the sound could perceivably be tied to animation duration.

Honestly at this point if you can't find a place for it, you need to create one. It likely also means we can rethink and reorganize other settings at some near point in the future to make more since.

**Comment by fpcorso** [comment]
@danieliser Well, I was specifically asking about a re-organization with putting opening events together in a tab (e.g. opening animation, opening sound, etc...) but we can worry about that in a future update I guess.

No worries. I'll put it under a "Sounds" tab for now then.

**Comment by fpcorso** [comment]
@danieliser For the sounds, should I only get CC0 or could we use some that are CC with attribution? If attribution ones are okay, where would we put the attribution? I found a bunch of great sounds on this site but it's CC with attribution: https://notificationsounds.com/. I didn't really care for all the ones in the Ahoy docs but will use a couple from that site (https://freesound.org) but would love to have a few better ones if we can find them.

Also, I think storing them in a /assets/sounds makes sense. Does that work for you?

**Comment by danieliser** [comment]
@fpcorso really? I didn't find any just now on that site that actually sounded the part of an onsite notification. Most that were about the right length/sound also had reverb & echo which is highly out of place in this context.

Do you have some specific ones? Either way we have no way of giving credit for each use, best we could offer is mention in our docs and maybe a comment in the code. Anything else would violate wordpress.org guidelines likely.

Maybe no attribution is best.

Also I found a few of those on freesound.org, but the rest were recommended by multiple users to add to the list. PS none had reverb or echo either haha. Sometimes less fancy is better?

**Comment by fpcorso** [comment]
@danieliser Okay, I'll hunt down some CC0. Unfortunately, about half the ones in the Ahoy docs require attribution so I'll have to grab a few more. The feature itself is just about finished once I find a few sounds. How many should we aim for? 4 or 5 work?

**Comment by fpcorso** [comment]
@danieliser Found 6 that might work that are CC0. I just realized that I don't have a way for the user to hear the sound without previewing the popup. Should we have the sound play when they select it in the dropdown for the sound setting?

Here are the sounds I am considering. Let me know what you think:
https://freesound.org/people/pan14/sounds/263133/
https://freesound.org/people/PaulMorek/sounds/330046/
https://freesound.org/people/TheAtomicBrain/sounds/351879/
https://freesound.org/people/ertfelda/sounds/243701/
https://freesound.org/people/paep3nguin/sounds/388046/

**Comment by danieliser** [comment]
@fpcorso I like the idea of it playing as they switch. Make sure you bind the event using `$(document).on()` as the form can be re rendered potentially.

**Comment by fpcorso** [comment]
Merged into `develop`!
