### ISSUE TITLE
Update menu editor walkers for latest compatibility fixes.

### ISSUE THREAD

**Issue by danieliser** [PopupMaker/Popup-Maker#702]
Nav Menu roles and Menu Icons plugins have both updated with a new version of these walker classes to fix issues in latest versions of WP. Need to merge in those changes as well. Simplify where possible.

- [ ] Update docs on usage of these classes: https://docs.wppopupmaker.com/article/297-popup-maker-is-overwriting-my-menu-editor-functions-how-can-i-fix-this

**Comment by fpcorso** [comment]
@danieliser Didn't you already update these some time last year or earlier this year or was that something different?

**Comment by danieliser** [comment]
@fpcorso Either that or just patched for WP 5.4+ support when they changed the walker officially.

But checking just now they do appear to both have been updated the same time, likely put this issue here to track those changes and just never closed it appropriately.

![image](https://user-images.githubusercontent.com/847818/94947659-02099300-04ac-11eb-82ba-3d81e12942ec.png)
