### ISSUE TITLE
Add better explanation of cookies in the Add Trigger modal.

### ISSUE THREAD

**Issue by danieliser** [PopupMaker/Popup-Maker#710]
Add more explanation and link to docs in the Add Trigger modal about why you would add cookies.

**Comment by fpcorso** [comment]
@danieliser  I wonder if we should reword the initial cookie options like this and then add a link at the bottom of that first modal:
![image](https://user-images.githubusercontent.com/9730040/81865938-80d15400-953c-11ea-8138-0719fe1ec29d.png)

**Comment by danieliser** [comment]
@fpcorso i like it.
