### ISSUE TITLE
Automate Development Tasks

### ISSUE THREAD

**Issue by danieliser** [PopupMaker/Popup-Maker#711]
The new Github actions system has prompted some new automation potential for us.

This serves as a master list of all possible process automations we can implement for Popup Maker, and eventually the other plugins.

Inspiration: https://10up.com/blog/2019/wordpress-github-actions-streamline-plugin-deployment/

10up Actions: https://github.com/10up/actions-wordpress

- [x] [Automated testing of Tested Up To version and issue creation](https://github.com/marketplace/actions/wordpress-version-checker)
- [ ] [POT generation](https://github.com/marketplace/actions/wp-pot-generator)
- [ ] [Text Domain auto generation](https://github.com/marketplace/actions/wp-textdomain)

**Comment by fpcorso** [comment]
@danieliser For the "POT generation" workflow: Do you still want to move that to a workflow as opposed to local build script? If so, should we have that run on pushes to a `release/**` branch, or can you think of a better event for that one?

**Comment by danieliser** [comment]
@fpcorso we may need to see if this is even necessary. For the core plugin I'm pretty confident that wordpress.org 
1. detects a new version tagged.
2. uses an automated scanner to extract gettext strings from filed directly
3. Populate GlotPress with the extracted text.
4. Once translated a langpack is generated and delivered via WP auto updates.

I don't believe that core .pot or .mo files ever are used these days. Likely could look to just remove them and the need for this.

Extensions on the other hand are translated via our own private glotpress install & the trudatore framework. I do believe it mimics wordpress.org in that it pulls directly from out github when there is a new version to populate strings. Once translated it generates langpacks and sends them via auto update.

That said the extension Activator/Updater classes need updating to check our translate.wpopupmaker.com api and hook into the auto updater. Trudatore lib has example code and Ahoy is already set up that way so we can copy from either.

**Comment by fpcorso** [comment]
@danieliser What did we decide for these last two? Is this still needed or can I close this one?

**Comment by danieliser** [comment]
@fpcorso The last one would be nice, but its bad practice to not just put `, 'popup-maker'` explicitly in our gettext calls.

So yea we can scratch those 2 as both WordPress.org and our own glotpress installs pull directly from the code base.
