### ISSUE TITLE
PHP 7.4 compatibility

### ISSUE THREAD

**Issue by lkraav** [PopupMaker/Popup-Maker#720]
```
Deprecated: Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in wp-content/plugins/popup-maker/includes/modules/reviews.php on line 298
```

**Comment by danieliser** [comment]
@ikraav - Fix is already committed 4d94663. Will be in v1.9

We are working to get v1.9 ready for beta.

**Comment by lkraav** [comment]
Is it me, or is https://github.com/PopupMaker/Popup-Maker/commit/4d946639e11dbfa6d7ae686240752e1493ffca3a a big whitespace error?

**Comment by danieliser** [comment]
@lkraav - Not that I can see, have debugging on, just checked out commit and running fine for me. I did find another similar warning as I tested the commonly used screens which I patched above.

Check your logs, see if you are getting some other errors on top of this one. That said I'm testing with 7.4 already with the above commit, everything activated fine.

**Comment by lkraav** [comment]
No I meant the indents are completely off on that commit, like it's not been through a linter?

**Comment by danieliser** [comment]
@lkraav I see what you mean, spaces rather than tabs. @fpcorso likely needs to update his IDE settings, but it will get corrected at release time either way.

**Comment by lkraav** [comment]
:+1: perhaps time for `.editorconfig` in repo root + `eclint`?

Some example rolls:

https://github.com/web-padawan/aybolit/pull/23/files
https://github.com/web-padawan/aybolit/pull/34/files

**Comment by danieliser** [comment]
@lkraav Way ahead of ya: https://github.com/PopupMaker/Popup-Maker/blob/develop/.editorconfig

Was actually added in February, but we changed branching methodologies and the branch it was on got left behind. Just remerged it all recently.

So I'm not sure if he was working on that branch or if his PHPStorm simply didn't have editorconfig enabled yet. I had to enable it via a plugin I believe.
