### ISSUE TITLE
Display Preset Switcher

### ISSUE THREAD

**Issue by fpcorso** [PopupMaker/Popup-Maker#728]
This new "template changer" would be a new first tab in the "Display" settings for each popup. By clicking a different template, the system would pre-fill in the display settings to best achieve that template.

For example, if the user clicked "Slide-In", it would switch "Display" -> "Position" -> "Location" to the correct location and modify the other settings for best defaults for slide-ins.

A quick example sketch would look like this:
![first-draft-template-switcher](https://user-images.githubusercontent.com/9730040/72088680-aa514900-32d8-11ea-8d07-e286df656f5c.png)

But, instead of text, or in addition to text, maybe we have a small graphic/image that represents what that preset does. 

Then, have a "custom" one that gets switched to once they start adjusting settings or switching to the custom theme they created.

Some of the most used templates we should include would be options for:

- [x] Popup, obviously
- [x] Slide-in
- [x] Top bar (i.e. hello bar)
- [x] Some sort of "notice" like template similar to the cookie notices that appear in one of the site's corners

Depending on which templates we decide in the final version, we may need to draft a few new default popup themes to be able to achieve the new default templates.

**Comment by fpcorso** [comment]
The final version would probably be mirrored or very similar to one of the steps we may create in the Popup Wizard for #686

**Comment by fpcorso** [comment]
I'll start mapping out which settings/theme are selected with which template so we can start moving forward with this one.

**Comment by fpcorso** [comment]
For the default, we will naturally keep a "center popup" preset with something such as:

Popup
Appearance: Default Theme
Size: 60% 0 min 100% max
Animation: Fade 350ms
Position: Middle Center
Advanced: All unchecked.

**Comment by fpcorso** [comment]
For the "notice", maybe a bottom left message:

Appearance: Cutting Edge or a new theme
Size: 30% 0 min 100% max
Animation: Slide 350ms Left
Position: Bottom-left 10px 10px
Advanced: All unchecked.

which creates something like:
![image](https://user-images.githubusercontent.com/9730040/73481637-38fe3680-436a-11ea-97be-8b25a65bc0d2.png)

**Comment by fpcorso** [comment]
For the top bar, we will need a new popup theme to get it right:

Appearance: New popup theme that is wide and minimal padding
Size: Custom -> 100% Auto-height
Animation: Fade and Slide 350ms Top-Center
Position: Top-center 0px Fixed Positioning checked
Advanced: Disable overlay checked

Will create something like this:
![image](https://user-images.githubusercontent.com/9730040/73484788-ef184f00-436f-11ea-83ea-d10db8c45dec.png)

**Comment by fpcorso** [comment]
@danieliser Looking at the code to start identifying steps to build the actual process, I see that the settings are saved on the save_post hook in the PUM_Admin_Popups class here: https://github.com/PopupMaker/Popup-Maker/blob/master/classes/Admin/Popups.php#L262

To save them, they are loaded from the $_POST index here: https://github.com/PopupMaker/Popup-Maker/blob/master/classes/Admin/Popups.php#L249

Most of the fields are set to popup_settings[FIELD_ID] here: https://github.com/PopupMaker/Popup-Maker/blob/master/classes/Admin/Popups.php#L746

So, could the display switcher then just update the values in fields across display tab? Everything else will work as-is since the plugin handles generating the fields and saving them.

For example, if someone clicked on the "top bar" preset, it would run through some function that updated each of the fields across the display tab to match whatever values we enter into the preset.

Is there a different or better way we should handle it? We probably want the presets in some sort of standalone module/array so we could re-use it in the eventual popup wizard we want to create or for us to even build on top of to create a bigger overall template/prebuilt popup system.

**Comment by fpcorso** [comment]
Also, @danieliser in addition to the questions above, how many presets are a good number to launch with? 4 or 5? I wouldn't want to go crazy and design 12 of them and then have a lot of debugging and documentation to write as soon as it launches but I want enough to show some variety in use-cases.

**Comment by danieliser** [comment]
@fpcorso - 4-5 is probably sufficient.

You can either update fields by name manually, or you can do what I mentioned before:

1. Get object in JS containing current form values.
2. Merge in the preset values.
3. Redraw the form replacing the existing one entirely.

Probably the simplest and most reliable as it relies on the form renderer to handle everything except merging field values.

**Comment by danieliser** [comment]
@fpcorso Here is how the form is rendered.

https://github.com/PopupMaker/Popup-Maker/blob/master/classes/Admin/Popups.php#L158

**Comment by fpcorso** [comment]
@danieliser That array appears to include all settings including conditions and targeting. Is there a way to just merge into the display settings and redraw only that? Is the JS object as people update conditions and other settings? If we redraw all of the forms, will it overwrite any other changes they were working on but haven't saved yet?

**Comment by danieliser** [comment]
1. Will it overwrite their other changes: not the way I described. First you would collect current field values, then merge in the new presets, then redraw with them.

2. Sorry that link was wrong place. That link shows what we pass for all of it. The form renderer only takes the form_args & current_values.

Here is the actual form rendering using those values: https://github.com/PopupMaker/Popup-Maker/blob/master/assets/js/src/admin/popup-editor/general.js#L20-L27

So in your case, you would merge those same passed current values, with values of the form now, with presets being merged.

    values = Object.assign({}, pum_popup_settings_editor.current_values || {}, $container.find('form').pumSerializeObject(), new_preset_display_values );

Then you would redraw the form with that:

            var $container = $('#pum-popup-settings-container'),
                args = pum_popup_settings_editor.form_args || {},
                values = Object.assign({}, pum_popup_settings_editor.current_values || {}, $container.find('form').pumSerializeObject(), new_preset_display_values );;

            if ($container.length) {
                $container.html(''); // Clear it out (this may not be needed, test without it).
                PUM_Admin.forms.render(args, values, $container);
            }

**Comment by danieliser** [comment]
@fpcorso For this one, should we show a toggle to see what will actually be changed?

A confirm modal with something like this would be ideal:

```
The following changes will be made:

- Size: Custom
- Width: 100%;
- Position: Top
- Animation: Slide Down
- Animation Origin: Top Center

[ Cancel ]                   [ Confirm ]
```

**Comment by danieliser** [comment]
We could add a "Do not show this again" which would just make them auto apply in the future if need be as well.

**Comment by fpcorso** [comment]
@danieliser Do you have thoughts on where we should keep/load the preset values from? Since we will probably re-use these values in the eventual popup creation wizard and some other potential places, we need it somehow accessible/exposed. We could have them as objects/arrays in the JS files. Or, we could have them as JSON files that we load from.

We could have these as options/meta in the DB too but that doesn't seem like a good option for our current plans for the preset data.

**Comment by danieliser** [comment]
@fpcorso Did you see #749, I think a format like JSON is ideal for this. We need a quick mechanism that puts $popup->get_settings() into a JSON string and then we can export/import from there.

**Comment by fpcorso** [comment]
@danieliser Not entirely sure how #749 is related as we were discussing where to store the presets.

If we went down the JSON files route like we discussed, should we have a separate folder called `presets` or `templates` that we keep them in?

**Comment by danieliser** [comment]
It is related in that both will use the underlying import/export from JSON source. So the structure under the hood needs to be built to handle both cases as well as being able to 1 click import from themes.wppopupmaker.com for popup_theme post types.

I like the idea of files, but that seems overly impactful. May be simpler to do it in a PHP array for now. Look at how the themes we include are handled.

There are multiple themes listed in an array, each has a serialized string of popup_theme_settings meta data.

I'm open to whatever, but I think a json file would be ideal as its easily portable, usually easy to read at a glance etc.

**Comment by danieliser** [comment]
We already have a templates folder, so I'd say maybe either

`presets/popup/slide-in.json`

or 

`configs/presets/popup-slide-in.json`

Further each needs to have some meta data like version.

**Comment by fpcorso** [comment]
@danieliser, what are your thoughts on the name of the tab for the display switcher? I agree with your earlier comment about "Template" makes it seem like it does more than it does. I am not too sure "Presets" quite fit and not sure if all new users would understand that.

What about "Type" as in "type of popup"?
![image](https://user-images.githubusercontent.com/9730040/77350471-f24a0e80-6d12-11ea-971b-fbd659edc5ef.png)

**Comment by fpcorso** [comment]
@danieliser, in addition to the heading question above, here is what I am thinking for the actual UI. Of course, instead of the PM logo, each would have some diagram or representation of what it would look like. Any thoughts on this direction?

*styling is only dummy styling and would, naturally, be tweaked to match the rest of the UI design

![image](https://user-images.githubusercontent.com/9730040/77351616-66d17d00-6d14-11ea-9d90-696b8aed4205.png)

**Comment by fpcorso** [comment]
@danieliser , in addition to the two previous questions, I have two more:

1. Is there any existing functionality for switching tabs dynamically? When I re-render the popup settings, it jumps back to the "Targeting" tab and I need it to go back to the "Display" tab so it's not quite as jarring to the admin. I am looking through forms.js now and don't see anything that would work. I didn't want to build anything if it already exists.

2. For the presets, we wanted to also switch the themes so we can select themes that best fit the type. For example, for the top bar, we wanted one with slimmer designs with a much smaller close button in a different location. My question is: Since the themes are inserted, they will always have different theme ID's. And, the admin could rename or even delete any of the included themes. What do you think is our best option here? 

We do have the list of theme_id's and names in the popup_settings in the popup editor. So, I could check in the list for one that matches the name of what I want and not make a theme change if it is not found. For example, if I wanted the "Cutting Edge" for the cookie notice, I could check the list of the themes for Cutting Edge and then (if found) add that theme's ID to the preset value before re-rendering the field. Any thoughts on this strategy?

**Comment by danieliser** [comment]
@fpcorso - I don't know if `Type` is appropriate either. It might fit later when popups become Campaign with type=popup, but even then it may not make since once we add all the options I could imagine working well.


I do think `Preset` actually makes most since here. But it might make even more since to call it `Display Presets` as that is more precise for the time being. Later when we put it into a bigger wizard it can be relabeled.

For styling, what do you think about the images used in Ahoy for the "Type" field? Flat vectors essentially that show what to expect with simple text below the image?

I can create some templates to make them in Adobe Photoshop or Adobe XD for that.

**Comment by fpcorso** [comment]
@danieliser, hmmm... I still don't think "Display Presets" conveys to the end user who is not familiar with PM the right message. But, if that's what you would prefer, I'll go with that for now then.

For the styling, as I mentioned in my earlier comment, yes I would want to use diagrams of what the UI would look like similar to Ahoy. However, what I think is better to also have a label of text describing the UI which doesn't exist in Ahoy unless you click on it. That won't work if we have 10+ presets which is why I was asking about the UI and had an example in a previous comment.

**Comment by danieliser** [comment]
1. My inline code comments mentioned just manually using .click() on the display tab after re-render as a temporary solution for now.

We need to address this long term with localStorage and extra args you can pass into the form to change tabs on re-render.

2. I don't see it working honestly. First they can delete them or worse adjust them making them no longer suitable for the purpose, and we would still try and use that on new popups.

I'm not sure it makes since to do this from that perspective.

Alternatively we could:
a) leave that out for now.
b) include a few new default themes properly named to their use cases.
c) add a lock to default themes making them uneditable.

I'd say leave it out for now.

Something we might end up visiting in the near future as we replan this thing is that we may just do away with popup_themes and move that info into the campaign display settings outright. Meaning that Display Presets could just overwrite those theme options as well.

Currently I don't think there is an ideal solution, so it may be best to just skip changing theme for now and use this as a step 1 to a larger vision..


----

Side note about the labels in ahoy. Those are actually not option labels at all. Those are dynamic descriptions of the current radio field.

By default each field gets one description `desc` key in the array. Using dynamic descriptions allows you to adjust the description based on the chosen option to provide more detail.

We are likely just hiding the actual option label with CSS in the case of Ahoy. The code to set up a field like that would be the same though.

**Comment by fpcorso** [comment]
@danieliser , yeah, your thoughts on the theme being included in the switcher makes sense. It is unfortunate though as our existing themes don't really do well for some of the spots we included so I wanted to be able to help them "envision" the outcome quicker by automatically switching the theme to one designed for that location. 

But, we can skip that part for now. Maybe, we limit this scope to what I have (after fixing/improving the other things we already discussed) and plan on creating some new appropriately named themes soon to help them know to choose them. But, for automatically switching, I agree that there may not be an easy path to do that right now.

If you have time, do you want to whip up the flat vectors for the different presets in Photoshop/XD as you mentioned? I don't currently have an active Adobe subscription and also have never created anything like those before.

**Comment by danieliser** [comment]
@fpcorso The easy solution might come after we merge the theme editor into the popup editor.

If we keep popup_theme_settigns separately saved than the normal popup_settings, but maintain them in a single editing experience, we can switch/save themes separately from functional settings.

**Comment by fpcorso** [comment]
@danieliser, you might have missed it within the long comment, but I asked about the flat vectors in my previous comment. Would you be able to whip those up for these initial 4 presets?
