### ISSUE TITLE
Add in functionality for Prebuilt Popups

### ISSUE THREAD

**Issue by danieliser** [PopupMaker/Popup-Maker#73]
Should detect and show a Prebuilt popup selector when creating new popups, and a metabox with dropdown for editing existing.

Prebuilts will allow predefined settings to popuplate all fields.

Theme editor may also get this functionality allowing prebuilt themes to be edited and customized.

Also need to add functionality for including prebuilt themes when Unlimited Themes is not available.

Consider adding unlimited themes to the core.

**Comment by fpcorso** [comment]
@danieliser This issue has lots of different things added to it and I think we have other issues created for each of these ideas. Can I close this one out?

**Comment by danieliser** [comment]
@fpcorso Yea when triaging issues, try to keep the older ones in case of duplicates. But here if we have new issues that cover some of these, be sure to copy any relevant details from here to those issues and create new issues for anything here that isn't already covered before closing this one.

Another option is to convert this to a larger issue or epic and link the other issues to it.

Fine either way as long as all the ideas are still in the system.

**Comment by fpcorso** [comment]
All of these ideas/topics are now accounted for in other issues. Closing this one.
