### ISSUE TITLE
Research & plan automated testing approaches

### ISSUE THREAD

**Issue by danieliser** [PopupMaker/Popup-Maker#731]
- [ ] Linting / Code Inspection - #822 
- [ ] Unit Testing - #563 
- [ ] Acceptance testing - #671

**Comment by fpcorso** [comment]
@danieliser I am going to break each of the main "sections" into their own issues so we can tackle this one-at-a-time but keep this main issue to tie them together.

**Comment by danieliser** [comment]
@fpcorso awesome, do you want to define this as a new "Project" to keep them organized. I believe that can be considered similar to an Epic before.

**Comment by fpcorso** [comment]
@danieliser I was originally planning to keep this issue as the way to organize them all but I like your idea of using "projects" here as we don't utilize that enough. I'll use that this time to see how we like it.

**Comment by fpcorso** [comment]
Moved these over to our Automated Testing project. Closing here.
