### ISSUE TITLE
Explore use of CSS animations

### ISSUE THREAD

**Issue by danieliser** [PopupMaker/Popup-Maker#737]
Explore the use of CSS animations for our elements:
- [ ] https://codepen.io/FlorinPop17/pen/drJJzK
- [ ] https://codepen.io/seansean11/pen/dhwzj
- [ ] https://dev.to/webdeasy/top-20-css-buttons-animations-f41
- [ ] https://codepen.io/donovanh/pen/QwdMKN
- [ ] https://salferrarello.com/css-pulse-animation/

**Comment by fpcorso** [comment]
@danieliser Is this a duplicate of #639? Should I close that previous one?

**Comment by danieliser** [comment]
Or we can just merge the above examples into that one would probably be better.
