### ISSUE TITLE
PHP Notice: Undefined index: HTTP_ACCEPT_LANGUAGE

### ISSUE THREAD

**Issue by danieliser** [PopupMaker/Popup-Maker#741]
PHP Notice: Undefined index: HTTP_ACCEPT_LANGUAGE in /home/sparka11/public_html/wp-content/plugins/popup-maker/classes/Utils/I10n.php on line 158

I'm running WordPress 5.3.2 & PHP 7.3.7

https://github.com/PopupMaker/Popup-Maker/blob/master/classes/Utils/I10n.php#L158

Adding a simple `( isset( ) ? : )` should work fine here.

    ​if ( preg_match_all( "/$locale_re/i", isset( $_SERVER['HTTP_ACCEPT_LANGUAGE'] ) ? $_SERVER['HTTP_ACCEPT_LANGUAGE'] : '', $matches ) ) {

**Comment by fpcorso** [comment]
While most browsers send over an Accept-Language header in the HTTP request, not all do all the time depending on user settings. Additionally, search engines and other crawlers also do not which would all lead to the HTTP_ACCEPT_LANGUAGE index to not be set.

Surprised we have not encountered this before.

**Comment by fpcorso** [comment]
@danieliser I have committed the change. When you have a moment, can you verify that it fixed the error within your test site so that I can close this?

**Comment by danieliser** [comment]
Looks good.

**Comment by danieliser** [comment]
@fpcorso make sure you add the fix to the readme changlog & CHANGELOG.md.

**Comment by fpcorso** [comment]
@danieliser Done
