### ISSUE TITLE
Merge Block Functionality

### ISSUE THREAD

**Issue by fpcorso** [PopupMaker/Popup-Maker#742]

**Comment by danieliser** [comment]
@fpcorso The block playground is currently built on a completely different set of build tools, need to work out the best way to mix/merge them.

That is arguably the hardest part of this endeavor.

**Comment by danieliser** [comment]
Proposed changes currently stand at:

1. Add new /src & /dist directories for assets going forward. Will take time to move them all there officially, but we gotta start somewhere and doing it for the entire plugin at once will likely be too large a single undertaking, so we will be utilizing multiple directories until completely migrated. This also serves to show us what code hasn't been updated yet in the old directoy.

2. Update npm package requirements, will add a bunch of new stuff, and slowly remove old stuff as the older code is dissolved into new code over time.

3. Add new classes & methods in PHP to register everything and kick it all off properly.

4. Find a way to run all build tools from one command still, new stuff will run from npm directly replacing need for gulp in most instances, likely still need it for release and zipping etc.
