### ISSUE TITLE
Create system for guided tours of admin interface

### ISSUE THREAD

**Issue by fpcorso** [PopupMaker/Popup-Maker#743]
We've discussed in a few places about the possibility of adding a tour/popup guide of the interface for new users of the plugin.

For the popup editor tour, we discussed having:
1. Popup content
2. Popup triggers
3. Popup targeting
4. Popup display
5. Theme selector

Then, have a second tour when an admin adds their first trigger or condition to further introduce those more complex concepts.

**Comment by fpcorso** [comment]
@danieliser For this, how many should we aim for in the first tour of the popup editor? Maybe 5 for:

1. Popup content
2. Popup triggers
3. Popup targeting
4. Popup display
5. Publish button

**Comment by danieliser** [comment]
Short version:

1. Remove #5.
2. Add one specifically to introduce theme selector and link to edit.
3. Layer on a second tour when they add their first trigger or condition to further introduce those more complex concepts.

**Comment by fpcorso** [comment]
@danieliser For the popup editor tour, should we have a place that someone can retake the tour? We aren't diving too deep into any particular concept so I can't imagine anyone needing to or thinking to retake the tour.

If we do add a way, where should that button be? Somewhere in the Popup Settings section or on a different screen?

**Comment by danieliser** [comment]
@fpcorso - Help & Support or Screen Options tabs near top come to mind.

**Comment by fpcorso** [comment]
@danieliser This is currently what I have for the main tour text. Let me know what you think:

### All Popups Pointer
Welcome to Popup Maker!
Click the "Add New Popup" button to create your first popup.

### Add Popup Tour
Popup Content
Add content for your popup here.

Popup Triggers
Use triggers to set what causes the popup to open.

Popup Targeting
Use targeting to set where on your site the popup should load and who to show the popup to.

Popup Display
Use display settings to set where on the screen the popup appears and what it looks like.

Popup Theme
Choose the overall theme for the popup which controls the colors, spacing, and fonts of the popup.

**Comment by danieliser** [comment]
@fpcorso - Should we add one before Popup Content for Popup Name?

Maybe use the word `choose` instead of `set`.

And

**Comment by danieliser** [comment]
@fpcorso That looks awesome, my only criticism would be there is no escape button. Do we have a way to offer a dismiss on the first so they don't see the rest?

**Comment by fpcorso** [comment]
@danieliser Added a skip tour button for when there is more than one pointer queued for a page:

![image](https://user-images.githubusercontent.com/9730040/83903518-466a6980-a72c-11ea-857c-00b58657d67c.png)
