### ISSUE TITLE
Form Integration: Formidable Forms

### ISSUE THREAD

**Issue by danieliser** [PopupMaker/Popup-Maker#750]
Plugin: https://formidableforms.com/

**Comment by fpcorso** [comment]
@danieliser Making progress on this one:
![formidable-forms-example](https://user-images.githubusercontent.com/9730040/90795332-e96a6280-e2db-11ea-9730-d8b81268a4d7.png)

But, can you point me to where the `pum_form_popup_id` is set? It shows in the CF7's on_success method but isn't set in the CF7's JS file: https://github.com/PopupMaker/Popup-Maker/blob/feature/750/classes/Integration/Form/ContactForm7.php#L94

Is that done automatically somewhere that I don't have to worry about?

**Comment by danieliser** [comment]
@fpcorso This should handle it: https://github.com/PopupMaker/Popup-Maker/blob/cf71d1c064c1fa6c37ce527150639fdc406b0051/assets/js/src/site/general.js#L46-L55
