### ISSUE TITLE
Add new minimal popup theme for page builders

### ISSUE THREAD

**Issue by danieliser** [PopupMaker/Popup-Maker#759]

**Comment by fpcorso** [comment]
@danieliser Can you provide a little more details here? What would this new theme be and how would it be implemented? Would the site admin need to do anything with these themes?

**Comment by fpcorso** [comment]
@danieliser What do you think a good name for this theme would be? I was originally thinking "Minimal" or similar but that could be confused with a normal minimal theme designed for normal popups. Probably want to make it clear that this popup theme is designed for content from page builders or similar systems.

**Comment by danieliser** [comment]
Yea I'm thinking name it Builder, or Page Builder, or maybe something generic like "Content Only"

**Comment by fpcorso** [comment]
@danieliser Should we explicitly state for use with page builders? Not sure "Content Only" or similar names will help people connect that they can use this theme with page builder content.

Something like "Content Only (For use with page builder content)"

**Comment by danieliser** [comment]
If you think it makes it more clear then sure.

**Comment by fpcorso** [comment]
@danieliser Can I get your thoughts on these questions:

1. Should all drop-shadow related settings for the container background be 0?
2. Should background opacity be 0?
3. Should we keep the overlay default at 100% still since they won't be editing the overlay in a page builder?
4. Should we adjust any of the title/content settings at all?
5. Should we adjust the close button settings?

I am assuming the answers to the first three are yes but wanted to double-check. For the close button, it seems weird to have a large green button floating there if we keep it the defaults but not sure what we'd change it to since they need to have a close button in the core version.

**Comment by danieliser** [comment]
1. Should all drop-shadow related settings for the container background be 0?

By default that would make it have no shadow, so yea, the page builder can do shadows on individual blocks, columns and rows.

2. Should background opacity be 0?

Either set it to 0 or set the background color to `''`

3. Should we keep the overlay default at 100% still since they won't be editing the overlay in a page builder?

IDK, the default likely shouldn't be 100% though, these days maybe 70-80% with a dark overlay like a light box etc.

4. Should we adjust any of the title/content settings at all?

Maybe set them all to `inherit`.

5. Should we adjust the close button settings?

Possibly to make sure it is decently contrasted on as many common colors as possible and maybe positioned ouside the popup slightly?

**Comment by fpcorso** [comment]
@danieliser Okay, adjusted everything and playing with the close button now. Here is a quick Elementor template I built with a border so I could see spacing around template in the popup.
![image](https://user-images.githubusercontent.com/9730040/90787956-47467c80-e2d3-11ea-95fe-cb5996ed9ee6.png)

For the close button, maybe something minimal like with our newer floating bar theme. In the screenshot, I currently have just a bold, black `&times;` close button. Not sure about defaulting with a border (round or square) as it's difficult to guess exactly what type of templates people would be using. 

I'm assuming there will be more squared popups so maybe a square border on the close button might be appropriate. As for inside or outside, I think more of the popups created usually have the close button inside the popup.

**Comment by danieliser** [comment]
Looks great, we might want to make the font size quite a bit larger by default, maybe even 2x what it is now.

Wonder if we should offer 2 versions: `Dark` & `Light`

**Comment by fpcorso** [comment]
@danieliser Just to clarify: You're saying to increase the font size of the close button, right?

As for the `Dark` and `Light`: What would be different between them other than only the close button?

**Comment by danieliser** [comment]
@fpcorso Yes I think its a bit small for common use cases & accessibility.

Correct, would just be the close button color really, but there is no easy way currently to change just that on a per popup basis. So if you had a dark popup and a light popup, you would need 2 themes.

Adding both by default means it should offer something for any site out of the box.

**Comment by fpcorso** [comment]
@danieliser I don't know. The majority of the time, they will only need one version. So, would it be better to just provide one, especially if they are nearly identical? They could edit the theme and change the close button, if needed.

It may be confusing to have to "Content Only" themes with one dark and one light. The admin wouldn't know what the differences were and would have to hunt down the documentation or test out both.

**Comment by danieliser** [comment]
Point taken, not sure the right answer, mainly because we have users who didn't know about the theme editor for years. Some still don't haha.

**Comment by fpcorso** [comment]
@danieliser Maybe a good first intermediate step is to just release the current "Content Only" I have and see if anyone even uses it. If we see it does gain traction, maybe we then plan on releasing a couple of different variations of it.

**Comment by danieliser** [comment]
Sounds good.
