### ISSUE TITLE
1.9.1: block editor 404 errors, `admin-editor-styles.css` missing `pum-` prefix

### ISSUE THREAD

**Issue by lkraav** [PopupMaker/Popup-Maker#762]
https://github.com/PopupMaker/Popup-Maker/blob/v1.9.1/classes/Admin/Shortcode/UI.php#L95 seems to be missing prefix vs https://github.com/PopupMaker/Popup-Maker/blob/v1.9.1/assets/css/pum-admin-editor-styles.css

**Comment by danieliser** [comment]
@lkraav Good catch, we will get that patched.
