### ISSUE TITLE
Close Button Appears Incorrect On Fresh Install

### ISSUE THREAD

**Issue by fpcorso** [PopupMaker/Popup-Maker#766]
When installing Popup Maker on a fresh install (WP site that has not had PM before), the close button does not appear in the correct location.

![image (1)](https://user-images.githubusercontent.com/9730040/77352068-faa34900-6d14-11ea-9d2b-b5842da94dd6.png)

This problem persists across all popups each time the popup opens until I edit the default theme and "Update" it. Even, if I make no changes to the theme. Once updated, the close button begins to show in the correct position.

![image (2)](https://user-images.githubusercontent.com/9730040/77352134-1dcdf880-6d15-11ea-92ca-0786d01f81c4.png)

**Comment by fpcorso** [comment]
@danieliser Debugged this a bit further.

I created a test popup on a fresh install. This issue occurred again. Looked at the CSS. The rules were coming from CSS that was outputted into the HTML head. But, the values in the default theme part are missing as shown in this screenshot:

![image](https://user-images.githubusercontent.com/9730040/77812755-de3b3f80-7079-11ea-9fb5-b832f3819d44.png)

I checked and the cache files are generated correctly when I saved the popup. The values for the default themes are correct in the cache file as shown in this screenshot:

![image](https://user-images.githubusercontent.com/9730040/77812799-22c6db00-707a-11ea-97f6-96ffb8ebdc65.png)

If I go and edit the Default Theme and update, even without making changes, the close button then starts appearing in the right spot. Upon viewing in developer tools, we can see the values are now correct as shown in this screenshot:

![image](https://user-images.githubusercontent.com/9730040/77812829-6883a380-707a-11ea-8109-2090d9bcc0d9.png)

Now, so there's two questions from this:
1. What could cause the default values to show as blank for the default theme but then get corrected when updating the theme? If the creation of the Default Theme had issues, it wouldn't show up over in the cache file as correct, right? So maybe something with the inlining of the CSS? But, those methods look fairly straight-forward so I don't see what could cause that issue there.

2. As an aside to this main issue, for some reason, my fresh installs do not load the cached file and only inlines the CSS as shown in the screenshots above. But, the cached files do get generated and regenerated correctly. They never show up in the `Network` tab of the developer tools, even trying to load them. The only reason those files wouldn't be registered is if the cache is disabled (it's not), if the files aren't writeable (which they are) or if the cache dir URL is false, which it shouldn't be. I'll have to debug each part of those functions then to make sure we don't have anything wrong. All of our asset cache and site assets methods seem right at quick glance.

**Comment by fpcorso** [comment]
@danieliser You can ignore the second question here. That was caused by an unrelated issue discovered and fixed.

However, after fixing the second issue, the original issue still remains. I did a fresh install using the updated code. Close button still appears in the incorrect place due to missing values. This time, the missing values are in the cache CSS as shown in this screenshot:

![image](https://user-images.githubusercontent.com/9730040/77813787-b5b74380-7081-11ea-9613-ae67156068cf.png)

I checked the defaults for the fields and all have correct default values. The `get_generated_styles` method for the theme appears to just bring in the settings which should be correct. I am unsure what else to debug/test.

**Comment by fpcorso** [comment]
It appears that this must be something happening when installing the default theme. On the fresh install, I checked the post_meta for the Default Theme to see the settings and, while the close location was correct, all the values were `N` as shown in this screenshot:

![image](https://user-images.githubusercontent.com/9730040/77814438-7ab80e80-7087-11ea-9e0e-6b8ae063e352.png)

**Comment by fpcorso** [comment]
@danieliser Can't quite figure out where the null/N values are coming from. When the plugin is freshly installed, the activate_site method is called:
https://github.com/PopupMaker/Popup-Maker/blob/master/classes/Install.php#L84

In there, the function `pum_get_default_theme_id` is called:
https://github.com/PopupMaker/Popup-Maker/blob/master/classes/Install.php#L112

Inside that function, if the default theme doesn't exist, which it doesn't upon fresh install, it calls `pum_install_default_theme` here:
https://github.com/PopupMaker/Popup-Maker/blob/master/includes/functions/general.php#L36

That function calls `pum_install_theme` with the second argument as `null`:
https://github.com/PopupMaker/Popup-Maker/blob/master/includes/functions/themes/portability.php#L61 

Passing `null` to that function sets the settings to the theme defaults here:
https://github.com/PopupMaker/Popup-Maker/blob/master/includes/functions/themes/portability.php#L15

The defaults method just returns the form field defaults:
https://github.com/PopupMaker/Popup-Maker/blob/master/classes/Admin/Themes.php#L1237

The fields being here:
https://github.com/PopupMaker/Popup-Maker/blob/master/classes/Admin/Themes.php#L458

In those defaults, close position top and right are both set to 0.

**Comment by danieliser** [comment]
@fpcorso - I wonder if `0` is the issue. Should it be be `'0'`?

I can take a look.

**Comment by danieliser** [comment]
@fpcorso This issue is in the fetching of defaults. I ran through it with xdebug on and this line comes back with close_position_top: 
```
		$settings = PUM_Admin_Themes::defaults();
```

The resulting $settings variable looks like this:

```
array (
  'overlay_background_color' => '#ffffff',
  'overlay_background_opacity' => 100,
  'atc_promotion' => NULL,
  'container_padding' => 18,
  'container_border_radius' => NULL,
  'container_background_color' => '#f9f9f9',
  'container_background_opacity' => 100,
  'container_border_style' => 'none',
  'container_border_color' => '#000000',
  'container_border_width' => 1,
  'container_boxshadow_color' => '#020202',
  'container_boxshadow_opacity' => 23,
  'container_boxshadow_horizontal' => 1,
  'container_boxshadow_vertical' => 1,
  'container_boxshadow_blur' => 3,
  'container_boxshadow_spread' => NULL,
  'container_boxshadow_inset' => 'no',
  'title_font_color' => '#000000',
  'title_font_size' => 32,
  'title_line_height' => 36,
  'title_font_family' => 'inherit',
  'title_font_weight' => 400,
  'title_font_style' => 'normal',
  'title_text_align' => 'left',
  'title_textshadow_color' => '#020202',
  'title_textshadow_opacity' => 23,
  'title_textshadow_horizontal' => NULL,
  'title_textshadow_vertical' => NULL,
  'title_textshadow_blur' => NULL,
  'content_font_color' => '#8c8c8c',
  'content_font_family' => 'inherit',
  'content_font_weight' => 400,
  'content_font_style' => 'inherit',
  'close_text' => 'CLOSE',
  'close_position_outside' => false,
  'close_location' => 'topright',
  'close_position_top' => NULL,
  'close_position_bottom' => NULL,
  'close_position_left' => NULL,
  'close_position_right' => NULL,
  'close_padding' => 8,
  'close_height' => NULL,
  'close_width' => NULL,
  'close_border_radius' => NULL,
  'close_background_color' => '#00b7cd',
  'close_background_opacity' => 100,
  'close_font_color' => '#ffffff',
  'close_font_size' => 12,
  'close_line_height' => 36,
  'close_font_family' => 'inherit',
  'close_font_weight' => 400,
  'close_font_style' => 'inherit',
  'close_border_style' => 'none',
  'close_border_color' => '#ffffff',
  'close_border_width' => 1,
  'close_boxshadow_color' => '#020202',
  'close_boxshadow_opacity' => 23,
  'close_boxshadow_horizontal' => 1,
  'close_boxshadow_vertical' => 1,
  'close_boxshadow_blur' => 3,
  'close_boxshadow_spread' => NULL,
  'close_boxshadow_inset' => 'no',
  'close_textshadow_color' => '#000000',
  'close_textshadow_opacity' => 23,
  'close_textshadow_horizontal' => NULL,
  'close_textshadow_vertical' => NULL,
  'close_textshadow_blur' => NULL,
)
```

A lot of null values there that shouldn't be null. Digging into that now.

**Comment by danieliser** [comment]
@fpcorso Found it

**Comment by danieliser** [comment]
@fpcorso Test it but its fixed for me.

**Comment by fpcorso** [comment]
@danieliser Was able to verify that this is indeed fixed.
