### ISSUE TITLE
Animation origin is not correct

### ISSUE THREAD

**Issue by fpcorso** [PopupMaker/Popup-Maker#773]
When setting up a popup that appears in the bottom right, we were trying to get it to slide in upwards, similar to an Ahoy message. However, setting the animation origin to "Bottom" or "Bottom Center" both have the popup slide in, diagonally, from the middle of the bottom of the screen as shown in this video:

https://www.loom.com/share/914eddc69bda4aac8a72ac95252b3f33

**Comment by danieliser** [comment]
@fpcorso I duplicated it last night. Decided it wasn't like that before (We have `Bottom` and `Bottom Center` options for a reason, they should do different things.

So I stepped back a few minor versions and tested. Seems it works if I pull v1.7.0, but breaks in v1.8.0

Too tired now to step through all the versions of v1.7.x backwards to see when it stopped working exactly. Then we can compare and solve it that way.

**Comment by danieliser** [comment]
@fpcorso Tested v1.7.29 today, no issue. So it came in v1.8 specifically. Getting closer.

**Comment by danieliser** [comment]
https://github.com/PopupMaker/Popup-Maker/compare/v1.7.30...v1.8.0#diff-47be2ee7bb15e6b3f1ec991b76ed5edf

Lot of small tweaks to the animations it seems. Looking those over.

**Comment by danieliser** [comment]
@fpcorso 

This is probably it: 
![image](https://user-images.githubusercontent.com/847818/77829518-f4d4ab80-70f8-11ea-8556-f58a56478342.png)

Gonna pick through those changes line by line and see what fixes it. Want to undo as minimal as possible.

I'm pretty certain its related to this issue: https://github.com/PopupMaker/Popup-Maker/issues/633, and this commit: https://github.com/PopupMaker/Popup-Maker/commit/9151d8f0481535122c4f22398364192c4e5202cb

**Comment by danieliser** [comment]
@fpcorso - Ok, I see.

![image](https://user-images.githubusercontent.com/847818/77829860-19318780-70fb-11ea-93c9-ece886a20840.png)

#2 calculates start positioning of the popup container for animation origin. If the popup is hidden via `display:none;` when this occurs the position cannot possibly calculate correctly.

#1 must occur to unhide the popup without it being visible immediately.

I think I'm gonna make this more apparent by redoing the code a bit so that these steps don't happen in variable declarations, but rather in stepped order with full comments to explain why things are there.

**Comment by danieliser** [comment]
So the only change required to make it work correctly is the first line it seems in the image above. Adding back the `.show

**Comment by fpcorso** [comment]
@danieliser , interesting. Such a small piece of code change to have to hunt down. Glad you were able to find it. So, the ones with only one direction (E.g. "Bottom" or "Top") should originate from the popup's side whereas the others should originate from the absolute screen (E.g. "Bottom right" is bottom right of screen), right?

**Comment by danieliser** [comment]
@fpcorso - Correct.

I'm making some small improvements, mainly a reset function so all animations start from the same base styles, along with inline comments and making the code more intuitive to read through.
