### ISSUE TITLE
Bottom positioned elements caused overlay scrollbars to appear

### ISSUE THREAD

**Issue by danieliser** [PopupMaker/Popup-Maker#779]
![image](https://user-images.githubusercontent.com/847818/78000133-cb3aa080-7301-11ea-98d6-69959aeb77e1.png)

**Comment by fpcorso** [comment]
@danieliser Can you provide a little more details on what popup settings you used?

I tried to recreate the issue but was unable to:
![image](https://user-images.githubusercontent.com/9730040/82834736-fbc93180-9e8f-11ea-8404-8c4f8f1a556a.png)

I created a popup using the visual tab, entered in the paragraphs, used default theme, custom size of 300px, and position as bottom-right. Tried both with disable overlay checked and unchecked.

**Comment by fpcorso** [comment]
Also tried size of small and set the bottom and right in positioning to 0px. Still wasn't able to replicate the issue of the scrollbars. 
![image](https://user-images.githubusercontent.com/9730040/82834921-81e57800-9e90-11ea-993b-25a63fe0067b.png)

**Comment by danieliser** [comment]
I will retest, might be the theme that was active.

**Comment by fpcorso** [comment]
@danieliser Did you get a chance to retest for this?

**Comment by danieliser** [comment]
@fpcorso I think this might be related to that weird positioning bug we fixed a while back, but it wasn't merged into all the dev branches right away. So occassionally when working on branches other than dev / master I've seen this. Always ends up being just on my end though so probably can close this for now.
