### ISSUE TITLE
Update extend page

### ISSUE THREAD

**Issue by danieliser** [PopupMaker/Popup-Maker#786]
- [x] Add Form / MailChimp for WordPress
- [x] Add Form / Caldera Forms
- [x] Add Form / WP Forms
- [x] Remove Form / QSM?
- [x] Add Extension / WooCommerce Pro
- [x] Add Other Product / User Menus
- [x] Add Other Product / Content Control

**Comment by fpcorso** [comment]
@danieliser I made all the modifications for this issue. The only thing left is to add the new images for the form and other plugins. Do you generally create those or do you use brand assets? Do you have a specific template you follow for those?

**Comment by danieliser** [comment]
@fpcorso Usually start from brand assets, but put it on a new file the same size as the others there, put the logo in the middle and match the background color to their logo bg color or whatever their secondary color is.

Can't find the old PSD I had for it, but nothing you can't whip up in a few minutes if you open one of the others to edit as a guide.

**Comment by fpcorso** [comment]
@danieliser Okay, I don't have an active Adobe license so I'll try to download one of the free alternatives (maybe GIMP) and try to learn them so I can create these images.

**Comment by fpcorso** [comment]
@danieliser Alright, images are added. This issue is competed.
