### ISSUE TITLE
Explore need to add Developer Wiki here on github.

### ISSUE THREAD

**Issue by danieliser** [PopupMaker/Popup-Maker#797]
Several other plugins that want developers to integrate with or commit code to have wikis outlining most dev stuff. This may make more since than putting it into our own doc sites.

Docs like this for example https://github.com/woocommerce/woocommerce/wiki/How-to-set-up-WooCommerce-development-environment

**Comment by fpcorso** [comment]
Okay, I started building out wiki here for information on setting up this repo's local environment and IDE. I think those types of documentation make sense here for any developer (both our team as well as contributors).
