### ISSUE TITLE
[1.10] No support for font-awesome <5

### ISSUE THREAD

**Issue by danieliser** [PopupMaker/Popup-Maker#803]
@fpcorso User pointed out we currently do not support <FA v5.

Updating this regex to `^fa[srldb]?\s.+` should resolve it by making the `[srldb]` optional.

**Comment by fpcorso** [comment]
@danieliser, Ah! I had used the Font Awesome site for grabbing the classes and all my test sites must use themes that include FA5 and the plugin also uses FA5 so I completely missed that FA4 didn't have the third character. Yeah, we can make the third letter optional.

**Comment by danieliser** [comment]
@fpcorso patching this now for v1.10.1 which is imminent.
