### ISSUE TITLE
simplify

### ISSUE THREAD

**Issue by fpcorso** [PopupMaker/Popup-Maker#809]

**Comment by danieliser** [comment]
@fpcorso Lol, what is this one?

**Comment by fpcorso** [comment]
@danieliser Was playing around with ZenHub to see if we still need it. In the edit Epic screen, there is a long text input right above the list of issues and looks exactly as a search bar as one would expect considering where it is. However, if you type something in and hit ENTER, you quickly realize that it actually is to create new issues and is not a search bar. 😂

**Comment by danieliser** [comment]
@fpcorso Yea I don't even have it active in the browser now. Guess I disabled it a while back and forgot to re-enable it, haven't needed it it seems.
