### ISSUE TITLE
WP responsive images functionality not working

### ISSUE THREAD

**Issue by raoulunger** [PopupMaker/Popup-Maker#811]
The below described issue was brought up on the popupmaker forum (a possible solution was foreseen for v 1.10.1) - for good measure I file it here as an issue as well (which I should have done in the first place, sorry for that).

//

WordPress has ‘responsive images’ functionality built into its core since almost five years now. It means the browser is presented (via a SRCSET in the html-output) with all sizes of a certain image available, so it can choose the one that is sufficiently large for the view window. In this way, loading of too large images (especially on mobile phone) is avoided.

I tested Popup Maker, and noticed that any image included in popup is always served at its full size, even though the SRCSET is present in the hmtl-output. This means on small screens, Popup Maker serves images that are too large. Is there a way to make Popup Maker honour WP’s Responsive Images functionality?

Cheers!
Raoul

**Comment by danieliser** [comment]
@raoulunger - Already patched and released per this commit: https://github.com/PopupMaker/Popup-Maker/commit/9e9919d90b010858cfd177df153ca44a0ee383e3#diff-cdf4afc42a7fc602941517cc80a83513R56

Tested it with both gutenberg and standard editor. Both render proper srcset and load different images per screen size now. Pretty sure it went out in v1.10.0: https://github.com/PopupMaker/Popup-Maker/blob/master/readme.txt#L143
