### ISSUE TITLE
Set margin-top to 0 for first-child in popup content

### ISSUE THREAD

**Issue by fpcorso** [PopupMaker/Popup-Maker#820]
We set the margin-bottom to 0 for the last-child but we do not set the top margin to 0. When trying to create slim floating bars or popups without titles, this makes the popup skewed towards the bottom.

**Comment by fpcorso** [comment]
@danieliser I found an issue with just setting it to 0 completely:
![image](https://user-images.githubusercontent.com/9730040/83792538-2e7de180-a669-11ea-9d61-a204aff8eab8.png)

For popups without a title, we should remove the margin, as shown with the floating bar in the image.

However, for popups with a title, the top margin of the first content child pushes it away from the title, as shown in the popup in the image.

Right now, we have no way for the admin to adjust the margin on the title.

So, we have three options:
## Option 1
Set margin-top to 0 in all cases and then add a margin setting for the title in the popup themes and default it to X px.

## Option 2
Set the margin-top to 0 on first child but then set a margin-top on the first child if the title element is present. This can be achieved using this CSS:
`.pum-container .pum-content>:first-child {
margin-top: 0;
}
.pum-container .pum-title ~ .pum-content>:first-child {
    margin-top: 1em;
}`
which results are shown in this image which looks much better:
![image](https://user-images.githubusercontent.com/9730040/83793066-00e56800-a66a-11ea-8ccf-5d1541d8001f.png)

## Option 3
Set margin-top to all first child but then set margin-bottom on title elements when they are present. The CSS would be this:
`.pum-container .pum-content>:first-child {
margin-top: 0;
}
.pum-container .pum-title {
    margin-bottom: 1em;
}`


I personally like option 3 as it would open us up to be able to move to option 1 in a future update, if we chose to do so. I'm hesitant on going full option 1 since we've been discussing the future of the themes system and wouldn't want to introduce new features there right now until we finalize some of the theme and template plans.

The argument for option 2 would be that if people already have CSS affecting the title and first child, this would be the least likely to affect their changes as we are only affecting one element instead of two as in option 3.

**Comment by danieliser** [comment]
@fpcorso Shouln't option 2 use ` + ` rather than ` ~ `. The first would be more explicit, though with :first-child they likely do the same I guess.

Otherwise I'm good with any of them, so number 3 it is then.
