### ISSUE TITLE
Automate deployment of non functional assets to wp.org

### ISSUE THREAD

**Issue by fpcorso** [PopupMaker/Popup-Maker#827]
Utilizing GitHub actions or similar scripts, we can commit any readme and WordPress.org-specific assets changes to the WordPress.org plugin repository.

10up has an action for this already: https://github.com/10up/action-wordpress-plugin-asset-update

Originally apart of #711

**Comment by fpcorso** [comment]
@danieliser Just realized that we don't keep wp.org assets in the repo. Makes it difficult to hunt down the assets to switch them out and makes this automated deployment not possible.

Should we add the wp.org assets to the repo and, if so, where?

**Comment by danieliser** [comment]
Yea that was part of #711 too, that is the only way to manage them via that action.

**Comment by fpcorso** [comment]
@danieliser Looks like if we continue as planned to the 10up action above, they have a slug for us to point to which directory we use for the assets:
![image](https://user-images.githubusercontent.com/9730040/89574803-b794ce80-d7fa-11ea-8911-6d83226ee1c6.png)

I like their default `.wordpress-org` folder which would sit alongside our `.github` folder as another non-development directory. Are you good with keeping that directory name?

**Comment by danieliser** [comment]
@fpcorso Yea a `.` folder keeps it well out of the normal structures.

**Comment by fpcorso** [comment]
@danieliser Tested this on one of my tiny plugins. The 10up action will update the readme in `trunk` and in the tag folder that matches the stable tag. It did not touch any other files so it should be good.
