### ISSUE TITLE
Delete related user meta upon complete uninstall

### ISSUE THREAD

**Issue by fpcorso** [PopupMaker/Popup-Maker#831]
Right now, when someone does a complete uninstall, it removes popups, popup themes, and Popup Maker related settings. However, the few user meta keys we set still remain. This includes dismissed alerts and dismissed tour pointers. I wonder if we should also remove these, if there is an efficient way, to ensure that, if installed again, it would be like a fresh start.

**Comment by fpcorso** [comment]
@danieliser The most efficient way for this one is a direct query deleting all our user meta keys, right? The alternative would be looping over users and using built-in WordPress methods but on sites with lots of users, that might make the uninstall system go slow.

Something like:
```php
$wpdb->query( "DELETE FROM $wpdb->usermeta WHERE meta_key LIKE '_pum_%'" );
```

**Comment by danieliser** [comment]
@fpcorso this is basically what we do for post meta as well.

**Comment by fpcorso** [comment]
@danieliser Yes, that's where I got the query from 😅 . Was asking if there was a better way for the usermeta or if we should use the same strategy.

Also, do you have any thoughts on the second part of my question about the pointers?

**Comment by danieliser** [comment]
@fpcorso I'd do a mix, delete all *_pum_*, and if there are other non namespaced options, we need to delete them specifically.

As for pointers, that is likely something we may have to consider leaving if there is no clean way to remove them at scale.

**Comment by fpcorso** [comment]
Okay, I added query that covers all usermeta we use in the plugin. We'll leave out the pointers for now as I don't think there is an efficient way to handle them right now.
