### ISSUE TITLE
Periodical Tip/Suggestion Message

### ISSUE THREAD

**Issue by fpcorso** [PopupMaker/Popup-Maker#834]
Popup Maker has a lot of settings and configurations that are useful across different sites. What if we had some sort of "tips" or "suggestions" message that appeared on some recurring basis such as "tip of the day" or "tip of the month"?

These could highlight smaller settings/features or suggest improvements that we know would help popups perform better.

**Comment by fpcorso** [comment]
@danieliser What are the top X things you think people miss in the plugin that would greatly help them (and possibly help reduce support)?

Maybe:
1. Bypass ad blockers setting
2. Enable Block Editor Support setting (until we make it default)
3. Disable categories & tags setting

**Comment by danieliser** [comment]
categories and tags are disabled by default, so technically would be enabling, but I don't know its useful unless we qualify it with only showing it to users with more than 10 popups that actually need categorizing etc.

Others might be

4. Targeting
5. Theme editor
6. Admin toolbar helper (which could be expanded).
7. Add popups to nav menu items in 1 click.

**Comment by fpcorso** [comment]
@danieliser The setting is labeled starting with "Disable categories..." which is what I was referring to.

The Admin toolbar helper would be handy and the menu item popups. 

The targeting already has a pointer to it and, if they haven't found the targeting to create a popup by the time this periodical tip gets shown, they probably would have already deleted the plugin. So, not sure on that one.

**Comment by fpcorso** [comment]
@danieliser What's a good frequency for a tip? We already have multiple other alerts so I don't think we could do weekly on top of the others. So, maybe once a month?

**Comment by fpcorso** [comment]
@danieliser In addition to the questions above, I'm thinking we structure the tip something like this. We have a brief statement about some X feature. 

Then have links to learn more (either to the particular settings page/feature or the documentation about the feature) and to dismiss (we already have the X but though listing "Learn more" as the only option might not be as intuitive).

![image](https://user-images.githubusercontent.com/9730040/96151539-8232ee00-0ed9-11eb-8169-3a6fbedb32f1.png)

Any thoughts/feedback on this approach?

**Comment by danieliser** [comment]
@fpcorso Yea once a month is probably enough, and we should probably have a never show these tips again option as well.

Maybe 3 days is ok, not sure really how to even test that.

**Comment by fpcorso** [comment]
@danieliser Good call on the "never show these tips again" idea. Will get that added.

**Comment by fpcorso** [comment]
@danieliser Updated the alerts to also have an option to disable tips.
![image](https://user-images.githubusercontent.com/9730040/96278110-1ae17080-0fa3-11eb-83f1-b542cc18710f.png)

**Comment by danieliser** [comment]
@fpcorso looks awesome.
