### ISSUE TITLE
Add filter to exclude blocks with isAllowedForBlockType 

### ISSUE THREAD

**Issue by pcfreak30** [PopupMaker/Popup-Maker#835]
Right now `excludedBlocks` is a hard coded list. Some plugins dont like having the additional `openPopupId` added in and will cause a 400 api error.

In my case, it is gravity forms doing this. I manually changed `excludedBlocks`  to `var excludedBlocks = ['core/nextpage', 'gravityforms/form'];` 

There should be a php filter to output with ex `pum_block_editor_vars` to dynamically add compatibility with different plugins.

Thanks :)

**Comment by danieliser** [comment]
@pcfreak30 - Sounds reasonable enough.

**Comment by danieliser** [comment]
Reference: https://github.com/PopupMaker/Popup-Maker/blob/master/src/block-editor/block-extensions/popup-trigger/index.js

**Comment by danieliser** [comment]
Possibly related: https://secure.helpscout.net/conversation/1196422100/16578/

**Comment by fpcorso** [comment]
@pcfreak30 We added a new filter in a recent commit which should appear in our upcoming `1.14` release. The new filter will be `pum_block_editor_popup_trigger_excluded_blocks`.

I already tested it with the Gravity Forms using the following code and works great. You should be able to use this going forward after the update is out.
```php
add_filter( 'pum_block_editor_popup_trigger_excluded_blocks', function( $blocks ) {
    $blocks[] = 'gravityforms/form';
    return $blocks;
});
```

**Comment by WMNF-web** [comment]
I hope it's ok to add a comment on how you can find block names you want to exclude. The way I did this was to search for the `register_block_type`  function in the plugin directory. For instance, I had this same issue with the All In One Video Gallery plugin blocks. To find all the blocks via an SSH session, I changed to the plugin directory and ran `grep` as shown below ...

`[robert@www all-in-one-video-gallery-premium]$ grep -r register_block_type .
./blocks/blocks.php:    public function register_block_types() {
./blocks/blocks.php:            if ( function_exists( 'register_block_type' ) ) {
./blocks/blocks.php:                    register_block_type( 'aiovg/categories', array(
./blocks/blocks.php:                    register_block_type( 'aiovg/videos', array(
./blocks/blocks.php:                    register_block_type( 'aiovg/search', array(
./blocks/blocks.php:                    register_block_type( 'aiovg/video', array(
./includes/init.php:            $this->loader->add_action( 'init', $blocks, 'register_block_types' );`

Then added to the list of blocks to exclude as needed ...

`add_filter( 'pum_block_editor_popup_trigger_excluded_blocks', function( $blocks ) {
    $blocks[] = 'gravityforms/form';
    $blocks[] = 'aiovg/categories';
    $blocks[] = 'aiovg/search';
    $blocks[] = 'aiovg/video';
    $blocks[] = 'aiovg/videos';
    return $blocks;
});`

Thanks for the filter!

**Comment by danieliser** [comment]
@pcfreak30 I will add to that, I found that you can get all of a current blocks info, including the block name for this filter by adding it to a builder and while it is selected entering this into the browser console.

```
wp.data.select( 'core/block-editor' ).getSelectedBlock().attributes;
```
