### ISSUE TITLE
Add code of conduct to repo

### ISSUE THREAD

**Issue by fpcorso** [PopupMaker/Popup-Maker#842]
To ensure all contributors understand how we expect people to behave and how we enforce it, we need to add a Code of Conduct.

We have two options:

1. We can add it at this repo level: https://docs.github.com/en/github/building-a-strong-community/adding-a-code-of-conduct-to-your-project
2. Or, we can add a default code of conduct at the org level so all public repos within PopupMaker inherit that one: https://docs.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file

Once we decide on that route, we need to decide on a good template to use. Here are some of the most popular ones used:

1. https://contributor-covenant.org/
2. https://www.djangoproject.com/conduct/
3. http://citizencodeofconduct.org/

Here is an example from a repo within the WP space: https://github.com/WordPress/gutenberg/blob/master/CODE_OF_CONDUCT.md

Here is a good guide for creating and using Code of Conducts for open source projects: https://opensource.guide/code-of-conduct/

This was moved out of the original #799 issue.

**Comment by fpcorso** [comment]
@danieliser: Out of the two options, I think the second option (org level) makes sense so we don't have to create one for each repo. Do you think we may have Code of Conducts that differ between the repos?

**Comment by danieliser** [comment]
@fpcorso Agree

**Comment by fpcorso** [comment]
@danieliser Here is the initial version: https://github.com/PopupMaker/.github/blob/master/CODE_OF_CONDUCT.md

I think that works for us at our current size.
