### ISSUE TITLE
Add contributor guidelines

### ISSUE THREAD

**Issue by fpcorso** [PopupMaker/Popup-Maker#843]
To help any contributors understand our code style, requirements, and preferences, we need to set up some contributor guidelines. We have some basics listed in the repo readme to help us get started.

We have two options:

1. We can add it at this repo level: https://docs.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors
2. Or, we can add a default contributor guidelines at the org level so all public repos within PopupMaker inherit that one: https://docs.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file

Here are some examples of Contributor Guidelines:
1. https://github.com/atom/atom/blob/master/CONTRIBUTING.md
2. https://github.com/opengovernment/opengovernment/blob/master/CONTRIBUTING.md
3. https://github.com/WordPress/gutenberg/blob/master/CONTRIBUTING.md

This was originally part of #799.

**Comment by fpcorso** [comment]
@danieliser For this one, I think going option 1 (repo level) might be more appropriate as the specific relevant information for each repo might be different. Alternatively, we have an org level guidelines that is general and then use each repo's wiki or readme for more specific guidelines.

**Comment by danieliser** [comment]
@fpcorso agree
