### ISSUE TITLE
Add security policy

### ISSUE THREAD

**Issue by fpcorso** [PopupMaker/Popup-Maker#845]
GitHub supports having a security policy. In fact, there is a "Security" tab along the repo toolbar that would show one if we had it.

The main section of the security policy is how to report a vulnerability.

A few examples of security policies:
1. https://github.com/WordPress/gutenberg/blob/master/SECURITY.md
2. https://github.com/Veil-Project/veil/blob/master/SECURITY.md

**Comment by danieliser** [comment]
We should probably have it point to a special form that goes directly to our teams inbox or slack etc.

**Comment by fpcorso** [comment]
@danieliser Yeah, that's probably a good idea. I'll create a form on the site for reporting security vulnerabilities.

**Comment by fpcorso** [comment]
@danieliser Also, just found out that we can also add this at the org level so all the repos inherit it. I think that makes sense for this one.

**Comment by fpcorso** [comment]
@danieliser What do you think of this form: https://wppopupmaker.com/report-security-vulnerability/

I think it contains all the elements one would need to report an issue to us. Surprisingly, most of the WP plugins I looked at didn't have anywhere on their site to report an issue. I had to look at some pages from Microsoft, Bluetooth group, and a few others of similar size to find good examples of what to include.

Two useful guides for reporting an issue that I used also were: https://medium.com/swlh/how-to-write-a-better-vulnerability-report-20163ab913fb and https://blog.cobalt.io/how-to-write-a-great-vulnerability-report-ab8654c6290c

**Comment by danieliser** [comment]
@fpcorso needs styling but looks good. Definitely like that it collects things on how to attack it and possible solutions.

Are you planning to link to those guides or culminate them into one for our own docs?

**Comment by fpcorso** [comment]
@danieliser I created our initial security policy. Before I add it "officially", can you glance it over and let me know if you agree with the content and if there is anything you think I should change: https://github.com/PopupMaker/.github/blob/master/SECURITY.md

**Comment by danieliser** [comment]
@fpcorso - Looks good.
