### ISSUE TITLE
Add "subscriptions" to Woocommerce Endpoints List

### ISSUE THREAD

**Issue by bydrewpaul** [PopupMaker/Popup-Maker#849]
## Describe the feature request
I edited your plugin to add an endpoint for a WooCommerce Subscription Plugin, and was hoping to have it updated to avoid needing to alter it each update or hack the plugin.

## Use case
I currently downloaded a plugin extension for WooCommerce called Subscriptions. It has an endpoint of 'subscriptions' for users to view their subscription data.

## Example screenshots (if any)
<img width="978" alt="Screen Shot 2020-07-12 at 9 30 53 PM" src="https://user-images.githubusercontent.com/20331270/87264881-d23b8800-c486-11ea-9847-770d4b433cee.png">

**Comment by fpcorso** [comment]
@bydrewpaul Thanks for submitting the pull request! We have now merged it into `develop` and it will be included in our 1.12 update.
