### ISSUE TITLE
CF7 Update breaks integration

### ISSUE THREAD

**Issue by danieliser** [PopupMaker/Popup-Maker#851]
## Describe the bug
The latest CF7 update removed their jQuery event system and broke the integration we have with their success events.

Requires replacing our events with the new DOM events.

- [ ] https://contactform7.com/dom-events/

## Additional context
- https://contactform7.com/2020/07/04/contact-form-7-52/#more-36548
- https://contactform7.com/dom-events/

**Comment by DevSnapTech-Lindsay** [comment]
Is there an ETA when you will have a patch for this or detailed solution on how we can edit the code in the meantime to fix this?

**Comment by fpcorso** [comment]
@DevSnapTech-Lindsay At quick glance, all of our CF7 JS code is within our contactform7.js file. And, there is only one jQuery event in that file: https://github.com/PopupMaker/Popup-Maker/blob/master/assets/js/src/integration/contactform7.js#L9

So, I think it may only need to be updated to the new CF7 DOM events and maybe update the code for getting the form ID and instance ID.

I'll be looking into this issue today and will let you know if there is anything more than that.
