### ISSUE TITLE
WP 5.5: `wp_make_content_images_responsive` is deprecated, use `wp_filter_content_tags()` instead

### ISSUE THREAD

**Issue by lkraav** [PopupMaker/Popup-Maker#852]
## Describe the bug
Traceback https://sentry.io/share/issue/7530f25ac4ff48979eb4eccadc3aa212/

https://github.com/PopupMaker/Popup-Maker/blob/cf71d1c064c1fa6c37ce527150639fdc406b0051/classes/Site.php#L60

## Site information
Popup Maker version: 1.11.0
WordPress version: 5.5.0 b2
PHP version: 7.4.7

**Comment by fpcorso** [comment]
@lkraav Thanks for reporting this notice. It seems the wp_filter_content_tags function is introduced in 5.5 so we wouldn't be able to make the switch right now or the plugin wouldn't work on WordPress 5.4.

We will have to re-evaluate this once 5.5 almost out or after to see when is the appropriate time for us to make this switch.

I'll tentatively add this to our 1.12 milestone so we can be sure to come across it again in the near future.

**Comment by fpcorso** [comment]
@lkraav Sorry, I completely misunderstood what this error was the first time I glanced at it. Definitely should have been fixed prior to 5.5's official release. Working on a hotfix release to get out to fix this and a couple of other issues.

Thanks for reporting the issue!
