### ISSUE TITLE
Create example popup(s) upon install

### ISSUE THREAD

**Issue by fpcorso** [PopupMaker/Popup-Maker#857]
We briefly discussed the possibility of creating one or two example popups when the plugin is first installed. This would help show some use cases as well as best practices for popups created within the plugin.

If added, how many and what sort of example popups should be added?

**Comment by danieliser** [comment]
I'd say maybe a normal optin or announcement popup mid-center and a slide in from bottom right like Ahoy.

**Comment by fpcorso** [comment]
@danieliser What if we also include these example popup(s) during the tour of the all popups page? We could point to the opens and conversion columns to better frame how those work.

**Comment by fpcorso** [comment]
@danieliser Just had a cool idea: What if the example popups that area auto-created and the finished version of the popups from a few of our step-by-step guides? Then, in the body of the example popup, we can refer them to the guide too.

**Comment by danieliser** [comment]
Not bad ideas at all.
