### ISSUE TITLE
Constantly getting TypeError: Cannot read property 'close' of undefined

### ISSUE THREAD

**Issue by DevSnapTech-Lindsay** [PopupMaker/Popup-Maker#861]
## Describe the bug
On exit and scroll triggers, and sometimes on just time delay pup getting error TypeError: Cannot read property 'close' of undefined which is breaking the page and is preventing the popup from firing. We have set the popups as per popup maker documentation. It sometimes works once, and then further testing shows it broken.

![close-issue-popup-maker](https://user-images.githubusercontent.com/67763930/88692662-30857f00-d0b3-11ea-92df-12722c0cca87.jpg)
## Site information
Popup Maker version: 1.11.0

WordPress version: 5.4.2

PHP version: 7.4

## Expected behavior
The popup should fire on the propper trigger and not freeze the screen. 

## Current behavior
Scroll and exit triggers are freezing the page and throwing the error

## Steps to reproduce
1. Created multiple popups as per documentation
2. Tried on multiple browsers
3. Verified same error through inspecting on all browsers tested

## Errors
 Uncaught TypeError: Cannot read property 'close' of undefined -  popup-maker-forced-interaction-site.min.js?defer&ver=1.0:1
See attached file

## Additional context
This is the second major issue we are having with popup maker, other issue is 
[https://github.com/PopupMaker/Popup-Maker/issues/851](https://github.com/PopupMaker/Popup-Maker/issues/851)

**Comment by danieliser** [comment]
@DevSnapTech-Lindsay per the email response:

Your site is both loading a currently incompatible version of jQuery (with WordPress ecosystem), as well as loading a second copy that is old and likely overloading parts of the first.

These 2 issues alone are enough to cause havoc with plugins that rely on jQuery.

So I'd recommend trying to track down those copies, likely from themes or other plugins and remove them to make your site compatible with the other 99.999% of the WP ecosystem that does things using compatible methods (using what comes with WP).

**Comment by danieliser** [comment]
@DevSnapTech-Lindsay Did that resolve the issue?

**Comment by GrmpyPmpkin** [comment]
Hi. I know this issue is closed, but I am having the same issue and it is only when I have enabled the forced interactions extension plugin. The Popup Maker and Leaving Notices plugins are fine. Can you please help?
