### ISSUE TITLE
Trying to access 'private' key when field is false

### ISSUE THREAD

**Issue by fpcorso** [PopupMaker/Popup-Maker#873]
## Describe the bug
After de-activating Videos, Scheduling, or Forced Interaction, a warning begins to appear when viewing pages that popups are loaded on.

## Site information
Popup Maker version: 1.12

WordPress version: 5.5

PHP version: 7.4

## Errors
Error originating from this line: https://github.com/PopupMaker/Popup-Maker/blob/master/classes/Model/Popup.php#L229

![image](https://user-images.githubusercontent.com/9730040/90803851-5f27fb80-e2e7-11ea-812b-07d210130a3d.png)

## Additional context
Upon debugging, I discovered that some fields are left where the `$value` is `false`. So, during the check for if the `$field` is false, it passes the not empty check leading the code to go to the `$field['private']` check which throws this error since `$field` is false.
![field-debugging](https://user-images.githubusercontent.com/9730040/90803962-8b437c80-e2e7-11ea-9482-432aca59f24f.png)

**Comment by danieliser** [comment]
Simplest solutions might be

Change `&& ! empty( $value )` to `&& isset( $value )` which would allow a false.

Or simply check that $field is an array before using it as one.

Or both.

**Comment by fpcorso** [comment]
@danieliser For the empty check, I think the very point of it is this use case. If a field no longer exists and there is a value, pass it through.

So, in that case, I think your solution of changing the empty to an `isset` is probably the right choice. I'll review the code and debug a bit more to make sure that change doesn't break anything. If not, I'll commit that.

**Comment by danieliser** [comment]
@fpcorso sounds good.
