### ISSUE TITLE
Label older form triggers/cookies as deprecated (or similar)

### ISSUE THREAD

**Issue by fpcorso** [PopupMaker/Popup-Maker#874]
Since our goal is to have everyone using the newer `Form Submission` triggers and cookies, we need to better communicate that the older `success` ones are not recommended. Most people do not read the docs unless needed so they probably aren't aware the older ones are no longer recommended and are planned to be removed someday.

So, we should add something similar to ` (deprecated)` or ` (use Form Submission instead)` to the end of these.

**Comment by fpcorso** [comment]
@danieliser What if we used both? For example: `Gravity Forms (deprecated. Use Form Submission instead)`. Would that be too much? We probably don't want to just say deprecated without telling them there is something else they can use but not sure if we can just say to use something else instead without saying it's deprecated. 

Thoughts?

**Comment by danieliser** [comment]
@fpcorso I do agree we need to let them know, not sure if that is too long though. We can test it I guess.
