### ISSUE TITLE
Consider ways to reduce clutter in "All Popups" table

### ISSUE THREAD

**Issue by fpcorso** [PopupMaker/Popup-Maker#878]
With the addition of the enabled toggle, the "All Popups" page is getting a little cluttered when one has tags/categories enabled too, which we know almost 6% of our customers do.  This is what it looks like on my laptop screen which is definitely a bit cluttered:
![laptop-example](https://user-images.githubusercontent.com/9730040/93239913-6f4dc200-f751-11ea-8747-f6c6edd54bf7.png)

Even on my larger monitor with the sidebar closed:
![monitor-example](https://user-images.githubusercontent.com/9730040/93239917-707eef00-f751-11ea-85e2-1d14ce9c94e1.png)

We also wanted to add in the conversion counter (see #775) columns too which would make this even more cluttered. 

Since we don't recommend people ever use popmake-{name}, do you think we could remove that from the CSS classes? Other than that, the only thing else we could consider removing is the whole CSS classes column or the title column. If we just remove the second CSS class, it wouldn't be too bad on the larger monitor but would be still a bit tight after we add conversion counters.

Alternatively (or additionally), we may be able to get rid of the Title or published date.

The other main question is: Do people use "Screen Options" to adjust these? If so, it's not something we'd have to worry about too much. My hunch is that most people see the clutter and do not think of the "Screen Options".

**Comment by danieliser** [comment]
1. We can remove the popmake-name classes from the list here, they still need to function for back-compat but I'm good with the other proposed change.

2. Agree, we can probably ditch or at least mark Title and published date as not visible by default under screen options.

3. Take it a step further, extend the Admin Pointers to show they can change what data is visible and available to them via Screen Options.

**Comment by fpcorso** [comment]
@danieliser Removed the extra css class from the table, hidden title and date by default, and added the extra pointer.

![image](https://user-images.githubusercontent.com/9730040/94935974-b2bb6680-049b-11eb-8593-d31111a386b2.png)

**Comment by danieliser** [comment]
Nicely done.
