### ISSUE TITLE
Add PHP Compatibility checks for PHP CS

### ISSUE THREAD

**Issue by danieliser** [PopupMaker/Popup-Maker#881]
Gutenberg currently uses this to test for PHP 5.6+ compatibility.

https://packagist.org/packages/phpcompatibility/php-compatibility

It can be done via .phpcs.xml.dist or composer.json

**Comment by ritwikchakraborty123** [comment]
Hai I want to contribute

**Comment by danieliser** [comment]
@ritwikchakraborty123 we would love to have it. Let us know how you think you can help.

**Comment by ritwikchakraborty123** [comment]
Sir can you mark the page where actually bug is.facing difficulty in finding

**Comment by danieliser** [comment]
Added in c80bd25f8d40de9906ea5c6206eb4fbfcfdc16bc
