### ISSUE TITLE
Add links for going to all popups or creating a popup to admin bar menu

### ISSUE THREAD

**Issue by fpcorso** [PopupMaker/Popup-Maker#892]
There are many times during testing a popup where I want to jump back to the "All Popups" page or go to create a new popup. Several other plugins include options to view all or create a new item, such as Gravity Forms.

It would be useful to list "All Popups" and "Add New" below the current items in the admin bar menu.

**Comment by danieliser** [comment]
@fpcorso I believe (could be wrong) that the Popup Maker -> Popups menu item is already a link to All Popups, but no there is no New popup option.

**Comment by fpcorso** [comment]
@danieliser Just checked and you are correct that the menu item is linked. However, considering I have been using the plugin for over a year and create dozens of test popups during each release cycle and I still didn't know that, it may be a good idea to specifically add an "All Popups" link to make it more noticeable.

**Comment by fpcorso** [comment]
@danieliser Added the two new links. Mirrored the other plugins that do this by having the all popups first followed by the new popup link.

![image](https://user-images.githubusercontent.com/9730040/98261952-09143d00-1f53-11eb-8205-69229ea4c804.png)
