### ISSUE TITLE
uncaught RangeError: Invalid array length with Debug Mode enabled.

### ISSUE THREAD

**Issue by danieliser** [PopupMaker/Popup-Maker#898]
Users have reported this issue once or twice, and have confirmed that disabling Debug Mode fixes it:

https://secure.helpscout.net/conversation/1326263250/18548?folderId=557112

**Comment by fpcorso** [comment]
@danieliser Do you have any insight into where this was occurring or were you able to replicate it? The ticket you linked to only mentions this error and disabling debug mode but doesn't provide any other details.

**Comment by danieliser** [comment]
@fpcorso He didn't provide any more context, but just based on the error and fact its related to debug mode I'd say its in these lines here:

https://github.com/PopupMaker/Popup-Maker/blob/1.12.0/assets/js/src/site/plugins/pum-debug.js#L103-L117

Specifically one of the `new Array()` calls is passing a negative range or a range too large: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Invalid_array_length

```
An invalid array length might appear in these situations:

When creating an Array or an ArrayBuffer which has a length which is either negative or larger or equal to 232, or
when setting the Array.length property to a value which is either negative or larger or equal to 232.
```

**Comment by fpcorso** [comment]
@danieliser Yes, seeing that disable debug mode removes the error, I had already guessed that the error was possibly originating from that file. 

My question was if you had any insights into what environment/setup was causing it and if you were able to replicate it. Right now, I cannot replicate it on my test sites so I cannot test if any solution actually solves it which is why I was asking.

**Comment by danieliser** [comment]
@fpcorso that was just a quick guess. It could be anything based on what you've shown.

Most likely some JS function returns an array and we are not using it properly would be my guess. No idea how to find it if linter isn't picking it up.

**Comment by fpcorso** [comment]
@danieliser Yeah, ESLint doesn't report anything other than us not using camelCase and us using console here. Nothing regarding this issue. Since I can't replicate the issue, not sure if we can get this fixed in `1.15` unless we get more insights.

**Comment by danieliser** [comment]
@fpcorso punted for now.

**Comment by danieliser** [comment]
Still unable to find anything in our code base that could produce this. Closing for now.
