### ISSUE TITLE
Activation/Installation Wizard

### ISSUE THREAD

**Issue by fpcorso** [PopupMaker/Popup-Maker#900]
When a site first installs Popup Maker, we can show a simple and quick wizard for some basic settings. The most important one to consider is asking if the admin wants to use the block editor or the classic editor. This would help increase our usage of the block editor until we feel confident enough for switching it as the default.

## Things to consider having

1. Welcome video
2. Quick, 3 minutes to your first popup video
3. Setting for the block editor
4. Setting for adblockers
5. Telemetry - would allow us to remove the alert
6. Button to take them to all popups page

**Comment by fpcorso** [comment]
@danieliser Updated the issue with some more ideas for within the plugin onboarding. Not saying we should do all of them but wanted to put down anything we might add so we can start discussing what to put. Am I missing anything we should consider adding?

**Comment by fpcorso** [comment]
@danieliser So, based on my onboarding research and some concepts from UXATT, we should probably strip this to getting the user to creating their first popup as fast as possible. 

Instead of letting them wander aimlessly into the setting first, we should probably automatically show a welcome screen and a button to go create their first popup.

If we didn't have any settings in the "wizard", it could be something simple like this:
![Home](https://user-images.githubusercontent.com/9730040/100480259-c4497500-30be-11eb-8fcc-d7a4cc117641.png)

Where the video area is either a welcome video or some welcome text.

For some important setting, we could have a setting section before the button, like this:
![Home](https://user-images.githubusercontent.com/9730040/100480390-1ee2d100-30bf-11eb-9c6d-3a752d29c6d5.png)

Since the goal is to get them to their first popup as soon as possible, the majority of settings can wait and not be here. The exception is the block editor vs classic editor since that will affect their popup creation. So, we could add that setting here. Or, we can keep the block editor as a setting elsewhere and make it a little more prominent until we switch it to being the default.

I'm leaning towards not having any settings here and getting them quickly to the new popup screen.

Thoughts @danieliser ?

**Comment by danieliser** [comment]
I really like the flow.

The only thing we would do maybe in the future, is replacing the "Create my first popup!" button at some point with a WooCommerce setup like wizard. So if there were more settings that neededt o be initialized they could paginate through them, and on the last step of course it would say "Congradulations your ready to create your first popup" with a button like yours.

But for now, I think your right, there are only a few possible settings for them to consider.

We could have a follow up second welcome screen that overtakes the All Popups screen after they have made their first popup, that could then guide them through some of the settings for adblock etc. Unless you had another idea for how to get them following up quickly.

**Comment by fpcorso** [comment]
@danieliser Here is the current prototype. What do you think of the welcome message? Thought we could suggest some use cases, provide some social validation (installs + reviews), and then let them know we are here if they need help.

![image](https://user-images.githubusercontent.com/9730040/100762967-97e56f80-33c2-11eb-9da4-a5f39c01be26.png)

**Comment by danieliser** [comment]
@fpcorso That looks good. Should the avatar and signature be side by side somehow? Avatar could probably be a bit smaller as well.

**Comment by danieliser** [comment]
@fpcorso Also I think I have my signature in a png if you wanted to use it.

**Comment by fpcorso** [comment]
@danieliser How's this for the avatar+signature:
![image](https://user-images.githubusercontent.com/9730040/100776590-b94e5780-33d2-11eb-8b3d-8c0606807269.png)

**Comment by danieliser** [comment]
@fpcorso oh yea that is a lot better.
