### ISSUE TITLE
pum-admin-bar Script Fails to Load

### ISSUE THREAD

**Issue by fluxism** [PopupMaker/Popup-Maker#907]
## Describe the bug
Admin scripts fail to enqueue on front end, breaking the admin bar button

## Site information
Popup Maker version: 1.13.1

WordPress version: 5.5.3
PHP version: 7.4.1

## Expected behavior
popup-make/assets/js/admin-bar.js should load as long as Disable Popups Admin Bar is disabled in settings.

## Current behavior
admin-bar.js, using the handle 'pum-admin-bar' fails to load. Query Monitor states "dependency missing"

## Steps to reproduce
1. Enable Popup Maker
2. Visit front end page

## Additional context
Was able to fix by adding to includes/modules/admin-bar.php, line 23:
`		add_action( 'wp_enqueue_scripts', array( __CLASS__, 'enqueue_files' ) );
`

**Comment by danieliser** [comment]
@fluxism can you confirm that the issue exists if you only have Popup Maker active? I haven't seen this recently and have been using the toolbar a lot for testing new features.

An easy way to test it is using the Health Check plugin's Troubleshooting mode on our plugin. If it doesn't occur then, I'd activate the other plugins in troubleshooting mode one by one till the issue re-appears.

Let us know.

**Comment by fluxism** [comment]
I confirmed. In Troubleshooting mode with only Popup Maker activated the issue still occurs.

**Comment by lkraav** [comment]
I also see this happening, for some reason QM states `jquery` dependency missing, although it's clearly there.

Maybe a timing issue, race condition of some sort?

It started somewhere at around 1.10 maybe or thereabouts.

**Comment by fpcorso** [comment]
@fluxism @lkraav @danieliser I was able to reproduce this. Interestingly, the hook for the admin bar comes after the hook for printing footer scripts apparently.
![image](https://user-images.githubusercontent.com/9730040/103233380-01499700-490b-11eb-8fad-a6427e8aa648.png)

This is definitely too late to be enqueueing scripts and styles. As suggested by @fluxism, I have moved that method to the `enqueue_files` hook. Thanks for reporting this!

**Comment by danieliser** [comment]
@fpcorso nice catch. Strange it didn't cause issues the entire time unless core changed something about that ordering.

**Comment by lkraav** [comment]
> Nice catch. Strange it didn't cause issues the entire time unless core changed something about that ordering.

Most weird thing is that same site, this misfire shows up only on some screens for us. Most of the time this issue doesn't occur, so doesn't seem to be a core thing. Haven't been able to figure out what the common denominator is.
