### ISSUE TITLE
Update Tested up to for WP 5.6

### ISSUE THREAD

**Issue by danieliser** [PopupMaker/Popup-Maker#909]
WP 5.6 is imminent.

I have tested all basic functionalities including:
- creating popups, triggers, cookies.
- adding shortcodes & blocks.
- tracking conversions on form submission.

@fpcorso anything else besides extensions we need to test specifically?

**Comment by fpcorso** [comment]
@danieliser No, that should be good.

I'll do another round of tests real quick on 5.6 and, as long as I don't see anything we both missed the first time, I'll go ahead and increase the "tested up to" on `develop` and in the live version, as we discussed in Slack.

**Comment by fpcorso** [comment]
@danieliser Went through and tested creating popups, triggers, cookies, etc... in both classic and block editors. Also tested opening popups through time delay, scroll, exit intent, click, etc...

Everything works as intended, though we do get a bit of deprecation notices from jquery migrate which we will need to solve prior to 5.7. 

Should be good to bump the tested to value now.
