### ISSUE TITLE
Improvements to 'Extend' page

### ISSUE THREAD

**Issue by fpcorso** [PopupMaker/Popup-Maker#913]
Right now, our Extend page has both our extensions and plugins Popup Maker works well with. This can be a bit confusing so we should probably separate the "integrations" out either to their own page or somewhere more prominent in our site or documentation.

Additionally, all of the "Extend" page makes it feel like buying the extensions individually are the only way. We need to find ways to introduce and recommend the plans.

Some snippets of the conversation from Slack:

> Frank: What if, instead of "Extend" the link is to "Upgrade" or "Premium". That's standard with Smush, AIO, Yoast, Pretty Links, etc...  Some take that link directly to their pricing page. Some have a splash page of premium features within the plugin that then links to the pricing page.
For example, Smush as a "Smush Pro" page in their plugin within their menu which has some copy, lists some premium features, lists some metrics, and links to their pricing page. 
So, we could do that same strategy where we switch our "Extend" page to be more of explaining our premium features and takes them to the pricing page instead of individual extensions pages.

> Daniel: I like that both would be sufficient, we could either link it to a landing page on our site, or to a page in dash. We could also do what we do for the Dashboard support page as well. Let them use an iframe browser.

> Frank: One challenge is that our extend page currently has both premium features and integrations. If we set that up for more pushing towards upgrades (or if we end up having that link go to a landing page), what about the integrations? Do we separate those into two separate pages or move integrations somewhere else?

> Daniel: But to the other point, couple options come to mind:
> * Separate "Integrations" page in the Popup Maker menu.
> * Add it to the Welcome page/notice so its only seen once.
> * Move it all to our site, and simply link off to it from somewhere (or a few places).
> * Get rid of it entirely, and show targeted alerts based on if those other plugins are already active, then link off to a page on our site describing what it offers.

**Comment by danieliser** [comment]
I think we opted for combination of the last 2 bullet points @fpcorso.

**Comment by fpcorso** [comment]
@danieliser Since the extend page is one of the biggest sources of traffic and sales, I wonder if we should be more incremental in these changes.

What if, we start by adding a small CTA at the top pushing people to the pricing page, and then positioning the list of extensions as learning about our most popular premium features?

Here's a rough outline of what I am envisioning:
![image](https://user-images.githubusercontent.com/9730040/102106532-b2760a80-3dfe-11eb-8227-05e2fd327088.png)

**Comment by danieliser** [comment]
@fpcorso that is nice looking.

That also works out well if we suddenly turned off single extension sales, no need to update plugin extend page

**Comment by fpcorso** [comment]
@danieliser Okay, I'll clean up the design some and then merge it in. I'll probably keep tweaking the actual copy while working on other areas but we can go ahead and merge to make sure it gets released with `1.15`.

Once released, we can start looking at the next version of the upgrade page.
