### ISSUE TITLE
Add 'flush popup cache' link in admin bar menu

### ISSUE THREAD

**Issue by fpcorso** [PopupMaker/Popup-Maker#931]
## Describe the feature request
Add a new link in the Popup Maker admin bar menu to flush our existing cache.

## Use case
Right now, when testing changes or developing new features, we have to constantly go in and re-save a popup or theme in order to see the changes or leave asset caching off. It would be handy to have a dedicated button to reset the cache.

**Comment by danieliser** [comment]
Would be useful for users debugging issues at times as well.

**Comment by fpcorso** [comment]
@danieliser Where in the menu do you think this should go? Where it is located in this image or maybe in the "Tools" menu? Should we draw attention to it, as I did in the image, so people notice it?

![image](https://user-images.githubusercontent.com/9730040/103675647-32027f80-4f4e-11eb-92b5-5873cd79d202.png)

**Comment by danieliser** [comment]
@fpcorso Tools tab would make most since likely. Not sure highlight matters long term, maybe initially to show people something new is there.
