### ISSUE TITLE
Ninja form date picker doesn't work in popup

### ISSUE THREAD

**Issue by Yop-La** [PopupMaker/Popup-Maker#934]
## Describe the bug
I have a ninja form  wirh a date picker filed in a popup . The date picker is ko when the form is in the popup. And the date picker is ok when on a simple page ( not in a popup ). By ko, I mean : " we can't select a date". The filed is frozen.

I have reproduced this bug on two wordpress site

## Site information
Popup Maker version: Version 1.14.0
Ninja form version: Version 3.4.33

WordPress version: 5.6

PHP version: 7.3

## Expected behavior

We should select date with date picker filed in the popup

## Current behavior

We can't select date with date picker filed in the popup

## Steps to reproduce
1.install last ninja form
2.install last popup maker
3.create a simple form with a date picker field
4. create a popup showing the previous form
5. trigger the popup
6. try to select a date

## Errors
no error

**Comment by Yop-La** [comment]
I found a fix. Datepicker is hidden by the popup overlay.

Here a quick fix:

.pum-overlay {
	z-index: 100 !important;
}

**Comment by danieliser** [comment]
I think we can add some CSS to force the z-index of those fixed position dropdowns to always be above our popups as a more permanent solution.
