### ISSUE TITLE
Times for Cookie Variables

### ISSUE THREAD

**Issue by bolderelements** [PopupMaker/Popup-Maker#94]
I couldn't register for an account on the support forums so hopefully it's okay to ask/suggest here?

I am a developer trying to use this plugin for a client's website. The issue is that they have two timing intervals that they want to set their cookies for. The first is 3 days if you simply close the popup and do nothing with it.

The second is a customized one. I found it through one of your tutorials, a small function I can call at another point in our script. In this case, it would be triggered after the customer subscribes to the newsletter (through the form in the popup). I have done this, but it seems to only last three days when the client wants it to not appear for at least a year, if not forever.

I looked up the function you recommended and found there are no possible arguments, it always takes the time value from the plugin settings. Would it be possible to add an argument here where I can customize the time for this one custom call, or is there an extensions or another way of going about it where I could do this?

**Comment by danieliser** [comment]
@bolderelements - Currently our site forums are only for paid support and extension support. We provide free support via the wordpress.org forums.

This is what your looking for though.

https://github.com/PopupMaker/Popup-Maker/blob/master/assets/scripts/popup-maker-site.js#L1136

You will need to replace all of the variables with strings but will do the trick.

**Comment by danieliser** [comment]
This is totally possible now with multiple cookies per trigger etc.
