### ISSUE TITLE
Uncaught TypeError: Cannot read property 'split' of undefined for Contact Form 7

### ISSUE THREAD

**Issue by bimperial** [PopupMaker/Popup-Maker#946]
## Describe the bug
The popup won't close after submitting the form. 

## Site information
Popup Maker version: 1.15.0
Contact Form 7 version: 5.4

WordPress version: 5.6.2

PHP version: 7.3.25

## Expected behavior
The popup will close after submitting the form.

## Current behavior
After submitting Contact Form 7, the popup will not close even when the popup settings in Contact Form 7 is set to close after the delay time.

## Steps to reproduce
1. Edit the contact form 7 - popup settings and select Close Popup with a time delay.
2. Create a new popup and add a trigger condition time delay/auto open.
3. Include the shortcode of Contact Form 7 in the popup content.
4. Navigate to the page where the popup with contact form 7 is available.
5. Submit the form, the popup won't close.

## Additional context
![1](https://user-images.githubusercontent.com/17669050/109082741-813f8200-773f-11eb-8f21-e670db759ecb.png)
![2](https://user-images.githubusercontent.com/17669050/109082749-83a1dc00-773f-11eb-9adb-178c057a2b22.png)

**Comment by danieliser** [comment]
Resolved in 43d24c14ef13c66541ba7bd83d8c1929076f2356
