### ISSUE TITLE
WP 5.7 compat: WP_Scripts::localize was called incorrectly. The $l10n parameter must be an array. To pass arbitrary data to scripts, use the wp_add_inline_script() function instead.

### ISSUE THREAD

**Issue by lkraav** [PopupMaker/Popup-Maker#948]
## Describe the bug
As deprecation notice says, we should probably refactor towards `wp_add_inline_script()`?

## Site information
Popup Maker version: 1.15.0
WordPress version: 5.7 RC2
PHP version: 7.4.15

**Comment by lkraav** [comment]
Pardon, forgot traceback https://sentry.io/share/issue/e3e4141b60344ecf8aa5b282bab7e539/

**Comment by lkraav** [comment]
And when I look at the code comment, this looks like a cleanup job, not a refactor.

**Comment by danieliser** [comment]
@lkraav - Appreciate the report, looks like we already caught this one and its in the latest update going out this week: 27dba3b5ab575487374c591ace68b64d4e8ec5c3
