### ISSUE TITLE
Forced focus doesn't lock on popup if only contains close button

### ISSUE THREAD

**Issue by danieliser** [PopupMaker/Popup-Maker#958]
When the only focusable element in a popup is an extra popup close button the focus doesn't get trapped until they click inside the popup.

- [ ] Ensure that close inside the content are allowed to be targeted as focusable.

**Comment by marklchaves** [comment]
Hi @danieliser,

Do you mean something like this?

https://gist.github.com/marklchaves/210261652cec18a0ba9cb123086bb2fb

Hopefully, I'm understanding the issue correctly.

Thanks!

**Comment by marklchaves** [comment]
## Use Case

When I open a popup that has only text and the default close button, I don't want the browser focus to default to the close button in case I accidentally hit enter right after the popup opens.

## Technical Requirement

If the first focusable element in the popup is a close button, force the focus on the popup content `div` instead to avoid accidentally closing the popup when it first opens.
