### ISSUE TITLE
Auto load popup if shortcode/class is detected.

### ISSUE THREAD

**Issue by danieliser** [PopupMaker/Popup-Maker#96]
If the_content contains classes or a shortcode for a particular popup, ensure its preloaded.

**Comment by fpcorso** [comment]
@danieliser would this mean that users who use our block editor popup trigger wouldn't need to ensure that popup is targeting the page since it would auto-load once the shortcode/class is detected?

**Comment by danieliser** [comment]
@fpcorso Correct, if we detect the popmake class anywhere it would autoload as well.
