### ISSUE TITLE
Microcopy: Change heading and label to the Add New Trigger modal

### ISSUE THREAD

**Issue by marklchaves** [PopupMaker/Popup-Maker#960]
**Choose what type of trigger to add?** isn't a question. 

We can change this _microcopy_ to be more contemporary and conversational like this, **What kind of trigger do you want?** You can see this style of _microcopy_ in **Netflix** (Who's watching Netflix?).

Found under: **Popup Settings** > **Triggers** > **Add New Trigger**.

![popup-maker-add-new-trigger-dropdown](https://user-images.githubusercontent.com/4658423/118731234-80644b00-b86b-11eb-802d-47d8d15b6873.png)

More on _microcopy_ here https://www.sitepoint.com/writing-clear-human-friendly-microcopy/

**Comment by danieliser** [comment]
@marklchaves Would you want to apply that to the other interfaces? We can start a [WIP] PR and you can change them there and merge into releases as we go.

**Comment by marklchaves** [comment]
Hi @danieliser,

Yup. Sure can. A WIP PR would be great. Thanks!
