### ISSUE TITLE
Unwanted outline appears on some popups

### ISSUE THREAD

**Issue by marklchaves** [PopupMaker/Popup-Maker#970]
## Describe the bug

Some popups display an _unwanted_ outline. 

This could be happening as a side-effect of the default focus on `.pum-content` from the 1.16.2 release.

## Site information
Popup Maker version:  1.16.2

WordPress version: 5.7.2

PHP version: 7.3.5

## Expected behavior

By default, there should **not** be an outline when `.pum-content` has focus.

## Current behavior

There's an outline displaying be default on some popups.

## Steps to reproduce
1. Launch a popup.
2. Click inside the popup if no outline is visible right away.
3. Alternatively, click inside the popup and _tab_ around to switch focus on the elements inside the popup.

## Errors

None. There are no functional errors. This is **UX** issue.

## Additional context

https://wordpress.org/support/topic/norder-on-pop-ups/

**Comment by aaditya-cpu** [comment]
+1
we have tried to make changes to the Plugin's CSS added custom CSS but to no effect please look into it it seems to be affecting chrome in majority on Firefox however the occurrence is rare

**Comment by marklchaves** [comment]
Hello @aaditya-cpu,

Can you try this **CSS** if you haven't yet? 

`
.pum-content:focus {
	outline: none !important;
}
`

This is the **CSS** we're testing now for this particular issue.

If you don't see the change take effect right away: 

1. Make sure the CSS is correct.
2. Make sure you saved your change.
3. Please purge all WordPress and browser caches. 
4. Then, try retesting in a private/incognito window.

Please [send in a ticket](https://wppopupmaker.com/support/) if the issue persists so we can check your site.

Thanks!

**Comment by danieliser** [comment]
@aaditya-cpu - Also don't modify the plugin css files, we don't load them, we bundle them via PHP with your customizations and any extensions and save them as a generated CSS file.

Add the custom override using your normal method to test it and we can get a patch out if it works for you.
