### ISSUE TITLE
[WIP] Microcopy enhancements

### ISSUE THREAD

**Issue by marklchaves** [PopupMaker/Popup-Maker#972]
### Proposed guidelines

1. Use title case for headings.
1. Use sentence case for field labels and descriptions. 
1. Avoid punctuation in field labels.
1. Avoid special characters.

**Good label**: Try to bypass ad blockers

**Good label**: Disable categories and tags

**Avoid label**: Disable categories & tags?

### Running list of suggested enhancements

1. Time Delay Settings: _Choose which cookies will disable this trigger?_ (Remove the question mark.)
1. Popup Maker Settings > Misc > Assets: _Check this disable loading ..._ (Change to: _This stops Google Fonts from loading. This is useful ..._)
2. Add Trigger: _Stop showing popup once visitor takes this action:_ (Remove the colon.)

**Comment by marklchaves** [comment]
Fix typo in admin bar notification. Change "reseet" to "reset".

![popup-maker-admin-bar-notificationtypo](https://user-images.githubusercontent.com/4658423/136646507-5c689847-1cc9-432a-99a9-54b54475dcb0.png)
.

**Comment by danieliser** [comment]
How did you want to handle this @marklchaves, small batches, one big PR?

**Comment by danieliser** [comment]
Updated the suggested ones above
