### ISSUE TITLE
Fatal error on page not found

### ISSUE THREAD

**Issue by bceyssens** [PopupMaker/Popup-Maker#974]
## Describe the bug
`Notice: Undefined property: stdClass::$post_type in .../plugins/popup-maker/classes/ConditionCallbacks.php on line 279`

## Site information
Popup Maker version: 1.16.2
WordPress version: 5.8
PHP version: 7.4

## Steps to reproduce
1. Navigate to a path that doesn't exist

## Errors
`Notice: Undefined property: stdClass::$post_type in .../plugins/popup-maker/classes/ConditionCallbacks.php on line 279`

**Comment by danieliser** [comment]
@bceyssens - Hmm, I haven't seen this before. Can you retest with the Health Check plugin's Troubleshooting mode activated for our plugins and eliminate conflict as a reason for the issue?
