### ISSUE TITLE
List is empty but entries are in the database

### ISSUE THREAD

**Issue by wursterje** [PopupMaker/Popup-Maker#976]
## Describe the bug

Popup list is empty but 67 entries are in the database.

![image](https://user-images.githubusercontent.com/14123012/136193114-deba5541-8a06-44a9-9bb5-77f17edbad45.png)

## Site information
Popup Maker version: 1.16.2

WordPress version: 5.8.1

PHP version: 7.4.24

## Additional context

Free version in use.

**Comment by marklchaves** [comment]
Hi @wursterje,

​Thanks for reaching out. We're sorry you're seeing an empty list of popups.

Any chance you're running **WPML**? If so, can you see if this support thread helps you?

https://wordpress.org/support/topic/old-popups-not-showing-up-anymore/#post-14888938

If that doesn't do the trick and you want help, please reach out to us here.

https://wppopupmaker.com/support/

Cheers!

**Comment by wursterje** [comment]
@marklchaves

Solved! Thanks for the quick response!
