### ISSUE TITLE
Add a PHP filter to disable the example popup from being created

### ISSUE THREAD

**Issue by marklchaves** [PopupMaker/Popup-Maker#978]
## Describe the feature request

Add a PHP filter to disable the example popup from being created.

## Use case

Every time Popup Maker is activated, it creates an example popup. It'd be sweet if that can be disabled.

This feature would avoid unnecessary popup bloat when troubleshooting the plugin.

### OP 

https://wordpress.org/support/topic/random-example-created-popups-after-enable-disable/

### Suggested code change

Line 121 classes > Install.php 

```php
		if ( !apply_filters( 'popup_maker_disable_example_popup' , '' ) ) {
			pum_install_example_popups();
		}
```

**Comment by danieliser** [comment]
This should really only be done on first activation. Lets update this to fix it by setting a flag so we just don't even try to install it a second time, no need to manually filter then.
