### ISSUE TITLE
Adding the do-default CSS class to a link does not open the destination page

### ISSUE THREAD

**Issue by marklchaves** [PopupMaker/Popup-Maker#979]
## Describe the bug

There might be an issue with using the `do-default` class to open a link from inside a popup. The popup closes but the destination never opens.

## Site information
Popup Maker version: 1.16.2

WordPress version: 5.8.1

PHP version: 7.4.1

## Expected behavior

The popup should close and the destination page should open.

## Current behavior

The popup closes, but the destination never opens.

See the [original post](https://wordpress.org/support/topic/link-not-opening-2/) and test #5 on this [test page](https://streetphotography.blog/test-popup-close-links/).

## Errors

No error messages.

**Comment by danieliser** [comment]
@marklchaves Its `pum-do-default`, there is also a data-do-default="true" parameter that does the same: https://github.com/PopupMaker/Popup-Maker/blob/master/assets/js/src/site/plugins/pum.js#L437

**Comment by marklchaves** [comment]
> @marklchaves Its `pum-do-default`, there is also a `data-do-default="true"` parameter that does the same: https://github.com/PopupMaker/Popup-Maker/blob/master/assets/js/src/site/plugins/pum.js#L437

Ah, it wasn't right in the [doc](https://docs.wppopupmaker.com/article/303-close-a-popup-when-a-link-inside-the-popup-is-clicked). I should've cross-referenced the code first 😬 

I [tested](https://streetphotography.blog/test-popup-close-links/) with `pum-do-default` and updated the doc.

Thank you, @danieliser 😌

**Comment by danieliser** [comment]
Sweet, glad I could help.
