### ISSUE TITLE
Remove extra "/" from //assets/sounds path

### ISSUE THREAD

**Issue by marklchaves** [PopupMaker/Popup-Maker#984]
## Source (v 1.16.3)

[https://github.com/PopupMaker/Popup-Maker/blob/89e4ecc68b6f1df80c6817b4c493f25bc6e90cd5/assets/js/site.js#L343](https://github.com/PopupMaker/Popup-Maker/blob/89e4ecc68b6f1df80c6817b4c493f25bc6e90cd5/assets/js/site.js#L343)

## Debugger

<img width="1545" alt="popup-maker-assets-sounds-path-extra-slash" src="https://user-images.githubusercontent.com/4658423/145941026-f3103707-a6e2-40b0-ac2b-679aff7c11f0.png">

## Extra Screen Capture

![popup-maker-double-slash-assets-sounds](https://user-images.githubusercontent.com/4658423/145941648-9368c852-df6e-4c53-a5a1-6e019f8cdb0b.png)

**Comment by danieliser** [comment]
Fixed
