### ISSUE TITLE
Disable the Preview button when previews are not possible (or allow previews even when popups are disabled)

### ISSUE THREAD

**Issue by marklchaves** [PopupMaker/Popup-Maker#991]
## Describe the feature request

Either disable the **Preview** button when previews are not possible or show previews when popups are disabled (preferred for consistency).

See the **Use case** section for more details.

OP: https://wordpress.org/support/topic/preview-broken/

Related issue: https://github.com/PopupMaker/Popup-Maker/issues/556

## Use case

1. If I edit a popup that's disabled, the **Preview** button is active and when I click it, it brings up a browser window but the popup never appears (because it's disabled).
2. I can save a new popup as a draft. When I do that, the **Preview** button appears. (Note: There's no enable button because the popup is still not published.) Again, the **Preview** button is active yet useless and creates confusion.

**Comment by danieliser** [comment]
This one should be fixed in `develop` branch

**Comment by marklchaves** [comment]
Tested with:

1. Enabled popup
2. Disabled popup
3. Draft popup

Looks good!
